### ISSUE TITLE
How am I supposed to build the redirect-url?

### ISSUE THREAD

**Issue by cvgaviao** [MaikuB/flutter_appauth#100]
I have set my google account to accept auth for one API and set my app (already is androidx) to use the flutter_appauth with:
```
manifestPlaceholders = [
                'appAuthRedirectScheme': 'com.c8tech.myapp'
        ]
```
I'm creating the AuthorizationTokenRequest using 'com.c8tech.myapp' as redirect_url and `openid` as the unique scope. But I'm receiving a 400 error: `Invalid parameter value for redirect_uri: Missing scheme: com.c8tech.myapp`

please, what am I missing?

btw, how can I specify the path to a specific page?

**Comment by MaikuB** [comment]
Your URI needs to have the scheme as part of it (e.g. `com.c8tech.myapp://...`). This is what the error message is trying to tell you

**Comment by cvgaviao** [comment]
@MaikuB, thanks for your time. ;)

When I tried to use `com.c8tech.myapp://home` I receive another error 400:
`Custom schemes cannot have authority: com.c8tech.myapp://home`

**Comment by cvgaviao** [comment]
I was trying to understand a bit more.. 
I saw that google console have created two `redirect_uris`: `urn:ietf:wg:oauth:2.0:oob` and "http://localhost". 
Am I supposed to use `urn:ietf:wg:oauth:2.0:oob` as the custom scheme ?

**Comment by cvgaviao** [comment]
Ok, after many hours trying and failing I finally get it working. 
Google requires you to use the app's package name for the "appAuthRedirectScheme" property. :D

**Comment by NightOwlCoder** [comment]
> Ok, after many hours trying and failing I finally get it working.
> Google requires you to use the app's package name for the "appAuthRedirectScheme" property. :D

Thank you @cvgaviao, after 5h of search, search and search, finally some suggestion that made it work!

@MaikuB this information should be more easy to find, your component seems great, but we suffered a lot for get it going....

**Comment by MaikuB** [comment]
Restrictions enforced by identity providers don't relate to the plugin so I'm not sure what you're hoping would be in the readme except for developers to read the docs for identity providers they're using. Developers will normally need to check the documentation to find out the scopes supported and extra parameters they need to provide. What @cvgaviao described isn't applicable for all providers.

**Comment by edihasaj** [comment]
I've put a workaround here:  #141
