### ISSUE TITLE
Self discovery looks to be stripping a parameter for Azure B2C

### ISSUE THREAD

**Issue by dwhiteddsoft** [MaikuB/flutter_appauth#101]
An Azure B2C endpoint does not only have authorize but the parameter(p) as the flow (ie. B2C_1_susi). If I use the following code:
`  final clientId = '90185a76-af9b-4ff0-9fdc-55c888583e2d';
  final redirectURL = 'com.davetest.wow://oauthredirect';
  final discoveryURL =
      'https://detroitdaveb2c.b2clogin.com/detroitdaveb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_susi';
  final List<String> scopes = ['openid'];`
When I get redirected I get a 404. If I look at the URL given to the browser on iOS I see that parameter is not there (thus the 404). Yet if I look at the discovery endpoint for the above I can see the authorize endpoint as: "authorization_endpoint": "https://detroitdaveb2c.b2clogin.com/detroitdaveb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_susi",

I have tried to set it manually with AuthorizationServiceConfiguration like so:
`    result = await _appauth.authorizeAndExchangeCode(
      AuthorizationTokenRequest(clientId, redirectURL, 
          issuer: "https://detroitdaveb2c.b2clogin.com/c8e21a93-15de-4b73-9004-b86ab87c27ea/v2.0/",
          serviceConfiguration: new AuthorizationServiceConfiguration(
              "https://detroitdaveb2c.b2clogin.com/detroitdaveb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_susi",
              "https://detroitdaveb2c.b2clogin.com/detroitdaveb2c.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1_susi"),
          //discoveryUrl: discoveryURL,
          scopes: scopes),`
to no avail. If I just change values in your sample app I get the same issue. Any help would be appreciated

**Comment by MaikuB** [comment]
Try the solution mentioned here https://github.com/MaikuB/flutter_appauth/issues/62#issuecomment-562003161

**Comment by MaikuB** [comment]
The other thing I forgot to mention is I had some issues in the past as well where there was conflicting information on the URLs to use. For example, you can see [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/signin-appauth-ios?tabs=applications) that the policy (the `p` parameter) is part of the URL path as opposed to being a query string. It's been a while but I think using that approach had worked for me back then

**Comment by dwhiteddsoft** [comment]
I wrote a blog post about doing this all with Azure B2C. Discovery URLs dont work and the 'p' parameter thing does not work consistently as well with library. I hope it is useful https://www.detroitdave.dev/2020/04/simple-azure-b2c-flutter.html

**Comment by MaikuB** [comment]
Nice one. Yeah I recall having a similar issue with discovery that I specified the endpoints directly though a former colleague seemed to have gotten it with discovery. His blog post is at https://nicksnettravels.builttoroam.com/connecting-flutter-to-azure-ms-ignite/. Maybe he got lucky 😅

**Comment by dwhiteddsoft** [comment]
yeah my experience was his code runs fine on Android but not on iOS as it will get a 404. Thanks for all the help :-)

**Comment by bryanCancelWT** [comment]
@dwhiteddsoft I followed you post but had to go my own way
since it seems a lot has changed in 2 years
for anyone trying to solve this now


search for my comments on this repo
you will find how to configure everything for iOS and android and get around nearly every issue with using flutter app auth with azure ad at the moment
