### ISSUE TITLE
Generic error when cancelling on iOS

### ISSUE THREAD

**Issue by xiprox** [MaikuB/flutter_appauth#105]
- Start flow / open browser
- Cancel

The following exception is thrown:
```
PlatformException(authorize_and_exchange_code_failed, Failed to authorize: The operation couldn’t be completed. (org.openid.appauth.general error -3.), null)
```

The auth flow works if the user proceeds instead of cancelling, and different (specific) errors are thrown on Android.

Here's my catch block that successfully handles everything on Android:
```dart
} catch (e) {
  if (e?.message?.contains('User cancelled flow') == true ||
      e?.message?.contains('The user has denied access') == true) {
    connectedAccountSigningIn.sink.add(false);
    return;
  }
  return _onConnectedAccountSignInError(e?.toString());
}
```

Obviously, I can't add a generic error in there.

Is this the intended behavior? Any chance we can get a specific error on iOS as well?

To begin with, this way of error handling with `contains` is fragile. Is there a particular reason the package just throws PlatformExceptions on cancel, as opposed to say, a field in the result?

**Comment by MaikuB** [comment]
The plugin wraps around native Android and iOS SDKs, each of which were developed independently and thus can have different errors. A `PlatformException` is thrown as they are the appropriate type of exceptions that should be thrown (see docs https://api.flutter.dev/flutter/services/PlatformException-class.html). It is how plugins are supposed to indicate that an error has happened in general.

With regards to getting a specific error, you could either check the native SDK to see what it throws or investigate if it's possible to align the errors from both Android and iOS to return the same error when caught within a Flutter app. PRs are welcome

**Comment by xiprox** [comment]
Thanks for the quick reply!

Looked into the iOS source code and found [this](https://github.com/openid/AppAuth-iOS/blob/65ef95c6b38c7889fdda7a22f242fa0156fd43b2/Source/OIDError.h#L103):
```c
  /*! @brief Indicates the user manually canceled the OAuth authorization code flow.
   */
  OIDErrorCodeUserCanceledAuthorizationFlow = -3,
```

`-3` is specific, after all.

**Comment by Abhishek01039** [comment]
Hello @xiprox 
can you please let me know that how you handle the exception?
```
throw Exception('Something went wrong. Please try again');
```

I have something like this but I need more effective error messages to show the users like this:
```
 if (e?.message?.contains('User cancelled flow') == true ||
      e?.message?.contains('The user has denied access') == true) {
    connectedAccountSigningIn.sink.add(false);
    return;
  }
```

**Comment by xiprox** [comment]
Hey @Abhishek01039.

Looks like this is what we did at the time:
```dart
if (e?.message?.contains('User cancelled flow') == true ||
    e?.message?.contains('The user has denied access') == true ||
    e?.message?.contains('general error -3') == true) {
```

Not sure what else I can tell you. :)

**Comment by Abhishek01039** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/56479665/126443190-fadc6553-9ac0-44c3-9588-1c3816fa0cfa.png">
I am not able to use the message variable 
and also I want all the possible exception so that I can show it to users

**Comment by Abhishek01039** [comment]
Hello @xiprox 
can you please take a look at above error?

**Comment by xiprox** [comment]
Do you specify a type for `e` in your catch block? Can you post your code without the error overlay?

**Comment by Abhishek01039** [comment]
Hey @xiprox 
I have done like this to access `message`
```
 } on PlatformException catch (e) {
      if (e.message?.contains('general error -3') == true) {
        print('manually canceled the OAuth authorization code flow.');
      } else if (e.message?.contains('general error -5') == true) {
        print('network error or server error occurred.');
      }
}
```

and do you have any general way to handle exception?

**Comment by xiprox** [comment]
Ahh. If you remove `on PlatformException` it should catch every exception.

**Comment by Abhishek01039** [comment]
Hello @xiprox 
but if I remove `PlatformException` then I am not able to access the message.

**Comment by xiprox** [comment]
Loaded my project with this code and I seem to be getting the same error now. Don't have much of an idea to be honest. You might be better off asking on StackOverflow.

**Comment by Abhishek01039** [comment]
@xiprox 
I think if we use `PlatformException` then I am able to access the `message`.

**Comment by Abhishek01039** [comment]
Hello @xiprox 
do you have the errors code or string like [this](https://github.com/openid/AppAuth-iOS/blob/65ef95c6b38c7889fdda7a22f242fa0156fd43b2/Source/OIDError.h#L103) for android?

**Comment by Abhishek01039** [comment]
and also @xiprox 
if the server is not able to respond then also it catches `general error -3`.
