### ISSUE TITLE
Add PKCE code challenge method parameter to AuthorizationTokenRequest constructor  

### ISSUE THREAD

**Issue by tchabot22** [MaikuB/flutter_appauth#106]
It would be helpful to have a parameter added to AuthorizationTokenRequest constructor to indicate the supported PKCE CodeChallengeMethod for the server we're making the request to.  It appears that it defaults to S256.  Would it be possible to add support for 'plain' or none?  In my case I'm connecting to a server that doesn't support a code challenge method as it is an option field in OAuth2. 

When I try this on Android it seems to work but I see in AppAuth-Android they have logic for falling back to Plain PKCE code challenge method if S256 isn't supported.  This doesn't appear to be the case in AppAuth-iOS but there is the ability to set it in both per this: 

https://stackoverflow.com/questions/35566299/how-can-i-use-the-plain-pkce-code-challenge-method-with-appauth/35566300#35566300

Thanks for your consideration!

**Comment by MaikuB** [comment]
I'm not looking to work on this at the moment and you appear to be across where it is in the native SDKs so I would suggest you consider submitting a PR

**Comment by MaikuB** [comment]
Closing as it's not something I will work out. Please submit a PR if it's something you need
