### ISSUE TITLE
Refresh token is null

### ISSUE THREAD

**Issue by boylenssen** [MaikuB/flutter_appauth#107]
I'm successfully logging in using the following code:

```
      result = await appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(_azureClientId, _redirectUrl,
            discoveryUrl: _discoveryUrl,
            scopes: ['openid', _azureClientId]),
      );

      authenticationRepository.token = "Bearer ${result.accessToken}";
```

But at one time, the token will expire and I need to refresh it, but I'm not getting a refreshtoken, the field is null.

Am I missing something, do I need to handle this differently?

the discovery URL looks like this:

https://<undisclosed>.b2clogin.com/$_azureTennant/B2C_1_SignIn/v2.0/.well-known/openid-configuration

In previous (native Android) development I called `acquireTokenSilent()` to log in without needing to show the login dialog in case the user has logged in before.
I'm trying to get the same UX here

I tried setting `promptvalues` to `['none']`, but still show the webview coming up

**Comment by MaikuB** [comment]
You're missing the `offline_access` scope. I'd suggest you compare your code with what is discussed in the Azure B2C docs. Getting a refresh token works fine as demonstrated by the example app in this repo

**Comment by boylenssen** [comment]
Ow thanks a lot!! 
I'm so confused by the Azure AD authentication all the time, it seems so complex.
Thanks for your work, I'm able to refresh my token now !
I just noticed that this is also in the description of the readme 🤦  sorry

Didn't find an option to buy you a coffee, is it somewhere? Appreciate your work

**Comment by MaikuB** [comment]
> Ow thanks a lot!!
I'm so confused by the Azure AD authentication all the time, it seems so complex.
Thanks for your work, I'm able to refresh my token now !
I just noticed that this is also in the description of the readme facepalm sorry

No worries

> Didn't find an option to buy you a coffee, is it somewhere? Appreciate your work

There isn't one but I appreciate the sentiment :)
