### ISSUE TITLE
Are there plans to implement more openid endpoints, such as user info endpoint?

### ISSUE THREAD

**Issue by markphillips100** [MaikuB/flutter_appauth#11]
I'm not sure if both the iOS and Android openid AppAuth libs support calling the user info endpoint in their implementations, but if they do, are there plans to surface the API in this package?

Somebody already asked about [signout](https://github.com/MaikuB/flutter_appauth/issues/10), which is also needed if it's necessary to support sign out of the single sign-on session.  I can live with just deleting the local session data for signing out. however user info is a must for me.

**Comment by MaikuB** [comment]
They do not, in fact the samples I've seen involve manually creating a web request to get the user info

**Comment by markphillips100** [comment]
Okay, thanks for the quick update @MaikuB.

I guess it wouldn't be difficult to implement the request ourselves as required.  It is just a web request using a token after all.
