### ISSUE TITLE
redirectUrl?

### ISSUE THREAD

**Issue by ghenry** [MaikuB/flutter_appauth#114]
Hi all,

What is https://github.com/MaikuB/flutter_appauth/blob/master/flutter_appauth/example/lib/main.dart#L32

`  final String _redirectUrl = 'io.identityserver.demo:/oauthredirect';`

This doesn't look like a normal Url. Google shows nothing to me. Is this `demo.identityserver.io` in reverse?

Thanks.

**Comment by ghenry** [comment]
I see this matches https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth#android-setup `appAuthRedirectScheme` which I'm confused about. Will look at Google and update here.

**Comment by ghenry** [comment]
Ah, clearly explained here:

https://github.com/openid/AppAuth-android#capturing-the-authorization-redirect

**Comment by ghenry** [comment]
For me, if I set:

`redirectUrl` to say uk.co.surevoip.portal:/oauth2redirect I see that taken for the actual Url, so I have had to set this to a real Url.

AppAuthRedirectScheme is just about in reverse though, without the `oauth2redirect` part as per above link.

Thanks.

**Comment by ghenry** [comment]
My misunderstanding. This is the Url to send the tokens etc. back to which is the local app Url this is anything you register in the android/ios section. Closing.

**Comment by MaikuB** [comment]
Yes it's the redirect URL you configured on the server side

**Comment by ghenry** [comment]
> Yes it's the redirect URL you configured on the server side

Yep, needs to match what you set when your registered your client on the oauth2 side.

**Comment by edihasaj** [comment]
I've put a workaround here:  #141
