### ISSUE TITLE
use flutter_appauth connect local IdentityServer4 came across http and https problems

### ISSUE THREAD

**Issue by cheapw** [MaikuB/flutter_appauth#116]
Hello, I use the sample to connect IdentityServer4 demo site (https://demo.identityserver.io) , everything is OK. But when I connect my own local IdentityServer4 server, some problems occurred. 

when I set the issuer to http://<my local IP>:5000 (the IdentityServer also made the corresponding config and authorize and token endpoint were also configured properly), after running the app and clicking Sign in with no code exchange button, the app flashed back, the crucial error log is 
java.lang.IllegalArgumentException: only https connections are permitted.

when I set the issuer to https://<my local IP>:5000 (the IdentityServer also make the corresponding config but I don't know how to get a valid ssl certificate), after running the app and click the button, the crucial error log is
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

I also found TokenRequest class and AuthorizationRequest class both has a parameter named allowInsecureConnections and its default value is false, I have set both the parameter of the instance of the TokenRequest and AuthorizationRequest class to true, but the running result was the same as above. The allowInsecureConnections didn't work.

I have had read the FlutterAppauthPlugin.java source code, I found that the TokenRequestParameters and AuthorizationTokenRequestParameters class don't have the allowInsecureConnections parameter,  processAuthorizationTokenRequestArguments and processTokenRequestArguments method also don't retrieve the allowInsecureConnections  parameter from the arguments. Hasn't this parameter been implemented yet. Is there a way to connect to the IdentityServer using http or make the app trust the unsafe https local endpoint. Thanks!

**Comment by MaikuB** [comment]
Have you tried what's mentioned [here](https://github.com/MaikuB/flutter_appauth/issues/12#issuecomment-591231534)? If this doesn't work then you'll need to look at a way to get it to work on your own or get a server with a signed certificate setup. The work for adding `allowInsecureConnections` was a community contribution. If this is causing issues then the community can help look at providing a fix. Otherwise, I might need to consider removing support for it

**Comment by MaikuB** [comment]
Closing due to lack of further response
