### ISSUE TITLE
how can we use http as well or https with self signed certificate 

### ISSUE THREAD

**Issue by harpreetfervaha** [MaikuB/flutter_appauth#12]
In the android we can use  ConnectionBuilder}that permits connecting to http links, and ignores certificates for https connections. 
is there any way to use http instead of https.
I am getting this error if I am trying to use http

E/AndroidRuntime( 4341): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 4341): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
E/AndroidRuntime( 4341): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 4341): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 4341): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 4341): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime( 4341): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime( 4341): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime( 4341): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime( 4341): Caused by: java.lang.IllegalArgumentException: only https connections are permitted
 And can we use https with self signed certificate

**Comment by MaikuB** [comment]
Not at this stage, given you seem to be familiar with what's required and require this functionality,  are you able to submit a PR?

**Comment by harpreetfervaha** [comment]
so its don't support https with a self-signed certificate?

**Comment by MaikuB** [comment]
My understanding is you need make use of the connection builder for either http or https with self-signed certificates and your original post has said as much so as per my previous reply, not at this stage. The code is there for you to confirm and you should be able to verify this if needed. The identity providers I have tested this with have also been mentioned in the readme

**Comment by balu-ce** [comment]
@harpreetfervaha  Can you able to solve this issue. I cannot able to use simply http.

**Comment by harpreetfervaha** [comment]
> @harpreetfervaha Can you able to solve this issue. I cannot able to use simply http.

I used https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/ConnectionBuilderForTesting.java

**Comment by balu-ce** [comment]
can you give some flutter example code on that.

Thanks,
Bala

**Comment by harpreetfervaha** [comment]
I used the platform channel to call the java code from the flutter.
 static const MethodChannel _methodChannel = MethodChannel('define CHANNEL at MainActivity.java);
 String result = await _methodChannel.invokeMethod("mehod define in java basically call the https://github.com/openid/AppAuth-Android/blob/master/app/java/net/openid/appauthdemo/LoginActivity.java");
LoginActivity.java is calling ConnectionBuilderForTesting.java internally

**Comment by MaikuB** [comment]
Closing this as it's not something I'll be working on. Contributions are working though

**Comment by arunkarri** [comment]
@harpreetfervaha can you give the exact code for flutter implementation

**Comment by Cir0X** [comment]
Im using `0.5.0` and I still get an Exception on Android:

```
E/AndroidRuntime(11434): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(11434): Process: <package_name>, PID: 11434
E/AndroidRuntime(11434): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(11434):        at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime(11434):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(11434):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(11434):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(11434):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(11434):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(11434):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(11434):        at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(11434): Caused by: java.lang.IllegalArgumentException: only https connections are permitted
E/AndroidRuntime(11434):        at net.openid.appauth.Preconditions.checkArgument(Preconditions.java:116)
E/AndroidRuntime(11434):        at net.openid.appauth.connectivity.DefaultConnectionBuilder.openConnection(DefaultConnectionBuilder.java:51)
E/AndroidRuntime(11434):        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:327)
E/AndroidRuntime(11434):        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:305)
E/AndroidRuntime(11434):        at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(11434):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(11434):        ... 4 more
```

Furthermore I tried to add `android:usesCleartextTraffic="true"` to the `AndroidManifest.xml` `application` tag.
Any ideas how I get unsecure http connections working on Android?

**Comment by MaikuB** [comment]
Perhaps the changes done don't fully work then. You may need to fork and try to address this issue yourself and submit a PR. I suspect searching around may lead to solutions, problem is I don't have access to a http auth server to test so need to rely on community contributions for this functionality.

**Comment by jaggerwang** [comment]
I've successfully resolved this issue by specify `allowInsecureConnections` to `true`, and add attribute `android:usesCleartextTraffic="true"` to node `application` in `AndroidManifest.xml`.

```dart

    final response =
        await appAuth.authorizeAndExchangeCode(AuthorizationTokenRequest(
      config.oAuth2Config.clientId,
      config.oAuth2Config.redirectUrl,
      serviceConfiguration: AuthorizationServiceConfiguration(
        config.oAuth2Config.authorizationEndpoint,
        config.oAuth2Config.tokenEndpoint,
      ),
      scopes: config.oAuth2Config.scopes,
      allowInsecureConnections: true,
    ));

```

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="net.jaggerwang.fip">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application android:name="io.flutter.app.FlutterApplication" android:label="FlutterInPractice" android:icon="@mipmap/ic_launcher" android:usesCleartextTraffic="true">
        ...
    </application>
</manifest>
```

**Comment by haarts** [comment]
I've had no luck with the same approach as @jaggerwang. Version 0.8.1 of the package. It is relatively easy to test with [Keycloak](https://keycloak.org/).

**Comment by vasurana** [comment]
Hey I have got the same error after adding allowInsecureConnections to true, and android:usesCleartextTraffic="true". Can you please share your code. I need some help here.
