### ISSUE TITLE
iOS build issue - include of non-modular header inside framework module

### ISSUE THREAD

**Issue by athornz** [MaikuB/flutter_appauth#125]
I'm unable to build my project after updating to `0.9.1+1`.

I get the following error:

```
 In file included from /myproject/build/ios/Release-stage-iphoneos/flutter_appauth/flutter_appauth.framework/Headers/flutter_appauth-umbrella.h:14:
    /myproject/build/ios/Release-stage-iphoneos/flutter_appauth/flutter_appauth.framework/Headers/OIDExternalUserAgentIOSNoSSO.h:20:9: error: include of non-modular header inside framework module 'flutter_appauth.OIDExternalUserAgentIOSNoSSO': '/myproject/build/ios/Release-stage-iphoneos/AppAuth/AppAuth.framework/Headers/OIDExternalUserAgent.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import "OIDExternalUserAgent.h"
            ^
    1 error generated.
    /myproject/ios/Runner/GeneratedPluginRegistrant.m:62:9: fatal error: could not build module 'flutter_appauth'
    #import <flutter_appauth/FlutterAppauthPlugin.h>
     ~~~~~~~^
    2 errors generated.
```

Any ideas on how to fix it?

**Comment by MaikuB** [comment]
Hmm drats, didn't happen when building the example. Maybe due to different build settings. I won't get to look into it yet until much later in the day. If you happen to be able to find a fix before then and can submit a PR though then would be much appreciated. I believe a rollback to 0.9.1 would likely fix this but result in some warnings (#123).

**Comment by MaikuB** [comment]
A quick thought is that perhaps the plugin should be importing the AppAuth header file instead

**Comment by MaikuB** [comment]
@athornz got a fix up in the `fix_nonmodular_import` branch that I've tested. Any chance you'd be able to reference that branch to confirm it fixes the issue for you as well?

**Comment by MaikuB** [comment]
All good now. It didn't get picked up before as it only happened on iOS apps using Swift. Will get the fix out soon

**Comment by imosmanyilmaz** [comment]
Thanks solved !
