### ISSUE TITLE
App Crash on Redirect back after success logout : Able to logout & redirect back with hack but app crash

### ISSUE THREAD

**Issue by mayank250004** [MaikuB/flutter_appauth#134]
App redirect back after logout ( code at bottom) with following stack , please help me . I only want to fix these crash

> 
> java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65030, result=-1, data=Intent { dat=in.test.mynk://redirect?state=QLMMftuvLn0Kx3qsGihJtw (has extras) }} to activity {in.test.mynk/in.test.mynk.MainActivity}: java.lang.IllegalStateException: authorizationCode not available for exchange request
> E/AndroidRuntime( 3416): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4458)
> E/AndroidRuntime( 3416): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4500)
> E/AndroidRuntime( 3416): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
> E/AndroidRuntime( 3416): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> E/AndroidRuntime( 3416): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> E/AndroidRuntime( 3416): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
> E/AndroidRuntime( 3416): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime( 3416): 	at android.os.Looper.loop(Looper.java:201)
> E/AndroidRuntime( 3416): 	at android.app.ActivityThread.main(ActivityThread.java:6861)
> E/AndroidRuntime( 3416): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 3416): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> E/AndroidRuntime( 3416): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> E/AndroidRuntime( 3416): Caused by: java.lang.IllegalStateException: authorizationCode not available for exchange request
> E/AndroidRuntime( 3416): 	at net.openid.appauth.AuthorizationResponse.createTokenExchangeRequest(AuthorizationResponse.java:458)
> E/AndroidRuntime( 3416): 	at net.openid.appauth.AuthorizationResponse.createTokenExchangeRequest(AuthorizationResponse.java:444)
> E/AndroidRuntime( 3416): 	at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.processAuthorizationData(FlutterAppauthPlugin.java:400)
> E/AndroidRuntime( 3416): 	at io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.onActivityResult(FlutterAppauthPlugin.java:373)
> E/AndroidRuntime( 3416): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
> E/AndroidRuntime( 3416): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
> E/AndroidRuntime( 3416): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
> E/AndroidRuntime( 3416): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:584)
> E/AndroidRuntime( 3416): 	at android.app.Activity.dispatchActivityResult(Activity.java:7598)
> E/AndroidRuntime( 3416): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4451)
> 

**Code Iam Using** 

```
 void _logout() async {
    try {
      //pr.show();
      final AuthorizationTokenResponse result =
      await _appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
            LOGIN_SERVER_CLIENT_ID,
            LOGIN_SERVER_REDIRECT_URL_redirectUrl,
            discoveryUrl: LOGIN_SERVER_DISCOVERY_URL,
            promptValues: ['login'],
            additionalParameters: {"id_token_hint": {idToken{, "post_logout_redirect_uri":  LOGIN_SERVER_REDIRECT_URL_redirectUrl},
            serviceConfiguration: AuthorizationServiceConfiguration(
                "https://{url}/connect/endsession", "https://{url}/connect/token")

        ),
      );

    log('Mayank: "Logout');

    } on Exception catch (_) {
    log('Mayank: "Crash');
    }
  }
```

**Comment by MaikuB** [comment]
This was already discussed in 
https://github.com/MaikuB/flutter_appauth/issues/133

You're asking for a fix for something that isn't supported to begin with. Asking a maintainer to be involved is therefore not reasonable given the problem was created by your choice and therefore ownership of solving this is issue for your application belongs to you
