### ISSUE TITLE
Android browser does not return

### ISSUE THREAD

**Issue by vinodshinde** [MaikuB/flutter_appauth#137]
Hi,
I am trying to use this library for my Flutter app.
I tried the code from exmaple https://pub.dev/packages/flutter_appauth/example

The system browser opens, I login using bob/bob, then web page says it will return to app, but it never returns.
Am i missing anything?

Thanks,
Vinod

**Comment by MaikuB** [comment]
Sounds like you only copied the code. There's setup that need to be done for each platform that's covered in the readme. If you can't be bothered to do so for whatever reason then download/clone the repo and run the example app from there as it would be preconfigured properly
