### ISSUE TITLE
Integration with Native WebView

### ISSUE THREAD

**Issue by Jojoooo1** [MaikuB/flutter_appauth#138]
Hi,

Are you planning to propose a native webview integration within the plugin ?

Thanks for the amazing work!

All the best.

Jonathan.

**Comment by MaikuB** [comment]
Can you please clarify what you mean here. On Android and iOS, these are using the native webviews/browsers that are supposed to open as per security best practices. Furthermore, this plugin has already been described as a wrapper for the native AppAuth SDKs that handle all of that stuff and I'm not involved in writing those SDKs, nor do I plan to move the plugin away from using the SDKs (assuming that is what you're effectively proposing)

**Comment by MaikuB** [comment]
Closing due to lack of further response/clarification
