### ISSUE TITLE
Logout missing?

### ISSUE THREAD

**Issue by draganjovanovic1** [MaikuB/flutter_appauth#14]
Hi, I am new to Dart / Flutter thing :) 

I am evaluating the lib. So far so good but I can't find way to logout from the IdentityServer. Any plans to implement this? Or if it is already there I would appreciate guidance. Thanks.

**Comment by MaikuB** [comment]
The functionality isn't there as this is a wrapper around the native AppAuth libraries that currently don't support it. Thus, if you need to implement something like single sign out then you'll need to look at implementing yourself

**Comment by draganjovanovic1** [comment]
Ok, thanks.
