### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by casetofon** [MaikuB/flutter_appauth#140]
I set the redirect_url parameter and the 'appAuthRedirectScheme' in build.gradle but still get

Invalid parameter value for redirect_url: Missing scheme

**Comment by BrightChad** [comment]
I literally just did this a few minutes ago and it worked for me. This is my default config (with the identifiers changed). Can you post yours? Did you go with all lower-case as suggested in the readme? 


defaultConfig {
        applicationId "com.example.app"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        manifestPlaceholders = [
            'appAuthRedirectScheme': 'msauth.com.example.app://auth'
        ]
    }

**Comment by casetofon** [comment]
Sorry I took so long but I was trying to come up with a "show me yours I'll show you mine joke".. to no avail. Anyway, here's how mine looks: 
defaultConfig {   
        applicationId "io.crossingthestreams.flutterappauthexample"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [
                'appAuthRedirectScheme': 'ai.autonet.afterme'
        ]
    }
Did you clone the example project or did you manually recreate it?

**Comment by casetofon** [comment]
Here's how I changed the strings to work with Youtube API. Help me. We are 5 brothers at home.

const AUTH0_DOMAIN = 'https://accounts.google.com/o/oauth2/auth';
const AUTH0_CLIENT_ID =
    'somethingsomething.apps.googleusercontent.com';

const AUTH0_REDIRECT_URI = 'ai.autonet.afterme';
const AUTH0_ISSUER = 'https://www.googleapis.com/oauth2/v1/certs';
const AUTH0_TOKEN = "https://oauth2.googleapis.com/token";
var scopes = [
  "https://www.googleapis.com/auth/youtube",
  "https://www.googleapis.com/auth/youtube.upload",
];

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _isBusy = false;
  final FlutterAppAuth _appAuth = FlutterAppAuth();
  String _codeVerifier;
  String _authorizationCode;
  String _refreshToken;
  String _accessToken;
  final TextEditingController _authorizationCodeTextController =
      TextEditingController();
  final TextEditingController _accessTokenTextController =
      TextEditingController();
  final TextEditingController _accessTokenExpirationTextController =
      TextEditingController();

  final TextEditingController _idTokenTextController = TextEditingController();
  final TextEditingController _refreshTokenTextController =
      TextEditingController();
  String _userInfo = '';

  // For a list of client IDs, go to https://demo.identityserver.io
  final String _clientId = AUTH0_CLIENT_ID;
  final String _redirectUrl = 'ai.autonet.afterme';
  final String _issuer = AUTH0_ISSUER;
  final String _discoveryUrl = 'ai.autonet.afterme';
  final List<String> _scopes = <String>[
    "https://www.googleapis.com/auth/youtube",
    "https://www.googleapis.com/auth/youtube.upload",
  ];

  final AuthorizationServiceConfiguration _serviceConfiguration =
      AuthorizationServiceConfiguration(
          'https://accounts.google.com/o/oauth2/auth',
          'https://oauth2.googleapis.com/token');

**Comment by BrightChad** [comment]
I started the project with 'flutter create' and then had to add the appAuthRedirectScheme line to the defaultConfig section. I received the error you mentioned which is what led me to add the appAuthRedirectScheme to my build.gradle. My error happened at build time so I don't think any of the code you posted in the second reply would matter yet.

Did you make sure the Gradle had a chance to run after you modified it? You can go into Android Studio and run the project from there to make sure Gradle actually saw and applied your changes.

**Comment by casetofon** [comment]
I guess you're talking about different things, because my error was shown on the website of the Authorization service (Google in this case). So the build went through fine.

**Comment by casetofon** [comment]
Not sure what I'm missing here.. I made the simplest version of this implementation and still get that error when trying to get the token. I added the three relevant files in this colab notebook: https://colab.research.google.com/drive/1bdXNovcFIR153GePDl-B_9qRBvKigYaw?usp=sharing
Any help would be valued.

**Comment by casetofon** [comment]
I found the issue: Instead of providing the redirect_uri set within the app, I needed to provide the one configured by the authorization service (Google). This is found in the client_secret.json file that you download when setting up the API client.

**Comment by casetofon** [comment]
The issue seems to be a bit more complicated. I made a StackOverflow post to hopefully get it sorted (for free):
https://stackoverflow.com/questions/63816482/how-to-correctly-set-redirect-uri-in-flutter-app

**Comment by edihasaj** [comment]
I've put a workaround here: #141
