### ISSUE TITLE
Does not redirect back into the app

### ISSUE THREAD

**Issue by casetofon** [MaikuB/flutter_appauth#141]
Instead of returning to the app once the permission is provided, it just shows the token in the browser and asks that you copy/paste it back into your app.
[](https://i.ibb.co/MRsW6Nc/backto.jpg)

Not sure what I'm missing, but I made the simplest version of this implementation and put it in this colab notebook: https://colab.research.google.com/drive/1bdXNovcFIR153GePDl-B_9qRBvKigYaw?usp=sharing

Any help would be valued.

**Comment by casetofon** [comment]
Found the problem.. had to put :// after the redirect_url

**Comment by edihasaj** [comment]
1) Make sure that your applicationId and appAuthRedirectScheme does not contain '_' or capitalized character.
2) Make sure that your application package name is the same in the identity server com.appname.xyz://login-callback , notice ://login-callback
3) In the appAuthRedirectScheme put only the applicationId without://login-callback.

Other part of the code stays the same.

Hope it helps someone
