### ISSUE TITLE
Error when client_id contains colon

### ISSUE THREAD

**Issue by LukasPoque** [MaikuB/flutter_appauth#142]
I want to authenticate my app client through the authorization code flow. 
Everything worked fine until I changed my client id to something like this 'abc:yxcv'. From now on the login method raised the following error:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: unauthorized_client, description: INVALID_CREDENTIALS: Invalid client credentials], null)`

I checked the id and the secret, but everything matches with the entry in the identity provider.

My code:

```
final AuthorizationTokenResponse result =
        await appAuth.authorizeAndExchangeCode(
      AuthorizationTokenRequest(
        "abc:44c32065-6e34-4ab0-b5ab-46e09b4a337a",
        'sso.example://redirect/',
        clientSecret: '450e0bc0-ba30-b57f-f90230744f27',
        discoveryUrl:
            'https://myserver/auth/realms/myrealm/.well-known/openid-configuration',
      ),
    );
```

Any idea how to solve this problem? Sure, I could change my client id, but I think this is not the final solution.

**Comment by MaikuB** [comment]
The issue with the colon will be to do with how the native SDKs will so not something I could resolve as this plugin is a wrapper for the native libraries. If it only works without a colon then you'll need to stick with it. I would suspect it has to do with our these details would be sent as part of a URL and using colons would cause issues. Perhaps it needs to be URL encoded for it to work

**Comment by MaikuB** [comment]
Closing as there isn't really I can do here
