### ISSUE TITLE
Plugin returns with PlatformException(authorize_and_exchange_code_failed, null, null) on Android 11

### ISSUE THREAD

**Issue by IRIG** [MaikuB/flutter_appauth#143]
The app is running well on all other Android versions with same parameters but it returns with 

~~~
PlatformException(authorize_and_exchange_code_failed, null, null)
~~~

on an Android device with Android 11.

**Comment by IRIG** [comment]
Solved by removing conflicting plugin registration

**Comment by MaikuB** [comment]
I believe this has to do with some changes in Android 11 and the AppAuth Android SDK docs were recently updated to include extra steps. Take a look at https://github.com/openid/AppAuth-Android#requirements and let me know how you go. I will also test and update the docs shortly

**Comment by MaikuB** [comment]
Tested it out and i worked for me so the readme has been updated. Have pushed a new release with the new info where I've also updated the SDK versions used as well but isn't necessary to get that version to solve the issue
