### ISSUE TITLE
 Loss of Focus on the browser used by flutter_appauth = no return of access_token

### ISSUE THREAD

**Issue by yvescurel** [MaikuB/flutter_appauth#147]
When another application required for authentication (example: sign & go https://play.google.com/store/apps/details?id=com.ilex.signandgo.android.rescue or https://apps.apple.com / en / app / sign-go-authenticator / id1030806448)
is called, it appears above the browser used by flutter_appauth. We therefore lose focus on the browser opened by flutter_appauth and there is no return with access_token even if this one is present ..... because in this case the browser used by appauth remains open if we comes back to it after its passage in background. Would it not be possible to use for the return of access_token a system of messages waiting for the calling application (StreamSubscription / Stream Flutter)?
Thank you.

**Comment by yvescurel** [comment]
Looking at the sources of FlutterAppAuthPlugin.java, wouldn't it be possible to send a message at the end of the tokenResponseToMap method with responseMap as a return
With a listening method based on Streams on the application side

**Comment by MaikuB** [comment]
I don't fully understand the problem here, can you record a video and upload it to a place like YouTube, Google drive or as a gif etc? Also please include details of the device, Android version and output of running `flutter doctor -v`

The way OAuth works is that the browser is meant to trigger a redirect by going to a url with the access token as part of the parameters. This would then in turn trigger code in AppAuth to extract the token etc. Sounds like this somehow not happening in your case and changing to a stream wouldn't solve it. Are you sure you've configured your app and redirect url properly?

**Comment by yvescurel** [comment]
yes you did not understand my question (I am French and my English is not
excellent) sign & go is an external software which is necessary for the
oauth identification process, there are many others on the stores ... and
before receiving access_token this applucation appears above the browser.
The chrome custom tab going to the backgroud can no longer correctly return
the token access. it cannot automatically close and return access_token to
the calling function! you understand ?



Le ven. 2 oct. 2020 à 23:27, Michael Bui <notifications@github.com> a
écrit :

**Comment by yvescurel** [comment]
of course everything is correctly configured it is a problem due to the design of flutter_appauth if an authentication software is launched above the browser (in android I suppose that you return the access_token via an activityresult ... what happens t 'it if the browser launches by an intention goes in background ...)

**Comment by yvescurel** [comment]
browser launches by an intent goes in background ...)

**Comment by yvescurel** [comment]
flutter_appauth must therefore offer two types of access_token return to the calling function, A) the existing return of acces_token with automatic closing of the browser (very good if the browser remains in the foreground) B) a return acces_token via a message sent to the calling function dart flutter on hold if the browser switches to background. (if another application necessary for the oauth process is started signed & go or other) (Way to achieve this: android broadcastreceiver / flutter streams or other ....) What do you think ? Thank you. Yves

**Comment by yvescurel** [comment]
precision for case B, it is the calling function which will have to close the browser after the return of access_token

**Comment by MaikuB** [comment]
>  it cannot automatically close and return access_token to
the calling function! you understand ?

I believe so but would you still like you to provide the details I asked for earlier so to repeat

> please include details of the device, Android version and output of running flutter doctor -v

Also, I don't see how what you described is to do with how AppAuth is designed. The Chrome custom tab is started from AppAuth and what happens from there is outside of AppAuth until the redirect occurs. If the browser isn't redirecting then I highly doubt changing how AppAuth works will fix this. 

Do you happen to have enabled the "Don't keep activities" setting on in developer mode?  That is something that was raised before in https://github.com/MaikuB/flutter_appauth/issues/102 and isn't something I can do anything about. Also should mention in case you've forgotten or didn't realise that this plugin is a wrapper for another SDK that is actually responsible for most of the logic. Issues you find may actually be to do with the SDK and not this plugin

**Comment by yvescurel** [comment]
yes I know it is a wrapper of another very well known sdk oauth but I thought it was possible to modify the return of access_token by sending a message in the end of the tokenResponseToMap method (from the line 429 FlutterAppAuthPlugin.java) with responseMap as a return

**Comment by MaikuB** [comment]
Doesn't look like you understood what I've been saying. My understanding of the problem you've described would mean that code isn't even being called to begin so making additional changes there wouldn't help. 

Another reminder to please provide the information I've requested

**Comment by yvescurel** [comment]
I think we misunderstood I am using the flutter_appauth package as standard and this modification does not affect the logic of the component or its wrapper.  the sign & go software dialogues only in the authentication phase, with the oauth server.  if flutter_appauth is installed on a smartphone A and sign & go is installed on a smartphone B I recover access_token (no loss of focus on the browser) if flutter_appauth and sign & go installed on the same smartphone loss of focus on the browser and no return  access_token

**Comment by MaikuB** [comment]
Regardless of what you're saying, please make sure to provide the information I have asked for. I won't be looking into this any further until you have done so.

You also haven't answered a question I had earlier, which was

> Do you happen to have enabled the "Don't keep activities" setting on in developer mode? 

Please make sure you do so

**Comment by yvescurel** [comment]
yes!  but any smartphone where sign & go or other strong authentication software is generally used in banks, do not accept debug and developer mode.

**Comment by MaikuB** [comment]
If by yes you mean have turned on "don't keep activities" on then that would be your problem and isn't an issue for this plugin as I mentioned earlier. In that case, whatever banks accept in terms of debug or developer mode is irrelevant because your issue is to do with you turning on a specific setting that applies to developer mode

Also, again I have to repeat

>  can you record a video and upload it to a place like YouTube, Google drive or as a gif etc? Also please include details of the device, Android version and output of running flutter doctor -v

If you cannot provide this info then I will close this issue

**Comment by yvescurel** [comment]
Ok 
I apologize for insisting heavily but I think there is a solution to this problem and it does not call into question the logic of the component https://appauth.io and its wrapper in flutter_appauth

**Comment by MaikuB** [comment]
Then I'm going to close this issue as you've already said so yourself that modifications wouldn't change the logic, in which case I don't see why it needs to be made or how it could solve your issue if the issue even exists given there's been a lack of evidence. I've used this to test with Google auth a while back and don't recall seeing the authenticator screen causing an issue. If you still believe there's an issue with the plugin, feel free to re-open the issue but make sure to include more details. Given the communication issues here, you might also want to consider reaching out to another developer who can speak French and fluent English to provide more details on your behalf
