### ISSUE TITLE
Problem in Flutter_AppAuth with authentication application above the browser used by Flutter_AppAuth

### ISSUE THREAD

**Issue by yvescurel** [MaikuB/flutter_appauth#148]
Hello, last weekend I misunderstood your requests and I did not have the test smartphones to correctly answer your questions. This is what you asked me about the use of an authentication application above the browser used by Flutter_AppAuth

Appli Flutter_AppAuth and AutenticatorSign&Go on same device: KO  
On Smartphone A First Step :  infinite Loader  :  KO
https://drive.google.com/file/d/1Dk9pOB_IA5_w0kdDctVHPVa2yx5Aw7xY/view?usp=sharing

On Smartphone A second step : if the browser is closed before, and reload Appli Flutter_AppAuth  OK
https://drive.google.com/file/d/1sTOEy_KLRZ7zf14r_w-P-hj-sL4aRS2F/view?usp=sharing

Appli Flutter_AppAuth on Smartphone B AND AutenticatorSign&Go  on Smartphone A: OK
https://drive.google.com/file/d/1ZOU19wIA2PX9-wvQvnLMebamTl49HrGL/view?usp=sharing

The target is for everything to be installed on a SINGLE Smartphone, therefore App with Flutter_AppAuth and Sign & Go on the same smartphone.
Problem: after Sign & Go authentication we lose focus on the Navigator and when we come back: infinite loader (even if the Aaouth process is complete)
On the smartphone where sign & go is installed, developer and debug mode is prohibited for security reasons ....

a solution ?
thank you very much

As you asked me, my Flutter Doctor :
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale fr-FR)
    • Flutter version 1.12.13+hotfix.8 at /Users/s0071604/flutter
    • Framework revision 0b8abb4724 (8 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/s0071604/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode_11.3.1.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is NO_PROXY=localhost, 127.0.0.1, nexus*, picnex000.dom101.mapres*, *.mapres, *.prdinf, *.prdres, itgce.caisse-epargne.fr, *sigce.caisse-epargne.fr, *.ibp, *.itce.fr
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[!] Connected device
    • Device QV7026H01E is offline.

**Comment by TheoSitnikow** [comment]
+1
Hi,
I had the same problem. 
If app(Webview) is in background during authentication, then Webview never receives redirect url.

**Comment by MaikuB** [comment]
> On the smartphone where sign & go is installed, developer and debug mode is prohibited for security reasons ....

@yvescurel Sounds like you still might not understand when I asked about developer mode and "Don't keep activities". You also seem to be using multiple phones. In the scenario when you have the Flutter app and authenticator sign and go on the same phone, you probably turn on the developer mode so that you could put your Flutter app on it right? If so, do you have the "Don't keep activities" setting turned on in developer mode? That is what I was asking about. I hope you understand what I mean

**Comment by MaikuB** [comment]
@yvescurel Also not that I'll be able to get the same device to try but still don't have details from you on what phone you are using (a search for "QV7026H01E" doesn't come up with anything) and the Android version it has installed. May be worth trying to test on a different, more recent phone in case you have some device-specific

**Comment by yvescurel** [comment]
On the smartphone where sign & go is installed, and app with Flutter_AppAuth (Case B) developer and debug mode is prohibited for security reasons .... Smartphone test: H8266 Android version 9
Thanks. Merci...

**Comment by MaikuB** [comment]
What is case B? The only letters you have used before is for different phones. Is this for when both are on the same device?

**Comment by yvescurel** [comment]
YES when both are on the same device

**Comment by yvescurel** [comment]
flutter_appauth must therefore offer two types of access_token return to the calling function,
1) an existing return from acces_token with automatic closing of the browser (Android: onActivityResult. Fine if the browser remains in the foreground)
2) an acces_token return via a message sent to the calling flutter function on hold if the browser goes to the background. (if another application necessary for the oauth process is started signed & go or other)
for this case, it is the calling function which will have to close the browser after the return of access_token.
I don't know if this sounds understandable to you with my bad English? If yes, what do you think?

**Comment by MaikuB** [comment]
No I don't understand and you seem to be repeating the same things where I already mentioned that 

- this plugin is a wrapper for the AppAuth Android SDK. Any issues you experience are most likely within that SDK and would need to be fixed from there
- if you're going to try to make changes to the plugin then I don't see the point when it's clear that at a certain point, some of the code for the plugin just won't be invoked because the browser never redirects back

Having said, as you're able to reproduce this issue and the code is open-source, you're welcome to go ahead and try to diagnose and fix the issue if you believe where the problem lies. This isn't something I'm going to be able to look at

**Comment by yvescurel** [comment]
Yes I understand your point of view. You can therefore close my request. I'll try to see what I can do about this issue or use another Open Client ID / OAuth package. Thank you.

**Comment by yvescurel** [comment]
I note that you clarify: "Since you are able to reproduce this issue and the code is open-source, you are prompted to try to diagnose and fix the issue if you know where the issue is."
I think this package is the best as it is based on known and proven Aouth Android / Ios components so I will try to fix this issue, if I find a solution I will keep you posted. Thank you.
