### ISSUE TITLE
iOS doesn't receive the result of login operation

### ISSUE THREAD

**Issue by martirius** [MaikuB/flutter_appauth#150]
Hi!

I'm facing a strange issue, I'm trying to login with Azure B2C; the browser is opened correctly and the login flow is prompted but when the user completes the login and been redirected to the application, no result is received.

I've attached a `.then()` and a `.catchError()` to the Future `authorizeAndExchangeCode` and it never completes.

On Android this doesn't happen and result is collected correctly.

Any advice?

Update: [10/10/2020]
I notice that sometimes i receive this message in logs when trying to login:
**Error retrieving thread information: (ipc/send) invalid destination port** 

Maybe it's related to this? https://github.com/flutter/flutter/issues/63025

**Comment by martirius** [comment]
Problem solved; it was a problem with redirectURL that must ends with a "/", otherwise it doesn't work for iOS

**Comment by rakib205** [comment]
Hi @martirius, I am having the same issue. Can you please explain the solution in a little brief?
Thanks

**Comment by martirius** [comment]
Hi @rakib205 
I suggest you to check for your redirectURL in AuthenticationExchangeCode and your URL scheme in Info.plist.
In my case the problem was that redirectURL was like this "myapp://auth" and not like this "myapp://auth/"
I noticed also that if you use the discoveryURL, iOS will give you problems

**Comment by rakib205** [comment]
Thanks

**Comment by mdrideout** [comment]
Commenting for SEO. I was also having a problem of app auth not working on iOS for Azure AD B2C. This was working fine on Android, but not on iOS simulator or physical device.

The normal browser redirect flow worked fine, but nothing happened after I was returned to the app. No errors, no result. 

I tried @martirius 's advice and added a trailing slash to the redirectUrl (I also learned that the serviceConfiguration method is necessary for iOS, discovery URL did not work).

**Comment by diegodiaz22** [comment]
> Commenting for SEO. I was also having a problem of app auth not working on iOS for Azure AD B2C. This was working fine on Android, but not on iOS simulator or physical device.
> 
> The normal browser redirect flow worked fine, but nothing happened after I was returned to the app. No errors, no result.
> 
> I tried @martirius 's advice and added a trailing slash to the redirectUrl (I also learned that the serviceConfiguration method is necessary for iOS, discovery URL did not work).

Were you able to get it to work?
