### ISSUE TITLE
Possibility to customize browser view (hide url bar, bottom navigation, etc)

### ISSUE THREAD

**Issue by tienthai0205** [MaikuB/flutter_appauth#151]
Hi, I'm looking in a way to customize the open browser when using the package to signup. Is it possible to hide the url bar and the bottom navigation when the browser is launched? Which part of the package code/ file that I could edit to achieve this?

**Comment by MaikuB** [comment]
The plugin doesn't support this, I don't think it's supported by the native AppAuth SDKs either. You'll need to do your own research into the SDKs to see if they do and if they happen to do so (which I doubt) then you'll need to implement this yourself (e.g. in your own fork)
