### ISSUE TITLE
Authorization only works with Basic authentication?

### ISSUE THREAD

**Issue by altherat** [MaikuB/flutter_appauth#152]
I've been trying to authenticate with Coinbase (https://developers.coinbase.com/docs/wallet/coinbase-connect/reference) and I kept receiving an `invalid_grant` error. After looking at the code of the plugin, I noticed it [only uses `ClientSecretBasic`](https://github.com/MaikuB/flutter_appauth/blob/defe695d5304d2f7214ff70f8562e21857cb82a4/flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java#L425) when authorizing, but Coinbase expects the `client_id` and `client_secret` to be in the POST body rather than in the headers with basic authentication. So, you should also add support for AppAuth's [`ClientSecretPost`](https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/ClientSecretPost.java).

**Comment by MaikuB** [comment]
This is an OSS project so if it's something you need then you should look at submitting a PR for it
