### ISSUE TITLE
Custom scheme vs. /nativeclient redirect URI?

### ISSUE THREAD

**Issue by magnuswikhog** [MaikuB/flutter_appauth#153]
I'm curious as to why this plugin works when using a redirect URI with a custom scheme, but using the one recommended in the [Microsoft Azure documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code) (`https://login.microsoftonline.com/common/oauth2/nativeclient`) does not seem to work?

**Comment by MaikuB** [comment]
This plugin is a wrapper for native SDKs that actually handles most of the work so it inherits the functionalities and restrictions that belong to them. I've not seen much around using AppAuth with http links besides [this](https://github.com/openid/AppAuth-Android#capturing-the-authorization-redirect) or having something setup to allow for testing in. Perhaps something you'd need to try out and/or look into it further. Their docs also seem inconsistent as if they recommending using MSAL but if you look at the MSAL docs then they use a custom scheme e.g. https://docs.microsoft.com/en-us/azure/active-directory/develop/redirect-uris-ios#msal-redirect-uri-format-requirements

**Comment by MaikuB** [comment]
Closing since this has been answered
