### ISSUE TITLE
Bug when using the nonce parameter in additionalParameters on ios

### ISSUE THREAD

**Issue by jhorlima** [MaikuB/flutter_appauth#157]
when i try to add the parameter "nonce" in the attribute "additionalParameters" i get the exception "PlatformException(authorize_and_exchange_code_failed, Failed to authorize: invalid_request: Failed to parse nonce as string, null, null)".

plugin version: 
```
flutter_appauth: ^0.9.2+6
```

my code: 
```dart
final nonce = getRandomString(15);
      final nonceHash = sha256.convert(nonce.codeUnits).toString();

      final result = await appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          AUTH0_CLIENT_ID,
    AUTH0_REDIRECT_URI,
          issuer: AUTH0_ISSUER,
          scopes: [
            'openid',
            'offline_access',
          ],
          additionalParameters: <String, String>{
            "nonce": nonceHash,
          },
          // promptValues: [
          //   'login',
          // ],
        ),
      );
```

error:
```
flutter: login error: PlatformException(authorize_and_exchange_code_failed, Failed to authorize: invalid_request: Failed to parse nonce as string, null, null) - stack: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      MethodChannelFlutterAppAuth.authorizeAndExchangeCode (package:flutter_appauth_platform_interface/src/method_channel_flutter_appauth.dart:32:57)
#4      FlutterAppAuth.authorizeAndExchangeCode (package:flutter_appauth/src/flutter_appauth.dart:7:44)
#5      _LoginPageState.loginAction (package:niduu_message/pages/login.dart:157:36)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart<…>
```

**Comment by MaikuB** [comment]
You'd need to debug further to look into this as it's not something I can help with. I tried it with the example app and passed "hi" as as the nonce parameter and didn't run into the same issue and decoding the id token showed that it had the same nonce value as well. Based on the error, it looks like there's an issue with the nonce value. Perhaps there are special characters in there and you need to URI encode your `nonceHash` variable for it's passed to the plugin

**Comment by jhorlima** [comment]
> You'd need to debug further to look into this as it's not something I can help with. I tried it with the example app and passed "hi" as as the nonce parameter and didn't run into the same issue and decoding the id token showed that it had the same nonce value as well. Based on the error, it looks like there's an issue with the nonce value. Perhaps there are special characters in there and you need to URI encode your `nonceHash` variable for it's passed to the plugin

I performed the same tests on android and it worked perfectly, I believe the problem only occurs on iOS. my token was generated with text only.

**Comment by MaikuB** [comment]
I'd need a complete minimal app that can reproduce the issue to be able to see what's going. This would preferably be a fork of the example app. Note that even then I might not be about to do anything because the plugin is a wrapper for the native iOS and Android SDKs that handle the bulk of the work
