### ISSUE TITLE
 SystemChrome.setSystemUIOverlayStyle not working on Android after successful login.

### ISSUE THREAD

**Issue by achalukkhal** [MaikuB/flutter_appauth#159]
```
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.0.1 20B29, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
```

Not able to control the Status Bar text color and background. Once the authentication is successful and navigation is complete. This issue is faced only on Android. 

```
 SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(
          statusBarColor: Colors.black,
          statusBarBrightness:
              Brightness.dark // dark == white status bar -- for IOS.
          ));
```
The above code is working on IOS but not on Android.

**Comment by MaikuB** [comment]
The above code is provided by the Flutter SDK not the plugin so if you have issues that code then you should ask on the Flutter repo or one of places listed [here](http://flutter.dev/community)
