### ISSUE TITLE
is there a way to change customTab Toolbar Color?

### ISSUE THREAD

**Issue by tcastro-hz** [MaikuB/flutter_appauth#163]
On Android, you could change the toolbar color on the CustomTabsIntent.Builder.

**Comment by MaikuB** [comment]
No as the plugin is a wrapper for the Android AppAuth SDK and that is what is responsible for making use of Chrome custom tabs. If you look at the Android code for this plugin [here](https://github.com/MaikuB/flutter_appauth/blob/master/flutter_appauth/android/src/main/java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin.java), you can see there's no code referencing Chrome custom tabs at all. 

If you happen to know of way, you could look at doing a fork and submitting a PR back
