### ISSUE TITLE
Unable to find a specification for `AppAuth (= 1.3.1)` depended upon by `flutter_appauth`

### ISSUE THREAD

**Issue by dophuhoang** [MaikuB/flutter_appauth#164]
I've got an error as the title above when build and run app on iOS.
And I found the configuration inside [../ios/flutter_appauth.podspec](https://github.com/MaikuB/flutter_appauth/blob/master/flutter_appauth/ios/flutter_appauth.podspec), the dependency 'AppAuth" is still using version '1.3.1'. So, how do I fix that error?

**Comment by MaikuB** [comment]
I'm guessing it didn't install the pod for whatever reason, it might tell already tell you what you need to run from within the ios directory of your app. If it does, then it generally says run `pod repo update`. Otherwise, running `pod install` should install it

**Comment by dophuhoang** [comment]
Because I added another `source` inside `ios/Podfile`, so I need to add `source 'https://github.com/CocoaPods/Specs.git'` and everything is fine
