### ISSUE TITLE
WebView doesn't open on iOS when using Multi Tenant

### ISSUE THREAD

**Issue by fersanraphael** [MaikuB/flutter_appauth#165]
Hello everyone.

I'm currently using AppAuth on both platforms, Android and iOS as Single Tenant, and it was working just fine on Azure AD.
Since I'm validating three different Azure ADs for my users, I changed from Single to Multi Tenant.

Everything is alright when running on Android platform after changing to Multi Tenant, but on iOS, the WebView isn't opening anymore.

I got the following exception:

_PlatformException(discovery_failed, Error retrieving discovery document: JSON error parsing document at 'https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration': Invalid URL: issuer, null, null)_

Note: Using "common" for Multi Tenant on discoveryUrl parameter generates the exception. Instead of "common", if I use a Single Tenant Id, everything works fine, but I need the common for Multi Tenant setup on Azure.

Could you guys take a look at the problem?

Thank you.

**Comment by MaikuB** [comment]
I don't think is something I can help with as the plugin is a wrapper for the native AppAuth SDKs that are actually the ones responsible for doing the authorisation requests. If you're seeing this fail and have configured everything correctly then, it'd be an issue with the SDK. In which case I'd suggest logging an issue with https://github.com/openid/AppAuth-iOS after you have tried reproducing this with the native SDK directly. I don't have apps configured in Azure and rely on existing tenants used for demos to test this.

Note: as you said mentioned "guys" earlier, wanted to point out that this project is maintained by myself in my spare time with the occasional contribution from the community. If you're able to help contribute then that would be very helpful

**Comment by MaikuB** [comment]
Closing as there's nothing I can do about this

**Comment by LeonardoMel0** [comment]
Hello @fersanraphael  did you solve the problem? I have the same issue on my code.

**Comment by AristideVB** [comment]
@LeonardoMel0  @fersanraphael  did you solve this issue ? 🙂
