### ISSUE TITLE
Use specific browser in IOS

### ISSUE THREAD

**Issue by GoncaloPT** [MaikuB/flutter_appauth#166]
Looking into the code seems that in IOS > 12 ASWebAuthenticationSession is used.
I Have a specific VPN solution - VMWARE Tunnel - that has application-specific VPN definitions. 
The VPN is not enabled for safari, only for some other browser. 
For that reason, I'm not able to see the login page.

Would it be possible to use a specific browser instead of this inner web view?

**Comment by GoncaloPT** [comment]
Just adding some more information... I've realized in the last couple of days that what is used is actually safari. I need one of 2 options: 
- use another browser
- use wkwebview

since both of them will have per-app VPN enabled.

Any thoughts on how to implement this?

**Comment by MaikuB** [comment]
Took a look at the AppAuth iOS docs again and noticed that they explicitly call out that they don't support WKWebView. Something to be careful of is if using a webview would lead your app to being rejected as well. Looks more likely that you need to come up with your own solution and not something I can help with so will be closing this.
