### ISSUE TITLE
Keep track of the authorization

### ISSUE THREAD

**Issue by AurelianTimu** [MaikuB/flutter_appauth#17]
Hello,

Is there any plan to provide access/an interface to AppAuth's `AuthState` (Android) and `OIDAuthState` (iOS)?

**Comment by MaikuB** [comment]
There are no plans to provide access to them at this stage and they are platform-specific, with some differences on each platform. They're currently not utilised by the plugin either. I think there's more value in tracking state at the Dart level to promote more code reuse across both Android and iOS. By that I mean you should be able to implement the equivalent of the auth state classes in Dart using the classes provided by the plugin. That way you could have something like the equivalent of AppAuth's `performActionWithFreshTokens` function to refresh your tokens if needed before executing Dart code e.g.  a web request with either the http package or dio. You'd have also have more finer control, such as choose what approach/package for serialising and deserialising, when to refresh the access token etc

**Comment by msh-nayan** [comment]
@MaikuB is there any update regarding this? any plan to integrate on/afterward flutter_appauth: ^4.2.1?

**Comment by MaikuB** [comment]
No plans to do this and reasons are given in me previous post as well
