### ISSUE TITLE
One Moment Please message after account selecting with Google

### ISSUE THREAD

**Issue by ergec** [MaikuB/flutter_appauth#172]
I'm tearing my non-existent hair out.

Azure AD config works without any problem but I couldn't make flutter_appauth work with Google.

No matter what I did the best I can get is this screen (displaying tiny "one moment please" and a loading animation) after account selection which eventually redirects to google.com

![image](https://user-images.githubusercontent.com/422056/104351950-bafd5600-550e-11eb-9b1b-b63928a3f007.png)

Settings I have is like this `appAuthRedirectScheme = 'com.googleusercontent.apps.93324xxxxxxxxx-xxxxxxxxxxxxxxxx'`

I get either scheme error or redirect_uri error on Google before account selection if I put applicationId as scheme and/or redirect_uri.

Followed all rules mentioned here too https://github.com/MaikuB/flutter_appauth/issues/141#issuecomment-756984837 but no luck.

Please help

**Comment by MaikuB** [comment]
I'm not familiar with all identity providers nor do I have access to some of them out there as I really only maintain the plugin. If you have issues with specific providers, you should refer to their docs to see if there's something specific to them that needs to be configured. I've seen others report issues with connecting to Google that they were able to resolve. Off memory, I think one of the issues was a mismatch in the application id.

I'd suggest you reach out to the wider [community](https://flutter.dev/community). Perhaps the example app for the official Google sign in plugin will help with your issue as well so you can check the configuration. Other thing you may need to consider is switching to use said plugin.

**Comment by ergec** [comment]
The app had an underscore in its name at some point and I renamed the whole project a while ago and removed the underscore. Seems AppAuth didn't like it. Created a new project with a proper name (no underscore) and same code did work.

Long story short, don't try to rename your project to remove underscore and/or capital letters.

**Comment by adrianvintu** [comment]
@ergec I have a project with underscores and auth works. **But**, the `appAuthRedirectScheme` must not contain underscores. See https://github.com/MaikuB/flutter_appauth/issues/284#issuecomment-1488540227
