### ISSUE TITLE
PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: Network error], null, null)

### ISSUE THREAD

**Issue by karezza** [MaikuB/flutter_appauth#176]
When attempting to use *discoveryUrl* I get an error related to a self-signed certificate.  So, I've used the following instead to get around that error.  Now I am getting the error in the subject header above.  Not really getting enough of an error message to debug, ideas?

Note:
- I can confirm the ADFS server work as I have a powershell script and webapi which both interact with it successfully.
- I installed the certs from the local lan CA into the mobile, but this has not resolved the ssl error (for some reason).

```Dart
final AuthorizationTokenResponse result = await appAuth.authorizeAndExchangeCode(
      AuthorizationTokenRequest(
        clientId,
        redirectUri,
        //discoveryUrl: discoveryUri.toString(),
        //issuer: discoveryUri.toString(),
        serviceConfiguration: AuthorizationServiceConfiguration(
            'https:/server.net/adfs/oauth2/authorize',
            'https://server.net/adfs/oauth2/token'
        ),
        scopes: ['openid','profile','email'],
        //allowInsecureConnections: true
      ),
    );
```

**Comment by karezza** [comment]
My issue may be a duplicate of https://github.com/MaikuB/flutter_appauth/issues/92, testing ...

**Comment by karezza** [comment]
Installing a CA certificate chain will not be recognized by a mobile app by default, it must be configured to be permitted by using `android:networkSecurityConfig`, instructions to do so can be found here:  https://developer.android.com/training/articles/security-config

After adding the following I was able to go back to using discoveryUri, and my code immediately started working:

```
<network-security-config>
    <base-config>
        <trust-anchors>
            <!-- Trust preinstalled CAs -->
            <certificates src="system" />
            <!-- Additionally trust user added CAs -->
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

**Comment by huynguyennovem** [comment]
@karezza  I tried to trust my own CA but not successful. When I tried with [native lib](https://github.com/openid/AppAuth-Android), it worked perfectly and does not require any CA. Do you know what's the problem here?
