### ISSUE TITLE
Authorize_and_exchange_code failed error invalid_client  

### ISSUE THREAD

**Issue by newxtint** [MaikuB/flutter_appauth#178]
Hello!
How can I fix invalid_client error? 
In postman it works well. In Flutter If I use a client secret or not I'm not able to connect (I get invalid_client error)
Here is the authorizeAndExchange code:
```csharp
     final AuthorizationTokenResponse result =
      await appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          AUTH_CLIENT_ID,
          AUTH_REDIRECT_URI,
          clientSecret: AUTH_CLIENT_SECRET,
          serviceConfiguration: AuthorizationServiceConfiguration('https://$AUTH_DOMAIN/connect/authorize', 'https://$AUTH_DOMAIN/connect/token'),
          scopes: ['openid'],
        ),
      );
```
Here is the error
`login error: PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: invalid_client, description: null], null, null)`

**Comment by MaikuB** [comment]
To be honest I have no idea and it's something you'd need to look into more as it depends on the IDP you use and its requirements. From memory, myself and I others have used this library to connect to applications registered in Auth0 with a client id and secret without issues so I doubt the use of those parameters is the issue. Perhaps you need to double check the values you are using? In any case this isn't something I can help with

**Comment by newxtint** [comment]
It was the client secret that had an Issue. Replacing it solved the problem.

**Comment by postpasspost** [comment]
I had the same issue. You should not have special characters in the client secret.
