### ISSUE TITLE
Can't use http forAndroid app crash when use flutter_appauth connect with http link 

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [MaikuB/flutter_appauth#179]
flutter_appauth: ^0.9.2+6
============================

<img width="730" alt="Screen Shot 2021-02-03 at 2 47 28 PM" src="https://user-images.githubusercontent.com/13627112/106714688-cb48b280-662e-11eb-8be6-46863bb9a354.png">

=============================

how can I fix this problem ? , when I run `authorizeAndExchangeCode` app crash with error 
I also add this `android:usesCleartextTraffic="true"` in android manifest

error : 
E/AndroidRuntime(14149): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(14149): Process: com.triviet.cuchi_tunnel_gis, PID: 14149
E/AndroidRuntime(14149): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(14149):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(14149):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(14149):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(14149):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(14149):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(14149):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(14149):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(14149):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(14149): Caused by: java.lang.IllegalArgumentException: only https connections are permitted
E/AndroidRuntime(14149):        at net.openid.appauth.Preconditions.checkArgument(Preconditions.java:116)
E/AndroidRuntime(14149):        at net.openid.appauth.connectivity.DefaultConnectionBuilder.openConnection(DefaultConnectionBuilder.java:51)
E/AndroidRuntime(14149):        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:327)
E/AndroidRuntime(14149):        at net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.doInBackground(AuthorizationServiceConfiguration.java:305)
E/AndroidRuntime(14149):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(14149):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(14149):        ... 4 more
I/Process (14149): Sending signal. PID: 14149 SIG: 9

**Comment by MaikuB** [comment]
Not something I can help with. Perhaps you should test out the fork referenced in this PR to see if it solves the issue

https://github.com/MaikuB/flutter_appauth/pull/149

**Comment by Abhishek01039** [comment]
Hello @nguyenleanhkhoa 
Please try to add this inside your `AndroidMenifest.xml` file
```
<queries>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="http" />
      </intent>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.APP_BROWSER" />
          <data android:scheme="http" />
      </intent>
  </queries>
```
