### ISSUE TITLE
How to login diffrent user if already signed in to IdentityServer 4

### ISSUE THREAD

**Issue by sokolej79** [MaikuB/flutter_appauth#18]
Use case:
User is successfully loged in with appAuth to identityserver 4.
If user open app again it will automaticlly login the same user with no login prompt on identity provider. 
So how can the user with two diffrent accounts  login to second account and optionally switch between accounts. 
Thanks in advance

**Comment by MaikuB** [comment]
This may be more of a IdentityServer question as opposed to functionality around this plugin. The ability to switch accounts depends on the IdentityServer supporting that functionality, which unless i'm mistaken means it needs to be able the _select_account_ prompt value as per the [OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html). From what I've gathered online, sounds like IdentityServer supports this yet. Having said, exposing the prompt option isn't available in the plugin at the moment. Log out functionality has been asked about before [here](https://github.com/MaikuB/flutter_appauth/issues/14) and is something you would need to handle yourself

**Comment by MaikuB** [comment]
On a related note, support for the `prompt` parameter has been added. I'd suggest you look up IdentityServer's documentation such as [this page](http://docs.identityserver.io/en/latest/endpoints/authorize.html). I don't think what you're after can be done though as you can that `select_account` isn't supported as per their documentation

**Comment by sokolej79** [comment]
Thank you very much for the quick reply.

**Comment by MaikuB** [comment]
no worries. closing this as there's nothing i see the plugin needs to address
