### ISSUE TITLE
Unable to get a valid "audience" into JWT using additionalParameters

### ISSUE THREAD

**Issue by mondospaceman** [MaikuB/flutter_appauth#180]
```
        response = await appAuth.authorizeAndExchangeCode(
          AuthorizationTokenRequest(
            AUTH0_CLIENT_ID,
            AUTH0_REDIRECT_URI,
            issuer: 'https://$AUTH0_DOMAIN',
            additionalParameters: {'audience': AUTH0_AUDIENCE},
            scopes: <String>['openid', 'profile', 'offline_access'],
          ),
```
With or without the 'audience' parameter, I get a short token on a Spring Boot server as the 'audience' instead of the value I specify above (e.g., 'https://resource.io').  I'm attempting to walk this down into the plugin code, but although I'm an experienced developer, I'm new to XCode.  So I can't tell whether this is a flutter_appauth issue or an AppAuth issue, or more likely, an invalid programmer at keyboard error.

**Comment by MaikuB** [comment]
I assume you checked the audience by decoding the token? That token is just what gets return by the auth server so there isn't an issue with plugin when it comes to this as all it does is return the result of what it received. You likely have some configuration issue elsewhere. I also recently used the plugin to specify an audience that matched an API registered with Auth0 and worked as expected as the same audience was found in `aud` claim of the JWT that came back from Auth0.

**Comment by mondospaceman** [comment]
Yes, I looked at the token decoded on the server.  The "aud" parameter was
some base64 thing I think, which itself decoded to a bit of nonsense, not
the audience.  I then attempted to debug the plugin to walk the aud
parameter value down into the Objective C, but I haven't figured out how to
do that yet.  I'll need to learn how to write and debug a Flutter plugin
someday.  What I did try was specifying a nonsense additional parameter
name "xyzzy" on the flutter side and noticed that nothing seemed to
complain.  I tried both "aud" and "audience" without success.

For now, I have turned off audience validation on the server.

Thank you,
Craig

**Comment by MaikuB** [comment]
Debugging the code won't reveal anything more as all you would get is the jwt as that's what the plugin receives from the identity provider. As you've turned off audience validation and this isn't controlled by the plugin then I'll close this. Perhaps you need to add your API to Auth0 and specify the same audience there if you haven't done so.

**Comment by mondospaceman** [comment]
I turned off validation because the server is not getting the audience.
Debugging would verify that the parameter is actually making its way to the
jwt.

I will pursue this as I have time and with additional information request
that the issue be reopened if necessary.

Good day.
