### ISSUE TITLE
Closing WebView triggers PlatformException

### ISSUE THREAD

**Issue by pawelknuthGelato** [MaikuB/flutter_appauth#181]
Platform: iOS

Steps to reproduce:
1. Trigger `authorizeAndExchangeCode` with proper token request
2. Close WebView

Neither `try..catch` nor `catchError` doesnt help.

<img width="710" alt="Screenshot 2021-02-09 at 14 04 28" src="https://user-images.githubusercontent.com/78592149/107367547-bad98180-6adf-11eb-82be-a45c19dd45dc.png">

**Comment by Totot0** [comment]
I am the same problem. What is the solution
