### ISSUE TITLE
Android build error: print('METHOD CALL')

### ISSUE THREAD

**Issue by mazzadomenico** [MaikuB/flutter_appauth#184]
In file
`java/io/crossingthestreams/flutterappauth/FlutterAppauthPlugin`
on line 151, there is a line code
`print('METHOD CALL')`
witch cause a build error.

flutter_appauth version: 0.9.2+6

Thanks in advice

**Comment by MaikuB** [comment]
No such code within the plugin exists and the repo makes use of CI where you can see the example that integrates with the plugin could successfully be built [here](https://github.com/MaikuB/flutter_appauth/runs/1476360713). You may have inadvertently modified the code yourself. If so, you'd need to fix this

**Comment by mazzadomenico** [comment]
Thanks @MaikuB, my team accidentally left this issue! I am so sorry for wasting you time!
