### ISSUE TITLE
Null-Safe version.

### ISSUE THREAD

**Issue by sollematthew** [MaikuB/flutter_appauth#185]
I am interested in using this library since the Auth0 documentation points to it as a great integration point for Flutter. Is there a null-safe version of this application in the works? I'm worried about the longevity if its not being updated to support the latest in Dart.

**Comment by MaikuB** [comment]
All of my OSS work is done on spare time and this isn't the only plugin I maintain so would take some time to get to. If you find this library useful then as this open-source, it'd be greatly appreciated if you or others can help with the null-safety migration

**Comment by MaikuB** [comment]
Closing as null safety versions have been released
