### ISSUE TITLE
(iOS) Dismissing auth dialog by outside tap hangs app

### ISSUE THREAD

**Issue by calmh** [MaikuB/flutter_appauth#186]
Hi! Thanks for this package! I noticed one somewhat blocking issue though, which I'm not sure how to work around. I bring up the auth dialog with something like this:

```
        final authResp = await appAuth.authorize(AuthorizationRequest(
          config.oidcClientId,
          redirectURL,
          discoveryUrl: config.oidcDiscoveryUrl,
          scopes: config.oidcScopes,
          preferEphemeralSession: true,
          additionalParameters: {
            'login_hint': username,
          },
        ));
```

If the user authenticates, or fails to authenticate, or hits "cancel" on the dialog, this works fine -- it either returns a response, or throws an appropriate exception. However, it's also possible to dismiss the dialog by tapping anywhere outside the white window:

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-02-15 at 20 54 26](https://user-images.githubusercontent.com/125426/107988476-66973b80-6fd0-11eb-8400-283c0a1d669b.png)

Doing so dismisses the dialog, but the code is still stuck in the `await` with nothing returned and nothing thrown. This doesn't seem like a `flutter_appauth` specific thing, it seems somewhat endemic to iPadOS: https://github.com/auth0/Auth0.swift/issues/444

That said, I'm not sure how to work around it from my side. I need the response so I must await. If it never returns, the code is blocked there forever. It won't work to just educate all users to keep their fingers in the designated area. :)

**Comment by calmh** [comment]
So, on the workaround side this can probably be handled by converting the async await to a stream and being prepared to cancel the stream and try again when the user hits "log in" again... The underlying problem has lots of people looking for answers (in all iOS environments) and no real solutions anywhere that I can see. :/

**Comment by MaikuB** [comment]
Nothing the plugin can do if it's not getting a response that the action was cancelled. Does look like it's specific to iPadOS as you mentioned as I couldn't reproduce this on iOS. Other thing to note is the plugin is a wrapper for Android and iOS SDKs that handle the majority of the work so if a fix could've been done, it would need to be done within those SDKs

**Comment by calmh** [comment]
This is no longer a problem in current iOS. Tapping outside the dialog does nothing, and the `Cancel` button works as expected. 👍

**Comment by MaikuB** [comment]
Glad to hear they've resolved it. Thanks for the update :)
