### ISSUE TITLE
Unable to select Sign up tab

### ISSUE THREAD

**Issue by aleksandra-rudan** [MaikuB/flutter_appauth#189]
Is there a way to automatically select Sing up tab in on universal login open?

**Comment by ninjaengineers** [comment]
@aleksandra-rudan try adding `prompt: ['signup']`

**Comment by aleksandra-rudan** [comment]
I have tried that, not working. Apparently there are job also in auth0 dashboard.

**Comment by niku** [comment]
I leave comment for who wants to open sign up screen using with universal login of auth0.
If you add `screen_hint=signup` to url, you can get sign up screen.
You just need to add ` 'screen_hint': 'signup'` to `additionalParameters` like following:

```dart
AuthorizationTokenRequest(
  auth0ClientId,
  auth0RedirectUri,
  issuer: auth0Issuer,
  scopes: <String>[
    'openid',
  ],
  additionalParameters: <String, String>{
    'screen_hint': 'signup',
  },
  promptValues: <String>['login'],
);
```

Further information, see https://auth0.com/docs/universal-login/new-experience#signup
> You can make users land directly on the Signup page instead of the Login page by specifying the screen_hint=signup parameter when redirecting to /authorize

Hope it helps.
