### ISSUE TITLE
Cann not use file_picker package

### ISSUE THREAD

**Issue by JuriSalesski** [MaikuB/flutter_appauth#190]
Because flutter_appauth_platform_interface 2.0.0 depends on plugin_platform_interface ^1.0.2 and no versions of flutter_appauth_platform_interface match >2.0.0 <3.0.0, flutter_appauth_platform_interface ^2.0.0 requires plugin_platform_interface ^1.0.2.
And because file_picker >=3.0.0-nullsafety.3 depends on plugin_platform_interface ^2.0.0, file_picker >=3.0.0-nullsafety.3 is incompatible with flutter_appauth_platform_interface ^2.0.0.
And because flutter_appauth 0.9.2+6 depends on flutter_appauth_platform_interface ^2.0.0 and no versions of flutter_appauth match >0.9.2+6 <0.10.0, file_picker >=3.0.0-nullsafety.3 is incompatible with flutter_appauth ^0.9.2+6.
So, because usg_online depends on both flutter_appauth ^0.9.2+6 and file_picker ^3.0.0, version solving failed.
pub get failed (1; So, because usg_online depends on both flutter_appauth ^0.9.2+6 and file_picker ^3.0.0, version solving failed.)

**Comment by wm-alex** [comment]
Got same issue but with Firebase_core, firebase_analytics and firebaes_crashlytics. Telling me flutter_appauth is not compatible.

**Comment by MaikuB** [comment]
These are dependency issues in your app that you'll need to resolve on your own. This is happening as not all of packages in the Flutter ecosystem have migrated to null safety or have only done this in a prerelease version. The options you'll have are

- change the version requirement that your application needs when it comes to other plugins. this potentially means you have "downgrade" the dependencies used by your application so it's using the version prior to being migrated to null safety
- read the documentation around package dependencies and make use of dependency overrides as described [here](https://dart.dev/tools/pub/dependencies#dependency-overrides). This will likely mean specifying a specific version of the `plugin_platform_interface` package. This is what the example app for the `firebase_messaging` plugin does as seen [here](https://github.com/FirebaseExtended/flutterfire/blob/6544551ff3ac5665086385aa24f1ff4020a8ca55/packages/firebase_messaging/firebase_messaging/example/pubspec.yaml#L32)
- use the null safety version of `flutter_appauth` that is available as a prerelease. This is still a prerelease as migration was done rather recently and keeping it as a prerelease would allow for more time for issues to be identified/raised as opposed to rushing it out as a "stable" release
