### ISSUE TITLE
Prompt values set to null connects user automatically on Android but not on iOS

### ISSUE THREAD

**Issue by postpasspost** [MaikuB/flutter_appauth#191]
I connect a first time with flutter_appauth to a new app screen, on Android and on iOS, then I logout back to a login screen.
When I set prompt values to null on Android, and I connect again, the user is connected automatically. But on iOS the user is taken to the login server page.

**Here is what happens in my test server:**
```
Logged in a first time, then disconnect:
Android: Connection Button -> browser only opens momentarily before redirecting back  -> App opens
Logged in a first time, then disconnect:
iOS: Connection Button -> Opens server login page on a browser -> User enters password -> App opens 
```

**Here is what happens in auth0 test server:**
 
_With the auth0 example it works the same on Android and iOS:_
```
Logged in a first time, then disconnect:
Android: Connection Button -> browser only opens momentarily before redirecting back -> App opens
Logged in a first time, then disconnect:
iOS: Connection Button -> browser only opens momentarily before redirecting back-> App opens 
```

I do not receive any errors. 
I am now trying to debug using logs in AppAuth-iOS from the console. Where should I look for printing debug information?

**Comment by postpasspost** [comment]
This error seems to be linked to the changes I've made in #182.
```Authorization Response: com.mycompany.myapp://login-callback/?code=CODE&state=STATE```
There is no forward slash "/" after login-callback/
```Authorization Response: com.mycompany.myapp://login-callback?code=CODE&state=STATE```
I will try to remove the forward slash and close this if it works.

**Comment by MaikuB** [comment]
The behaviour you described on Android occurs if a user had already signed in. Did you already sign in on Android? If so, the browser only opens momentarily before redirecting back. This is outside the control of the plugin. If you wanted the browser to prompt for the login every time then that's where you should've specified `login` as one of the prompt values. Leaving it as a null will leave it to the default behaviour.

**Comment by postpasspost** [comment]
I understand this is outside the control of the plugin. If this feature is needed then it's on the server side that there is a configuration problem. Thank you for your answer!
