### ISSUE TITLE
authorizeAndExchangeCode not returning after successful login on android

### ISSUE THREAD

**Issue by poqueque** [MaikuB/flutter_appauth#196]
I tried implementing the example codes on my servers, using this call:

```
    final AuthorizationTokenResponse data = await _appAuth
        .authorizeAndExchangeCode(
      AuthorizationTokenRequest(_clientId, _redirectUrl,
          discoveryUrl: _discoveryUrl, scopes: _scopes),
    ).catchError((error, stackTrace) {
      print("[AUTH] error: $error");
    });

```

The app opens webview for authentication and after successful authentication the authorizeAndExchangeCode is not returning anything and it's neither entering catchError.

This only happens in Android. On iOS it works just as expected.

I have already setup the 

`manifestPlaceholders = [appAuthRedirectScheme: '<myscheme>']`

just as in the example app.

If I use the example app with my server, the authorizeAndExchangeCode works fine, so I guess that either I'm missing some step or there is something in my project that is not compatible with this library.

Any hint to debug this issue?

**Comment by poqueque** [comment]
Finally found the issue and it was in my own code.

For some reason the onActivityResult on the Flutter MainActivity was previously modified and it was not calling super.onActivityResult().

Closing the issue.

**Comment by simphiwehlabisa** [comment]
@poqueque <code>manifestPlaceholders = [appAuthRedirectScheme: '<myscheme>']</code> Here do you mean on <code>myscheme</code> should i put my application package name or something else?
