### ISSUE TITLE
When I run this library on android versions lower than android version 11, it runs normally, but when I run this library on android 11 my app is completely shut down. How can I fix It?

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [MaikuB/flutter_appauth#199]

**Comment by MaikuB** [comment]
Have you done everything covered in [Android setup section](https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth#android-setup). There are steps that need to be done to ensure the app will work with the plugin that's specific to Android 11+

**Comment by MaikuB** [comment]
Closing as this has been answered and there's been no further responses
