### ISSUE TITLE
Example for Azure AD B2C

### ISSUE THREAD

**Issue by sowsan** [MaikuB/flutter_appauth#202]
Is there an example for setting up this plugin for Azure AD B2C ?

**Comment by MaikuB** [comment]
No but I've seen tutorials before. If I'm not mistaken, using Azure B2C requires paying for it. If so, I doubt anyone would upload a working example that points to their own tenant unless Microsoft did so themselves much like how Google has examples for firebase plugins that point to projects they've setup.

Anything that's specific to Azure B2C would be more on how to get that set up via Azure portal etc. Usage of the plugin is generic and should work providers that implement OAuth 2

**Comment by bryanCancelWT** [comment]
@sowsan for you or anyone else who finds this
look for my comments on this plugins issues

and for iOS try out the configs suggested by Microsoft here
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios
