### ISSUE TITLE
Two how-to questions - setting acr_values and changing response type from code

### ISSUE THREAD

**Issue by RCSandberg** [MaikuB/flutter_appauth#204]
Hi!

1) How can I pass acr_values to the authorize endpoint? Is it by setting the `Map<String, String>? additionalParameters` property in the `AuthorizationTokenRequest()`?

2) Is it possible to change the responseType? In AppAuth-IOS I guess it is changing `responseType:OIDResponseTypeCode` in `OIDAuthorizationRequest()` and in AppAuth-Android I guess it is changing `ResponseTypeValues.CODE` in the `AuthorizationRequest.Builder()`

BR,
Robert

**Comment by MaikuB** [comment]
1. Have never used it myself but yes, for _any_ parameters not explicitly exposed, you would use the `additionalParameters` property to specify them.
2. No, if you need to explicitly set these then you'd need to look at having your own fork. Though I'm not sure whay you'd be looking to do so either unless you're trying to not use the authorisation code flow. The plugin uses this and will set the response type accordingly

**Comment by RCSandberg** [comment]
Thanks for the very fast reply.

Regarding 1)... Excellent. Many thanks. Seemed to work :)

Regarding 2)... Okey, good to know. Yeah so the idea is that I am doing a multi tenant soluation where different login solutions can be used. Since OIDC supports other flows then the idea is that also our solution would match that. At least that is my understanding of my task :)

**Comment by MaikuB** [comment]
There are different flows but using the authorisation code flow, which is what the [AppAuth SDKs](https://appauth.io/) implement, is currently the best practice.

Will close this then since questions have been answered
