### ISSUE TITLE
Access token misses few portion of response from Key Cloak

### ISSUE THREAD

**Issue by ineelp** [MaikuB/flutter_appauth#21]
I have implemented app_auth and when i am receiving response from Key cloak. Access_token misses few portion which gives response without Payload data. When I modified in **flutter_appauth.dart** file with performing casting to access_token. I get actual token with Payload data. But it throws some exception **"Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method 'cast'."** Application got crashed. How should I fix this issue? 

Size of token is very long so it does not receive exact portion after **"colon(.)"**. But with casting, it receives and throws an exception. 

![Screenshot 2019-05-06 at 4 17 42 PM](https://user-images.githubusercontent.com/16939820/57209642-92744780-701c-11e9-812a-18da161f6310.png)

**Comment by MaikuB** [comment]
I'll preface this by saying I'm not familiar with Keycloak but are  the extra parameters are actually part of the access token itself? The exception you're seeing is self-explanatory. Have you checked the `authorizationAdditionParameters` and `tokenAdditionalParameters` dictionaries to see if  they have the extra payload you're after?

**Comment by ineelp** [comment]
Yeah, access_token has format something like "**Some_txt1.Some_txt2.Some_text3"**. I am not receiving "**.Some_text3**" portion. Few things of payload I received from `tokenAdditionalParameters` from response. But with incomplete token Back-end gives unexpected error. So, if i shall be able to get full response of token, it would be advantageous to solve many problems. Casting solves problem so I am wondering with there should be some mechanism to render response because size of token is very long. Probabbly which may not store actual response and jump to the `refresh_token.` 

Thank you for your time and considertation.

**Comment by MaikuB** [comment]
how is casting solving the problem for you when you said it throws an exception (note: you were also trying to cast a string to a map as well)?

**Comment by ineelp** [comment]
Yes, I tried to cast String to a map which throws an exception. So my point is, there should be mechanical to get such response. Otherwise, I had no clue how to handle rest of the response of token.

**Comment by MaikuB** [comment]
do you run into the same problem on both Android and iOS and have you validated that a portion of the access token is missing? e.g. you could take the access token being returned and paste it in jwt.io to see if it can be decoded successfully.

besides that, i can think of three reasons for the issue you're seeing, either

1. there's an issue with the Android and iOS AppAuth SDKs. that doesn't seem likely though but probably worth investigating but this isn't something I'd be able to do as I don't have access to Keycloak. It'd be something you'd need to debug
2. the access token has all three parts whilst it's still on the Android/iOS platform side but is being truncated when it's passed over the platform channel to the Flutter side
3. the access token loses the third part when going from a dynamic to a String

Scenarios 2 and 3 could be validated if you know what the expected length of the access token is and we could try to generate a random string of that length to avoid you sending an access token to me to check

**Comment by MaikuB** [comment]
something I noticed is you seem to be using visual studio code, i had noticed an issue before where if you're hovering over a variable to see it's value then it'll be truncated. i would suggest you try invoking the print method to display the access token to see if all three parts are there if you haven't already

**Comment by ineelp** [comment]
No, I did everything whatever you have just mentioned. I checked on jwt
that from there only I came to know that I’m missing few portion of token.
I tried to print response on console even but same issue. Response doesn’t
fetch entire token.

**Comment by MaikuB** [comment]
please check my other response as well

**Comment by ineelp** [comment]
I am sending you dummy token to have a look. Is there something to prevent token being truncated while passing though platform channel?
`token= eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwU180dHhEMTJpUVJIZlJaLURRLTFaRWlGS3pWYkttVVFFWjdqOUdPaTZVIn0.eyJqdGkiOiJkZGY1NWNmNi03M2ZiLTRkZmItYmRhZC1kMjVjM2U0NWNmYWQiLCJleHAiOjE1NTcyMzA1NDYsIm5iZiI6MCwiaWF0IjoxNTU3MTg3MzQ2LCJpc3MiOiJodHRwczovL2JvdW5jZXItc3RhZ2luZy5vdXRjb21lLWh1Yi5jb20vYXV0aC9yZWFsbXMvaW50ZXJubWF0Y2giLCJhdWQiOiJkdW1teSIsInN1YiI6Ijc3MGZhNDA2LWRlZmYtNGRiMi1hYzJlLTlhNTdkNjE0YTUwMCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImR1bW15IiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiOGFjZWNlYzQtYWY0Zi00Y2MyLTkxODEtY2I0MjY5MDhjNGE1IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6W10sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJieXJvbiJ9.lztbVGPs79V9bLT1fIaFRLvtMMyORG6xOH0XDdeTCiC_IAGtA_mE8qhMi7uQEjw_hh9VDCy3WX24vd5wbx9zq_fHIhztEINfZOVcWiYeKJIJyc0_6D_Ut_xjK_o4MbaObK1qE852eClwlAUCyaDUpiNBKuQkvX0hOE0prIeCyghfjdCso8nm5UiI699w_BjrbgttNW3s81zndo3FkBfIkov5BGq6CXuMNbSPm8qApXgJT9nIhyAN5mINRN3i92eo4bN0n34oYghVP9m7tYZKH1zl5zB6YmbVzAmo8GPi4t5l4BVGheKyzxQZiCrvChLaWnvwWHr5hFTvfVG6w`

**Comment by MaikuB** [comment]
is this problem happening on Android or iOS or both?

**Comment by MaikuB** [comment]
I've taken a look by returning that dummy token and it's fine. So the only potential issue would be to do with AppAuth but I'd be really surprised if that is the case. Could you please double check the access token you're getting back from the plugin? When you said it looks like the access token is missing the third part, how did you inspect the value? If you're printing out the access token e.g. via `debugPrint(...)` in Flutter and within VS Code, it will be truncated as per the screenshot below. When I copy and paste that value, it only has two dots has it **doesn't** print out the full access token. This is a correction on what I stated above where I seemed to recall it being truncated when copying the value whilst debugging).

<img width="1251" alt="Screen Shot 2019-05-07 at 10 18 55 pm" src="https://user-images.githubusercontent.com/25263378/57298696-2e35ae80-7116-11e9-92f7-42febf1c6559.png">

You can put a breakpoint your code to inspect the values and copy them via that interface

**Comment by ineelp** [comment]
This problem is happening with Android and IOS both. I check access token received from key cloak using “jwt.io” from there only I come to know which doesn’t have any pay load as it shows token signature is invalid. On the other hand, refresh token comes with pay load and it also has same structure of three dots but it is not that much long compared to access token. I’m just printing it using method print. Only this issue for access token because of its size. Is there any mechanism over platform channel which can be fixed? Or if you can figure it out what is the reason behind of receiving truncating token. 
Thank you for your time and consideration.

**Comment by MaikuB** [comment]
There's nothing else i can do to check here. I would suggest you debug the code on the Android and/or iOS side e.g. by stepping through the Java code

**Comment by MaikuB** [comment]
Also note my comment above that printing will not show the full string. If pay close attention to the screenshot I had sent then you would see that. As you mentioned earlier you printing it. I suspect the access token isn't missing anything and that you're thinking it's missing the third part because it's too long so not all sections are printed

**Comment by ineelp** [comment]
I checked length of actual access token and after printing. There is huge difference in size. So, it is confirmed that the issue is with only `print()` and `debugPrint()` only. I have also found someone also has reported this issue. 
[(https://github.com/flutter/flutter/issues/22665)]

Thank your for your time and consideration.
