### ISSUE TITLE
Does not seem to react to redirect from Azure AD. Google works.

### ISSUE THREAD

**Issue by jomag** [MaikuB/flutter_appauth#213]
I have an app that use `flutter_appauth` for authentication (openid).

I've set it up to accept either Google or Microsoft Azure AD.

Google works without any problems: you get the browser view, you allow the authentication and are immediately returned to the app as expected.

Microsoft on the other hand does not work very well: I get the browser view with the sign in screen, and then a question on the next screen: "Are you trying to sign in to The App Name?" with a "Cancel" and "Continue" button. If I press the "Continue" button typically nothing happens. Sometimes, when I press it rapidly I get a screen that says "Trying to sign you in" which the returns to the "Are you trying to sign in..." screen again.

No redirect back to the app seems to happen!

I'm quite sure I got client id and redirect uri right, as if I change them in any way I get other errors about invalid id's as expected.

Any ideas what I could be doing wrong? Or how I can debug this?

So far I've only tested with Android.

**Comment by mdrideout** [comment]
I'm not sure what you are doing wrong, but I am using both Azure AD B2C, as well as Microsoft Graph (Azure AD B2B) endpoints without issue. And I have the same microsoft flow for the B2B version where it confirms you are trying to use the flutter app.

I have found that I need to pass AuthorizationServiceConfiguration instead of discoveryUrl or issuer on the TokenRequest. Example param below.

```
          serviceConfiguration: AuthorizationServiceConfiguration(
            "https://login.microsoftonline.com/xxxxxxxxxx/oauth2/v2.0/authorize",
            "https://login.microsoftonline.com/xxxxxxxxxx/oauth2/v2.0/token",
          ),
```

**Comment by MaikuB** [comment]
@jomag You've likely missed something whilst configuring the app as I've been able to using this library with Azure AD without issues as well. The issue you have may also be to do with making use of the v1.0 endpoints instead v2.0. From memory, I had a similar issue where the discovery document URL in Azure Portal was for the v1.0 configuration

**Comment by MaikuB** [comment]
Closing this as there are no known issues in the plugin and I've been able to get this working myself. You've likely missed something when configuring your app e.g. updating the build.gradle file

**Comment by paulhwangfti** [comment]
@jomag running into a similar issue right now. did you ever end up resolving this and, if so, what solution worked?

**Comment by jomag** [comment]
Sorry, 3 years has passed, and I can't remember the details. We did make it work eventually though.

**Comment by ancarloman** [comment]
> @jomag running into a similar issue right now. did you ever end up resolving this and, if so, what solution worked?

Hi, I am experiencing a similar issue. Have you resolved yours, and if so, how did you make it work?

**Comment by paulhwangfti** [comment]
> > @jomag running into a similar issue right now. did you ever end up resolving this and, if so, what solution worked?
> 
> Hi, I am experiencing a similar issue. Have you resolved yours, and if so, how did you make it work?

It's been a while since I fixed this but from looking back it looks like I removed `api` from the list of scopes.
```
final TokenResponse? result = await appAuth.token(
          TokenRequest(
            clientId
            (Platform.isAndroid)
                ? ...
                : ...
            refreshToken: refreshToken,
            serviceConfiguration: AuthorizationServiceConfiguration(
              authorizationEndpoint:
                  "..."
              tokenEndpoint:
                  "...,
            ),
            scopes: [
              'openid',
              'profile',
              'offline_access',
              'user.read',
              // REMOVED => 'api'
            ],
            additionalParameters: {"prompt": 'select_account'},
          ),
        );
```

I also adjusted the `android/app/build.gradle` to have this as the `manifestPlaceholders`
```
manifestPlaceholders += [
                'appAuthRedirectScheme': 'msauth'
        ]
```
