### ISSUE TITLE
Use without OpenID

### ISSUE THREAD

**Issue by timmyd87** [MaikuB/flutter_appauth#217]
I'm very new to both oauth and flutter but the examples here are to do only with openid. Is there particular scopes or setup to not use opened and just a normal/basic oauth flow that I'm missing? Does anyone have examples? I've setup a basic oauth provider with my web app and has hoping to connect my flutter app. Any guidance would be awesome.

**Comment by MaikuB** [comment]
Even if you're not using OpenID to use things like the discovery document, oAuth 2.0 still defines certain standards that like how authorisation flows work. The example app already has a code snippet to get the authorisation code and how it could be exchanged. Given you said you're new to oAuth and Flutter, I would say the best thing you could do is spend more time learning about these areas, especially on oAuth as this a platform-agnostic area and is becoming more of an essential area to know about
