### ISSUE TITLE
iOS app build - "openURL" and "SFAuthenticationSession" deprecation warnings.

### ISSUE THREAD

**Issue by sreekatt** [MaikuB/flutter_appauth#218]
Flutter app, When doing an iOS build on Xcode, getting the following deprecated warnings...

flutter_appauth issues.
'openURL:' is deprecated: first deprecated in iOS 10.0
'SFAuthenticationSession' is deprecated: first deprecated in iOS 12.0

Please advise, if there is any solution to resolve these issues. Thank you.

**Comment by tokyokamera** [comment]
Same question . For now i cannot build my project in ios , just upgrade to flutter 2.5

**Comment by MaikuB** [comment]
There's no action to take here as these are deprecation _warnings_ (emphasis on warnings). Furthermore, I've tried running `flutter build ipa` on the example app and a new Flutter 2.5 that takes a dependency on this plugin and did't see these issues either.

If your app is not building then I believe there are other issues you'd need to look into as deprecation warnings don't prevent app to build. With Flutter 2.5 being released, there was a change to no longer support iOS 8.0 as a minimum target so I would suspect that is where the issue really is.

If you still believe there's an issue with the plugin itself then please provide a link to a repository that hosts a minimal app that can reproduce the problem
