### ISSUE TITLE
Platform Exception : Parameter response_type/prompt is directly supported via the authorization request builder, use the builder method instead

### ISSUE THREAD

**Issue by projexe** [MaikuB/flutter_appauth#22]
calling 

`var result = await appAuth.authorizeAndExchangeCode(
                    AuthorizationTokenRequest(
                      '<client_id>',
                      '<redirect_url>',
                      serviceConfiguration: AuthorizationServiceConfiguration('<authorization_endpoint>', '<token_endpoint>'),
                      scopes: ['openid','profile', 'email', 'offline_access', 'api']
                     additionalParameters : {"p" : "B2C_1A_signup_signin" ,  "prompt" : "login" , "response_type" : "id_token",}
                    ),
                  );`

Throws Platform Exception

Parameters "p" and "response_type" are required for AD B2C authorization. 

Bug either needs fixing or better explanation of how to add "p" (policies) and "response_type" parameters is required

**Comment by MaikuB** [comment]
I'd suggest you have a read of how my colleague did at in his blog post [here](https://nicksnettravels.builttoroam.com/post/2019/02/24/Flutter-at-MS-Ignite-%7C-The-Tour-Sydney.aspx). In the sample code there, he uses the discovery url and doesn't need to specify the additional parameters

**Comment by bryanCancelWT** [comment]
policy can be specified within the URL, search my other comment in this repo to find how
response type is now a param you can specify in the lib
