### ISSUE TITLE
android redirect uri in appAuthRedirectScheme not working with microsoft redirect uris

### ISSUE THREAD

**Issue by thomas-topway-it** [MaikuB/flutter_appauth#222]
microsoft authentication (https://login.microsoftonline.com/common/oauth2/v2.0/authorize)
does not accept lowercase uris, which are instead in form 
```
msauth://com.myappname.app/JDmnfursHEMDnfds...
```
and the plugin does not redirect correctly to the app after authentication.

is there a way to explicitly use and intent-filter in the manifest and if so, can you post an example of it ?
thanks

**Comment by Nealsoni00** [comment]
You have to add this in the `AndroidManifest`

`<activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
           <intent-filter>
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
               <data android:scheme="msauth" android:host="<app bundle indentifier>" android:path="/<URL ENCODED>" />
           </intent-filter>
       </activity>
`

**Comment by MaikuB** [comment]
You'd need to check your configuration and MS docs. I've used lowercase urls with Azure AD without issues. Furthermore, I haven't seen a strict requirement on the redirect URL unless you use MSAL, which isn't the case here. Even then the URL format is different than what you've posted as they concatenate msauth with the app id to form the scheme whereas your code snippet only has msauth as the scheme

**Comment by thomas-periculo** [comment]
@Nealsoni00  It works !! thanks a lot
@MaikuB  yeah, I think we are using a generic url format, however the issue has been solved only adding the code above on the manifest
(Thomas)

**Comment by bryanCancelWT** [comment]
@MaikuB could you please add this detail to your read me?
I was stuck on this for hours... until I found this... I think it would help a lot of people...
perhaps have a Azure AD basic section?

this example assumes...
bundle id: com.myappname.app
hash: DmnfursHEMDnfds...

[1] edit build.gradle as follows (android/app/build.gradle)
manifestPlaceholders += ['appAuthRedirectScheme': 'msauth://com.myappname.app']

[2] edit AndroidManifest as follows (android/app/src/main/AndroidManifest.xml)
     <activity android:name="net.openid.appauth.RedirectUriReceiverActivity">
         <intent-filter>
             <action android:name="android.intent.action.VIEW" />
             <category android:name="android.intent.category.DEFAULT" />
             <category android:name="android.intent.category.BROWSABLE" />
             
             
             <data android:scheme="msauth" android:host="com.myappname.app" android:path="/JDmnfursHEMDnfds..." />
         </intent-filter>
     </activity>
