### ISSUE TITLE
Docs: pass inside `additionalParameters`

### ISSUE THREAD

**Issue by Abhishek01039** [MaikuB/flutter_appauth#227]
Hello @MaikuB 
what type of data do we need to pass in the `additionalParameters` ?
can we pass the language code also?

**Comment by MaikuB** [comment]
I don't know what exactly you mean with your question on the type of data and language code. As the class that holds this property represents a request, the `additionalParameters` refers to additional parameters to pass along with the request. What this would be typically depends on the IdP you use or the scenarios you are dealing with. This requires understanding OAuth 2 as opposed to being a question specific to how the plugin works. As an example, if you need to get an access token that is used with an API, you might need to specify the audience as done in https://auth0.com/blog/build-flutter-wishlist-app-with-secure-api-part-3/
