### ISSUE TITLE
App crashes on Android X

### ISSUE THREAD

**Issue by HenrikThien** [MaikuB/flutter_appauth#23]
The app keeps crashing with Android X.
Failure delivering result ResultInfo, java.lang.NullPointerException: dataIntent must not be null.
It seems like this is an issue in the plugin code.

+

android.content.ActivityNotFoundException: Unable to find explicit activity class {net.openid.appauth.AuthorizationManagementActivity}; have you declared this activity in your AndroidManifest.xml?

I'm using the authorizeAndExchangeCode method to connect to the Spotify Web API

**Comment by MaikuB** [comment]
Would likely need a sample app to look into this. It sounds like the generated manifest file from the build doesn't have the activity listed. The example app in this repository does use AndroidX as well and doesn't experience the same crash you're seeing. When I execute `flutter run` on the example app and go to the /⁨build⁩/⁨app⁩/⁨intermediates⁩/merged_manifests⁩/⁨debug⁩, the manifest file there does have an entry for that activity.

I should also point out this plugin is just a wrapper around the Android and iOS AppAuth libraries so there may be certain things I can't fix. Spotify does seem to have their own SDKs though I don't think it's really required to handle the auth side of things given they appear to support the OAuth 2.0 code grant flow. You may need to consider writing your own wrapper around those but a quick search on pub would indicate there is one that is supposedly incomplete https://pub.dev/packages/spotify
