### ISSUE TITLE
Does flutter_appauth support flutter web?

### ISSUE THREAD

**Issue by duydat1998** [MaikuB/flutter_appauth#230]
I used flutter appauth for redirecting to Okta signing page.
But it shows me the error 

```
Error: MissingPluginException(No implementation found for method authorizeAndExchangeCode on channel crossingthestreams.io/flutter_appauth)
    at Object.throw_ [as throw] (http://localhost:49430/dart_sdk.js:5041:11)
    at MethodChannel._invokeMethod (http://localhost:49430/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:49430/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:49430/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49430/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:49430/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:49430/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:49430/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49430/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:49430/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:49430/dart_sdk.js:37532:13)
    at http://localhost:49430/dart_sdk.js:33303:9
```

So I wonder if i supports the flutter web or not?

Below is the result when I run flutter doctor -v

> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-arm, locale
>     en-VN)
>     • Flutter version 2.2.3 at /Users/datnd17.local/Development/flutter
>     • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/datnd17.local/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • ANDROID_HOME = /Users/datnd17.local/Library/Android/sdk
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
>     • All Android licenses accepted.
> 
> [!] Xcode - develop for iOS and macOS
>     ✗ Xcode installation is incomplete; a full installation is necessary for iOS
>       development.
>       Download at: https://developer.apple.com/xcode/download/
>       Or install Xcode via the App Store.
>       Once installed, run:
>         sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
>         sudo xcodebuild -runFirstLaunch
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
> 
> ! Doctor found issues in 1 category.

**Comment by MaikuB** [comment]
No it doesn't. If you visit https://pub.dev/packages/flutter_appauth then you should see that it indicates only Android and iOS are supported. There's an existing on web support too https://github.com/MaikuB/flutter_appauth/issues/70

**Comment by duydat1998** [comment]
oh thank you, hope you soon implement for web too.
Have a nice day!
