### ISSUE TITLE
Android is not honouring the preferEphemeralSession=true setting in authorizeAndExchangeCode() call

### ISSUE THREAD

**Issue by KonAtPropertyMe** [MaikuB/flutter_appauth#232]
I'm using the `preferEphemeralSession: true` which works correctly in iOS. 

However, it does not appear to work for Andriod. When the `authorizeAndExchangeCode()` call is made the browser briefly pops up and gets the token from the session cookie and closes, returning to the app, with the previous logged in user's token. 

On iOS, the session is correctly discarded and a new call to `authorizeAndExchangeCode()` opens the identity screen. 

Is there some special android config needed to support this? (apart from that which is documented in the pub doc).

**Comment by MaikuB** [comment]
It's not working on Android as it's specific to iOS and this was mentioned in the [API docs](https://pub.dev/documentation/flutter_appauth_platform_interface/latest/flutter_appauth_platform_interface/AuthorizationTokenRequest/preferEphemeralSession.html)
