### ISSUE TITLE
Add state parameter manually in authorize request

### ISSUE THREAD

**Issue by lsuhov** [MaikuB/flutter_appauth#233]
Hello, 
We are having a scenario where we wanted to temporarily assign a fixed state as parameter. 
While trying to add the state field in additionalParameters, in Android we got the following Platform exception:
_"Parameter state is directly supported via the authorization request builder, use the builder method instead"_

We then concluded that this functionality is feasible at native library level, but not on Flutter library level.

Is it possible to expose this in Flutter library?
Thank you

**Comment by MaikuB** [comment]
Please submit a PR if you are in need of this. Another member of the community attempted to do so before in https://github.com/MaikuB/flutter_appauth/pull/96 but I closed the PR as there were no updates to fix the failing tests

**Comment by sonufrienko** [comment]
I have the same issue

**Comment by MaikuB** [comment]
Closing this as anyone interested in this can look to submit a PR and there's been further updates to one that had been opened before
