### ISSUE TITLE
PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] c.c.a.b.c.c

### ISSUE THREAD

**Issue by bhanuka96** [MaikuB/flutter_appauth#236]
When the button click I called your plugin. Why is this happening? This is happening to random users

**Error Code** 

`PlatformException(Exception encountered, read, java.lang.NullPointerException: Attempt to invoke interface method 'byte[] c.c.a.b.c.c....`

**Button Click code**

```
  @override
  Future<AuthorizationTokenResponse?> login(TenantCatLogModel? tenantCatLogModel) async {
    FlutterAppAuth appAuth = FlutterAppAuth();
    final String _issuer = '${tenantCatLogModel?.authorityUrl}';
    final AuthorizationServiceConfiguration _serviceConfiguration = AuthorizationServiceConfiguration(
        '${tenantCatLogModel?.authorityUrl}/connect/authorize', '${tenantCatLogModel?.authorityUrl}/connect/token');

    return appAuth
        .authorizeAndExchangeCode(AuthorizationTokenRequest(
      _clientId, _redirectUrl,
      issuer: _issuer,
      scopes: _scopes,
      promptValues: ['login'],
      serviceConfiguration: _serviceConfiguration,
      preferEphemeralSession: Platform.isIOS
    )).catchError((e) async {
      return null;
    }).then((value) async {
      log('access token -> ${value?.accessToken}');
      if (value?.refreshToken != null) {
        await SecureStore().setRToken(value?.refreshToken);
        return value;
      } else {
        return null;
      }
    });
  }
```

[device info](https://user-images.githubusercontent.com/34953062/132286458-2ba548b7-bedb-4fb4-bbfb-4711d8af3094.jpeg)

![screen record](https://user-images.githubusercontent.com/34953062/132286462-7f6c60b9-3da6-42b1-81c0-7e5092ae97b7.mp4)

**Comment by MaikuB** [comment]
Not something I can look into without a minimal app that can reproduce the issue so it would need to be something you'd have to debug to find out. Furthermore, that kind of error isn't something from this plugin. This looks more like something that would occur from the secure storage plugin you're using
