### ISSUE TITLE
null Access Token returned by Azure after authentication

### ISSUE THREAD

**Issue by JKornberg** [MaikuB/flutter_appauth#237]
Hello! Very new to this whole authorization thing. I'm using Azure B2C for authentication. My AuthorizationTokenResponse has "null" as the access token, and a quite lengthy response as the "idToken". The redirect is working properly. Any advice would be greatly appreciated. My code is:
```
result = await _appauth.authorizeAndExchangeCode(
        AuthorizationTokenRequest('fb105d3b-53c3-47fa-8e95-e7ec1bced50f',
            'com.example.azureplatform://oauthredirect',
            discoveryUrl:
                'https://xxxxxxxxx/xxxxx.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_azureflutter_signin_signup',
            scopes: ['openid', 'profile', 'email', 'offline_access']),
      );
```

Additional question, Azure says it returns "Claims" after sign up (like the user's name and other sign up fields), where would this be present in the response?

Thanks!!!

Edit: I'm starting to think all the data I need is returnd in the "ID token" given this article: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by JKornberg** [comment]
Follow up, I'm having a hard time understanding the difference between an Access Token and an IDToken. Do I need to receive both?

**Comment by shubhamkatore** [comment]
Seems like above request is incomplete you can try below request

`await _appAuth.authorizeAndExchangeCode(
              AuthorizationTokenRequest(
                clientId,
                redirectUrl,
                serviceConfiguration: AuthorizationServiceConfiguration(
                authUrl,
                tokenUrl,
              ),
                scopes: scopes,
                preferEphemeralSession: false,
              ),
            );`

Access Token mainly used for Authentication + Authorization purpose while IDToken is used for Authentication purpose.

If you want to communicate with backend most of the times you need Access token
