### ISSUE TITLE
CORS in WebView on /authorize redirect

### ISSUE THREAD

**Issue by simon-hypecast** [MaikuB/flutter_appauth#239]
I am trying to connect to our own ID server using flutter_appauth. The login page rendered at id.hypecast.dev in the web view is an Angular app and the /authorize redirect is initiated by the server API (api.id.hypecast.dev). But as you can see in the screenshot, the redirect of /authorize is blocked because of CORS. 

customURI scheme is in build.gradle and Info.plist is one.hypecast.app and the redirectURL is in the flutter-config and on server-side one.hypecast.app://login-callback.

Is there any way to configure CORS in flutter or native in iOS and android to allow the WebView to redirect?

<img width="1307" alt="Bildschirmfoto 2021-09-18 um 13 22 21" src="https://user-images.githubusercontent.com/78438528/133887371-c2f9c3b4-984a-46bb-b825-c216419aab6a.png">

**Comment by MaikuB** [comment]
As far as I know, no there isn't. Furthermore, my understanding is that anything related to CORS is around server configuration server where servers need to allow requests from trusted domains. As the issue mentions a non CORS _scheme_, perhaps the solution to your problem is configure a redirect URL with a https scheme

**Comment by simon-hypecast** [comment]
Thanks for the hint. With https in the redirectURL the CORS error disappears, but then there are problems that the app link is not recognized and the app does not open after the redirect.
<img width="1090" alt="Bildschirmfoto 2021-09-20 um 12 29 44" src="https://user-images.githubusercontent.com/78438528/134000728-284cfbd7-2533-4605-bc22-e834cc977ccf.png">


Do you have any idea how to define a CustomURI scheme with https which links to the app?

But anyway, I also think that the main cause is in the server configuration and the https in the CustomURI is more or less a workaround.

**Comment by MaikuB** [comment]
I've not used https schemes. i'd suggest checking the docs for the native sdks and platforms but from what you said, it sounds like you may have only changed the redirect URL in the Dart without making the appropriate changes on the native platform side to match

**Comment by ArefMozafari** [comment]
Hello there 
Did you find a solution to this?
Chrome Custom Tab says "Links Blocked" (When callback runs) when the user needs to leave the app in order to use a second app (OAuth provider app) to complete the authentication flow.
