### ISSUE TITLE
redirect_uri return  net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by hexes128** [MaikuB/flutter_appauth#245]
everything for IDS4 login works fint,but when it redirects me back,  the redirect page shows 'net::ERR_CONNECTION_REFUSED'
and when I close webview , I still cant get all the token
![image](https://user-images.githubusercontent.com/50615028/135738170-3f028389-7129-42a4-a6fe-65a62089c834.png)
![image](https://user-images.githubusercontent.com/50615028/135738202-1cab2cfd-36f8-488a-9985-1b60c3d8b773.png)
![image](https://user-images.githubusercontent.com/50615028/135738237-7a45075f-1baf-40c4-a8c2-e6e4c604743f.png)
![image](https://user-images.githubusercontent.com/50615028/135738249-99144f0a-5839-4710-ac3f-93dc261089e5.png)
this project I use your demo code ,only change client parmeters to mine,and all value match to my database
Im not sure whether red error on my manifest cause this problem, they appears then your project is open,
and even when new project is created

**Comment by stefannovak** [comment]
> everything for IDS4 login works fint,but when it redirects me back, the redirect page shows 'net::ERR_CONNECTION_REFUSED' and when I close webview , I still cant get all the token ![image](https://user-images.githubusercontent.com/50615028/135738170-3f028389-7129-42a4-a6fe-65a62089c834.png) ![image](https://user-images.githubusercontent.com/50615028/135738202-1cab2cfd-36f8-488a-9985-1b60c3d8b773.png) ![image](https://user-images.githubusercontent.com/50615028/135738237-7a45075f-1baf-40c4-a8c2-e6e4c604743f.png) ![image](https://user-images.githubusercontent.com/50615028/135738249-99144f0a-5839-4710-ac3f-93dc261089e5.png) this project I use your demo code ,only change client parmeters to mine,and all value match to my database Im not sure whether red error on my manifest cause this problem, they appears then your project is open, and even when new project is created

If you know the URL that *should* be called, then get the URL the webview is going to and compare the two URLs. That should give you some clues

**Comment by stefannovak** [comment]
If you know the URL that should be called, then get the URL the webview is going to and compare the two URLs. That should give you some clues

**Comment by MaikuB** [comment]
This is something you'd need to check on your end as you're making use of localhost when it might not be accessible via your emulator/device
