### ISSUE TITLE
Getting discovery_failed?

### ISSUE THREAD

**Issue by itaishalom** [MaikuB/flutter_appauth#249]
Hi, any idea what this means?
It happens on android 10, but not always.
PlatformException(discovery_failed, Error retrieving discovery document: [error: null, description: Network error], null, null).

The code:

` Future<TokenResponse> reLoginAction(String storedRefreshToken) async {

    return await synchronized(() async {

      try {

        final TokenResponse? result = await _appAuth.token(TokenRequest(

          this.clientId,

          REDIRECT_URI,

          issuer:

              'https://${this.domain}/oauth2/***********', //real string

          discoveryUrl: OKTA_DISCOVERY_URL,

          refreshToken: storedRefreshToken,
        ));

        return result!;

      } on Exception catch (e, s) {

        logger.e('error on login', e, s);

      }

      throw Exception("ReSign in issue");

    });

  }`

**Comment by MaikuB** [comment]
Have you checked to make sure it's not a connection issue on your end? I've tried this with Okta in the past for testing purposes and didn't run into issues. I recall hearing off others using this plugin with Okta too and didn't see reports of issues like this

**Comment by plantshopping** [comment]
I'm also getting the same error. The full error is

`PlatformException (PlatformException(discovery_failed, Error retrieving discovery document: [error: null, description: Network error], null, null))`

**Comment by MaikuB** [comment]
This error is outside of the plugin's control. It would be when the native SDKs detect a network error as it fails to hit the discovery endpoint due to either a connection issue or wrong information being provided.  You could try to explicitly specify the endpoints but if it's connection issue then chances are it won't help

**Comment by FranzM91** [comment]
I had the same error but I managed to solve it by manually adding the document discovery below the code: 
final TokenResponse? result = await _appAuth.token(
        TokenRequest(
          _clientId, 
          _redirectUrl,
          refreshToken: _refreshToken, 
          // issuer:       _issuer, 
          scopes:       _scopes,
          serviceConfiguration: const AuthorizationServiceConfiguration(
            authorizationEndpoint: 'https://{this.domain}/connect/authorize',
            tokenEndpoint: 'https://{this.domain}/connect/token',
            endSessionEndpoint: 'https://{this.domain}/connect/endsession',
          )
        ));
