### ISSUE TITLE
PlatformException(null_intent, Failed to authorize: Null intent received, null, null)

### ISSUE THREAD

**Issue by endritgojanikodelabs** [MaikuB/flutter_appauth#252]
`  final AuthorizationTokenResponse result =
          await _appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          _clientId,
          _redirectUrl,
          issuer: _discoveryUrl,
          additionalParameters: {'domain': domain},
        ),
      );`
After I login I'm gooing back to the app by redirect url and getting this error: PlatformException(null_intent, Failed to authorize: Null intent received, null, null)

**Comment by MaikuB** [comment]
Please provide steps to reproduce this, preferably via fork of the repo and using the example app. A search across the repo with this error message would indicate that your issue is the first time something like this has been reported so chances are you've misconfigured something. Haven't tried it but what comes to mind is perhaps you have turned on the "Don't keep activities" setting the developer mode options?

**Comment by postflow** [comment]
I think what you applicationID in Android contain symbol "_" or capital letters.

**Comment by konnic** [comment]
I had the same error. I resolved it by enabling flutter deep linking (see: https://docs.flutter.dev/development/ui/navigation/deep-linking#enable-deep-linking-on-android), because my redirect URI is not the android package, but a custom (shorter) scheme.

**Comment by MartinAKovachev** [comment]
@MaikuB We continue receiving a huge amount of `PlatformException(null_intent, Failed to authorize: Null intent received, null, null)`. Can't find the exact reason, but from the documentation it states:

https://javadoc.io/doc/net.openid/appauth/0.7.0/net/openid/appauth/AuthorizationService.html#getAuthorizationRequestIntent-net.openid.appauth.AuthorizationRequest-
> If the user presses the back button or closes the browser tab, the launched activity will call Activity#setResult with Activity#RESULT_CANCELED without a data Intent.

Could that be the reason? We can't reproduce the exception locally, only seeing it in analytics.

**Comment by MartinAKovachev** [comment]
> @MaikuB We continue receiving a huge amount of `PlatformException(null_intent, Failed to authorize: Null intent received, null, null)` (flutter_appauth: ^6.0.0). Can't find the exact reason, but from the documentation it states:
> 
> > If the user presses the back button or closes the browser tab, the launched activity will call Activity#setResult with Activity#RESULT_CANCELED without a data Intent.
> 
> https://javadoc.io/doc/net.openid/appauth/0.7.0/net/openid/appauth/AuthorizationService.html#getAuthorizationRequestIntent-net.openid.appauth.AuthorizationRequest-
> 
> And we saw in the code, if the intent is null you return that exception.
> 
> ![onActivityResult](https://user-images.githubusercontent.com/90396288/253194365-7b91d1d6-d126-4232-b2ee-ac1e3bd0dfb9.png)
> 
> Could that be the reason? We can't reproduce the exception locally, only seeing it in analytics.

I do not see handler for `ActivityNotFoundException`, could that be the issue here?

**Comment by MartinAKovachev** [comment]
> I had just saw this error as well. I resolved it by enabling flutter deep linking (see: https://docs.flutter.dev/development/ui/navigation/deep-linking#enable-deep-linking-on-android), because my redirect URI is not the android package, but a custom (shorter) scheme.

We have it turned on but the issue is still showing.
