### ISSUE TITLE
Documentation enhancement: .plist file add CFBundleURLSchemes

### ISSUE THREAD

**Issue by victorblaess** [MaikuB/flutter_appauth#254]
The format in the info.plist file like mentioned in the documentation and below made problems when uploading to iOS TestFlight (AppStore in General not tested yet). The problem is caused by the '[' which starts the String-Array of url-schemes as its not an alphanumeric character.

```xml
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string><your_custom_scheme></string>
        </array>
    </dict>
</array>
```

The solution is to delete the array-tags around the 
```<string><your_custom_scheme></string>```

So it looks like this:
```xml
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
            <string><your_custom_scheme></string>
    </dict>
</array>
```
![WhatsApp Image 2021-11-01 at 13 34 26](https://user-images.githubusercontent.com/60963842/140079179-bd86ad69-46a3-4f9b-897b-e34f2fd3ffec.png)

Investigated with @patimue

**Comment by MaikuB** [comment]
> The problem is caused by the '[' which starts the String-Array of url-schemes as its not an alphanumeric character.

Where did you pull the '[' from as it's not part of the actual docs itself

I have to wonder if something else is going on with what your app had as this is the first time anyone has reported this issue and it isn't configuration that is specific to AppAuth. For example, configuring the Facebook SDK requires similar setup and has `<array>` (https://developers.facebook.com/docs/ios/getting-started/#step-2---configure-your-project) and so does MSAL (https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios#for-ios-only-configure-url-schemes)

**Comment by victorblaess** [comment]
> > The problem is caused by the '[' which starts the String-Array of url-schemes as its not an alphanumeric character.
> 
> Where did you pull the '[' from as it's not part of the actual docs itself.
> 
> I have to wonder if something else is going on with what your app had as this is the first time anyone has reported this issue and it isn't configuration that is specific to AppAuth. For example, configuring the Facebook SDK requires similar setup and has `<array>` (https://developers.facebook.com/docs/ios/getting-started/#step-2---configure-your-project) and so does MSAL (https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios#for-ios-only-configure-url-schemes).
> 
> Did you by chance put the `[` character to signify and array in the `Info.plist` file by accident instead of an `<array>` XML element?

Its also the first time this appeared when using flutter_appauth. I have some more apps that worked fine. I did not add a '[' to my plist file. It was really solved by deleting the array tag. The '[' only appeared in the error message of xcode when uploading to TestFlight. I just connected the dots and deleted the <array> tag to get rid of the '[' which caused the problem. I have pasted the error message above.

**Comment by MaikuB** [comment]
On closer inspection of what you've sent, the error would appear to be legitimate.  The value in the screenshot would indicate in your app, the entire redirect URL was originally set as the scheme and this does have invalid characters like `:` and `/`. The scheme is meant to be the `f...e` (i.e. the part before `://com...`) as shown in your screenshot. Perhaps someone has fixed that and miscommunicated what the issue really was?

**Comment by victorblaess** [comment]
> On closer inspection of what you've sent, the error would appear to be legitimate. The value in the screenshot would indicate in your app, the entire redirect URL was originally set as the scheme and this does have invalid characters like `:` and `/`. The scheme is meant to be the `f...e` (i.e. the part before `://com...`) as shown in your screenshot. In other words, the scheme is the first part of the redirect URL. Perhaps someone has fixed that in your app and miscommunicated what the issue really was?
> 
> Note: putting the redirect URL as the scheme should've led to an issue with getting sign in functionality working as well so I'd suggest checking more thoroughly within your application's code

I have implemented discord oauth2 and they dont allow a scheme starting with com.xxx.xxx they want a xxxx://com.xxx.xxx scheme. Otherwise you cant save the redirect uri on the discord application. Authentication works fine for me. I just needed to delete the `<array>`-tag. Its not a bug. I just thought I will tell you this due to documentation reasons :)

**Comment by MaikuB** [comment]
I understand what you're saying however it doesn't look like you understand what I have written. Please take a closer look at what I've written and cross reference that with the screenshot in your original message. I didn't say the scheme in your case is `com.xxx.xxx`.  What I said was your error would have happened as your application configured specified the redirect URL as the scheme itself. `f...e://com...mobile.companion/oauth` looks more a redirect URL (note the `...` represents the parts your screenshot had blocked out). Using the example app as a reference, the redirect URL is defined as 

https://github.com/MaikuB/flutter_appauth/blob/2307f7cfadc3ce1d852c5d7140d98ed62302b086/flutter_appauth/example/lib/main.dart#L34

The scheme in this case is `io.identityserver.demo` i.e. the part before the `:/`. See https://github.com/MaikuB/flutter_appauth/blob/2307f7cfadc3ce1d852c5d7140d98ed62302b086/flutter_appauth/example/ios/Runner/Info.plist#L12 and notice they are not the exact same value (ignore `<string>` and `</string>`)

There is no fixed requirement that the scheme is the same as your application's ID (i.e. `com.xxxx.xxxx` as you put it), it is a convention. In your case, the scheme you should be setting in the `Info.plist` is `f...e`. You can't even have `xxxx://com.xxx.xxx` as a scheme so it looks like you are confusing redirect URLs with schemes. If you want to use  ``xxxx://com.xxx.xxx`  as the redirect URL, then the scheme would be `xxxx`. To reiterate, the scheme is only the first part of the redirect URL. Hope this makes it clearer what I meant.

Although I haven't used Discord OAuth before, I do have a Discord account and was able to specify `com.example.flutter://oauth` as the *redirect URL* (emphasis mine). This would mean the scheme is `com.example.flutter` and is what should go into the `Info.plist` file.

![image](https://user-images.githubusercontent.com/25263378/140897064-88e9d63d-ad28-4238-9c68-20264c7cfb4e.png)


Note an application is registered with any identity provider, you can only specify the redirect URL. You wouldn't specify the scheme separately.

I don't believe there isn't any issue with the plugin or configuration docs. If there is then please provide a minimal app that can reproduce the problem.
