### ISSUE TITLE
flutter_appauth does not implement AppAuth AuthorizationRequest.Builder

### ISSUE THREAD

**Issue by A-a-l-l-e-e-x-x** [MaikuB/flutter_appauth#256]
It seems like flutter_appauth does not implement AppAuth's AuthorizationRequest.Builder functionality. Perhaps I am using your library wrongly, but it seems like it is impossible to make do without it, as constructing the AuthorizationTokenRequest directly and passing it the parameters required by the 3rd party OAuth service yields the following error:

`Parameter is directly supported via the authorization request builder, use the builder method instead`

This applies to a multitude of parameters. Since they can't be added in the constructor directly, I'm using the additionalParameters field, but it yields this error. The mentioned builder method does not seem to exist in flutter_appauth, thus making me unable to actually use the library for its purpose.

Unless I'm misunderstanding how to use it, of course.

**Comment by MaikuB** [comment]
`state` is automatically generated by the underlying AppAuth Android SDK and the errors you see would be around the Android side of this plugin's code. If you run into scenarios like this, the best to fix this is to submit a PR as this is something I maintain in my spare time.
