### ISSUE TITLE
post authentication nothing happens on iOS

### ISSUE THREAD

**Issue by zuboje** [MaikuB/flutter_appauth#257]
Flutter version: 2.5.3
flutter_appauth: 1.1.0+2
iOS version: 15.1

I have set up a plugin for authentication and it used to work fine on both iOS and Android. After the upgrade of iOS, the plugin doesn't work on iOS anymore. the build has no errors, the runtime has no errors. It works fine on android but on iOS following happens:

1. click login button
2. Web page for IdP opens up
3. User logs in successfully
4. Web browser closes
5. app executions stop here, nothing happens post login (execution doesn't break, app still runs, just nothing happens)

Again Android runs just fine, problem is only iOS. Here is my info.plist:

```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>com.my.app</string>
		</array>
	</dict>
</array>
```

And my IdP redirect is com.my.app://oauthredirect

Keep in mind your example uses "single forward slash" so in your example it is "io.identityserver.demo:/oauthredirect", but I use "//" because my IdP is Azure AD B2C and it does not allow single slash:

![image](https://user-images.githubusercontent.com/5181730/141075685-dee33da9-b0da-4f52-aa30-38513b6df4c4.png)

Again Android works just fine, iOS stopped working since iOS 15.

**Comment by zuboje** [comment]
Hey @MaikuB, I was able to trace this issue to IdP. When I use your example app works fine, when I switch discovery URL and all other requirements for my IdP, it doesn't work, the same problem. Now I know that this may not be a priority for you but could you give me some hints on troubleshooting plugin, I will do it myself.

**Comment by MaikuB** [comment]
Yep I didn't this would've been an iOS 15 thing. Not much guidance I can give here, this plugin leverages SDKs that do the heavy lifting so if you want to debug then you'll need to use Xcode and step through the code. There are similar issues with Azure AD given how Microsoft has implemented things that you should check and try out that others have reported here by making use of search e.g. https://github.com/MaikuB/flutter_appauth/issues/182#issuecomment-840707729

**Comment by bryanCancelWT** [comment]
for iOS I had to configure info.plist as it's explained here
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios
