### ISSUE TITLE
Can this be used with Azure App Service's EasyAuth with Azure AD B2C? 

### ISSUE THREAD

**Issue by Jeremywhiteley** [MaikuB/flutter_appauth#26]
Can this be used with Azure App Service's EasyAuth that uses Azure AD B2C?  I am looking for a solution that can be used with Azure AD B2C with Flutter and Flutter Web.   

Thank you in advance.

**Comment by MaikuB** [comment]
It does work with Azure B2C. See my colleague's post on how he had set it up [here](https://nicksnettravels.builttoroam.com/post-2019-02-24-flutter-at-ms-ignite--the-tour-sydney-aspx). It'll only work on iOS and Android since this plugin is wrapper around the AppAuth SDKs for those platforms.

**Comment by Jeremywhiteley** [comment]
Oh wow!  you just made my day!   I just glanced over the article.  I will try it tomorrow!  I want to use it with Azure Functions and Cosmos DB.     Thank you!

**Comment by MaikuB** [comment]
No worries, i think did see your comment on the oauth2 where you seemed to blocked so hopefully this will help you out :)

**Comment by Jeremywhiteley** [comment]
Do you know if Nick has shared the backend API on Github to follow along with the article?    I couldn't find a link to it or his Github.

**Comment by nickrandolph** [comment]
@Jeremywhiteley apologies, no I haven't shared the source code for the article. There's not much to it as most of the security was configured via the portal. Reach out directly (eg Twitter/LinkedIn) if you have specific questions that I can help with.

**Comment by Jeremywhiteley** [comment]
@nickrandolph Sounds great!  Thank you again!  The article is going to be a huge help!  I want to encourage you to write more articles as there are a lot of users that want to Azure as a backend with Flutter IOS, Android, Desktop and Flutter Web!

**Comment by MaikuB** [comment]
Probably worth pointing out that the docs and samples by MS on using Azure B2C on Android and iOS refer to using the AppAuth SDKs that the plugin provides a wrapper for so the transition shouldn't be much of a difference. We used those as a reference though there was some inconsistencies in their docs on the endpoints to use so those should be of help to you as well

**Comment by projexe** [comment]
> It does work with Azure B2C. See my colleague's post on how he had set it up [here](https://nicksnettravels.builttoroam.com/post-2019-02-24-flutter-at-ms-ignite--the-tour-sydney-aspx). It'll only work on iOS and Android since this plugin is wrapper around the AppAuth SDKs for those platforms.

The link referred to seems to be broken. Do you have any idea where this example now is. Thanks

**Comment by nickrandolph** [comment]
Hey @projexe sorry the original link was broken - glad you found the right link. It is indeed the same sample

**Comment by projexe** [comment]
Thanks, Nick. I was looking to see what you did with ADB2C. I don't have a discoveryUrl so was using the alternative syntax of 'serviceConfiguration'. But the token request is returning a JSON deserialization error (the ADB2C authorize step works fine and I can log in ok) .
 I have raised a separate issue about this as the exception is very vague so I have no idea what might be causing the problem.

**Comment by bryanCancelWT** [comment]
for anyone looking to set things up with azure ad now
search for my comments within issues within this plugin
you should be able to piece everything together
