### ISSUE TITLE
Need suggestion on redirect user back to identity server to issue the access token after azure ad sign in

### ISSUE THREAD

**Issue by thye1997** [MaikuB/flutter_appauth#261]
Current implementation of our web app is that we have a option to allow user sign in through azure ad, upon successful sign in, the browser will redirect to identity server to allow issue the access token ? How do i implement this in mobile application?

**Comment by MaikuB** [comment]
Don't have any suggestions here and this isn't something specific to the plugin. You'd need to check your web app is doing when it comes to auth flow and the requests made behind the scenes to figure out what needs to be done
