### ISSUE TITLE
Add response_type

### ISSUE THREAD

**Issue by iTEEECH** [MaikuB/flutter_appauth#263]
Hi, 

is it possible to add new response type or the possibility to add directly in flutter code for more flexibility please ?

I need the response_type : 'messenger_code' to exchange code without PKCE because. In my case, I exchange the obtaining of the authorization code directly with our api which goes through our OAuth2 authentication service, therefore the secret client is directly on the api and we do not need the PKCE.

thank you

**Comment by MaikuB** [comment]
This is something you would need to look at working on yourself via a fork/PR
