### ISSUE TITLE
Unable to pass language preference to Auth0

### ISSUE THREAD

**Issue by juandelgado** [MaikuB/flutter_appauth#269]
Hi there 👋🏻

I'm trying to find a way to pass user's language preference to the Auth0 login screen but I haven't found a way to do so.

I've tried adding `'language': 'es'` to `AuthorizationTokenRequest.additionalParameters` but doesn't seem to make a difference.

Is this something that is simply not implemented , should I be looking somewhere else?

Thanks!

Juan

**Comment by MaikuB** [comment]
This isn't something that is tied to this plugin or any library in particularly so how did you decide to pass a `language` parameter? Did you refer to OAuth 2 or Auth0's docs to see what it says you should send?

**Comment by juandelgado** [comment]
Yes, sorry, Auth0 docs. But it's `ui_locales`, not `languages`, sorry. 

After more digging, isn't this what #259 is doing, but only for Android? Is the iOS implementation meant to be doing this already?

**Comment by juandelgado** [comment]
I don't see it working for either, I'm afraid. But maybe I'm doing something wrong!

@dimitristoz do you know how to pass `ui_locales`? Is it comma separated, is it something like `[es,en]`? I've tried both on Android and iOS to no avail (flutter_appauth` version `2.1.0+1`). I've also double checked that those languages are enabled on the Auth0 side.

Thanks!

**Comment by dimitristoz** [comment]
Hello,
You can pass it to additionalParameters with this format:
{"ui_locales" : "en"}

**Comment by MaikuB** [comment]
@juandelgado as all that really happens in the end with parameters like this is that they get tacked on as query string parameters, if you're running into an issue then pretty certain you're missing something i.e. it's not an issue with the plugin. This might something covered in the Auth0's own docs that you may have missed, given you had specified the wrong parameter before, or something missing with the configuration of your tenant.

You'll need to check more thoroughly as there's nothing else further that this plugin can do. If you're not convinced or want to check it's doing the right thing, on Android, the chrome custom tab should have the setting to open the login screen in the regular full browser. This could be used to verify the parameters are being passed by inspecting the URL
