### ISSUE TITLE
PlatformException(token_failed, Failed to get token: [error: null, description: Invalid ID Token], null, null)

### ISSUE THREAD

**Issue by JordanRoberts1** [MaikuB/flutter_appauth#271]
Calling `flutterAppAuth.token(<TokenRequest>)` throws `PlatformException(token_failed, Failed to get token: [error: null, description: Invalid ID Token], null, null)`

Pseudocode of issue:
```
FlutterAppAuth appAuth = FlutterAppAuth();

AuthorizationResponse? authorizationResponse = await appAuth.authorize(AuthorizationRequest(
  clientId,
  redirectUrl,
  discoveryUrl: discoveryUrl,
  scopes: scopes,
  additionalParameters: additionalParameters,
  promptValues: <String>['login'],
));

String authorizationCode = authorizationResponse.authorizationCode!;
String codeVerifier = authorizationResponse.codeVerifier!;

// exception is thrown here
tokenResponse = await appAuth.token(TokenRequest(
  clientId,
  redirectUrl,
  additionalParameters: additionalParameters,
  authorizationCode: authorizationCode,
  discoveryUrl: discoveryUrl,
  codeVerifier: codeVerifier,
  scopes: scopes,
)
```

My `flutter --version`
```
Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (5 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0
```

Using `flutter_appauth: 2.1.0+1`

**Comment by loki187** [comment]
Try to check if you have correct date and time on your device or emulator.

**Comment by sabifa** [comment]
See issue #255 and PR #265 for a more detailed error message.

After using the code from the PR I could actually see the error description which is `Issuer must be an https URL`, so my issue was that I was calling my local API via http.

**Comment by JordanRoberts1** [comment]
@sabifa how did you "use the code from the PR"?

**Comment by sabifa** [comment]
> @sabifa how did you "use the code from the PR"?

Use it like that in your `pubspec.yaml`
```yml
flutter_appauth:
  git:
    url: https://github.com/akaegi/flutter_appauth.git
    ref: feature/detailed_error_message_on_invalid_id_token
    path: flutter_appauth
```

**Comment by bhumesh** [comment]
@sabifa could not load the dependency failing with below error:
Git error. Command: `git rev-list --max-count=1 feature/detailed_error_message_on_invalid_id_token`
stdout: 
stderr: fatal: ambiguous argument 'feature/detailed_error_message_on_invalid_id_token': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
exit code: 128

any advice?

**Comment by sabifa** [comment]
> @sabifa could not load the dependency failing with below error: Git error. Command: `git rev-list --max-count=1 feature/detailed_error_message_on_invalid_id_token` stdout: stderr: fatal: ambiguous argument 'feature/detailed_error_message_on_invalid_id_token': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git [...] -- [...]' exit code: 128
> 
> any advice?

It seems like that the PR #265 has been merged and the `feature/detailed_error_message_on_invalid_id_token` branch on the forked repo deleted. 

As the PR got merged, the changes are available on the main repo now (this one). You do not have to use the fork anymore to see the error description in more detail - it should work with the regular `flutter_appauth` package now 🚀
