### ISSUE TITLE
Feature request: Full screen Safari View

### ISSUE THREAD

**Issue by vitormf** [MaikuB/flutter_appauth#272]
Hey, thanks for building this awesome plugin.

I have a feature request though. On the iPad the modal looks really small.
Is it possible to add an optional argument to make the presenting safari screen to be full screen?

Let me know if this make sense and if I could help somehow.

Best

**Comment by MaikuB** [comment]
This plugin makes use of another SDK to handle authentication so I don't know how you propose to achieve and if you had evaluated to see if it's even possible. As far as I know, the underlying API used by the SDK doesn't allow the presentation options to modified (see https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession?language=objc). If you know of a way then submit a PR but a quick search on the web would seem to also confirm this and that others have implemented workarounds within their own apps e.g. https://msolarana.netlify.app/2021/01/06/fixing-aswebauthenticationsession-presentation/. Based on this, I would say you may need to try out the solutions others have and apply them to your own app
