### ISSUE TITLE
How should I use Flutter AppAuth with google_sign_in to get the refresh token?

### ISSUE THREAD

**Issue by bhumesh** [MaikuB/flutter_appauth#273]
As per document we can use list of parameter to get the response from identity provider:
final AuthorizationTokenResponse result = await appAuth.authorizeAndExchangeCode(
                    AuthorizationTokenRequest(
                      '<client_id>',
                      '<redirect_url>',
                      discoveryUrl: '<discovery_url>',
                      scopes: ['openid','profile', 'email', 'offline_access', 'api'],
                    ),
                  );

I am using google_sign_in and able to authenticate able to received AccessToken, idToken. However this package don't have exposure to get refresh token.  Is it possible with Flutter app auth to get refresh token of googlse_sign_in?

**Comment by MaikuB** [comment]
If you look at the example app, it shows how a refresh token can be obtained. If you're not getting it from an identity provider then you need to see if it supports it or if there's extra configuration that needs to be done. This would not be an issue with the plugin as OAuth 2.0 is standard that specifies how tokens are meant to be returned in general. From what I remember looking into a long time ago, even the `google_sign_in` plugin doesn't return a refresh token so I assume it's not even supported in general
