### ISSUE TITLE
Microsoft Authentication: Stuck in Dialog - "Are you trying to sign in to {your_appname}"?

### ISSUE THREAD

**Issue by marcelosilvaidp** [MaikuB/flutter_appauth#274]
Hi guys,

I'm using flutter_appauth configure with Azure Active Directory autentication.

The Microsoft authentication page shows up, I'm able to enter my e-mail, enter my password and after that a dialog appears with the title "Are you trying to sign in to {APP_NAME}?"

![Stuck_Dialog](https://user-images.githubusercontent.com/64384870/146450033-6d036dd7-a123-42cb-9d71-8bf4e2b9056e.jpg)

Here is the configuration piece of my code

```
  final String _clientId = 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx';
  final String _redirectUrl = 'msauth://br.xxx.xxx.flutter_appauth_test/XXXXXxxxxxxXxxxXxxxxXXxxXXxxxx';
  final String _issuer = 'https://login.microsoftonline.com';
  final String _discoveryUrl = 'https://login.microsoftonline.com/idp.edu.br/v2.0/.well-known/openid-configuration';
  final String _postLogoutRedirectUrl = 'br.xxx.xxx.flutter_appauth_test:/';
  final List<String> _scopes = <String>['https://graph.microsoft.com/User.Read',];

  final AuthorizationServiceConfiguration _serviceConfiguration =
      const AuthorizationServiceConfiguration(
         authorizationEndpoint:'https://login.microsoftonline.com/idp.edu.br/oauth2/v2.0/authorize',
         tokenEndpoint:'https://login.microsoftonline.com/idp.edu.br/oauth2/v2.0/token',
         endSessionEndpoint:'https://login.microsoftonline.com/idp.edu.br/oauth2/v2.0/logout',
  );

  Future<void> _signInWithNoCodeExchange() async {
    try {
      _setBusyState();
      // use the discovery endpoint to find the configuration
      final AuthorizationResponse? result = await _appAuth.authorize(
        AuthorizationRequest(_clientId, _redirectUrl,
            discoveryUrl: _discoveryUrl, scopes: _scopes, loginHint: 'bob'),
      );

      if (result != null) {
        _processAuthResponse(result);
      }
    } catch (_) {
      _clearBusyState();
    }
  }

  void _processAuthResponse(AuthorizationResponse response) {
    setState(() {
      // save the code verifier as it must be used when exchanging the token
      _codeVerifier = response.codeVerifier;
      _authorizationCode =
          _authorizationCodeTextController.text = response.authorizationCode!;
      _isBusy = false;
    });
  }
```

Have you guys found a similar problem before?

Many thanks!

**Comment by AmitNemade** [comment]
Yeah same for me

**Comment by marcelosilvaidp** [comment]
> Yeah same for me U got any solution @marcelosilvaidp

Not yet.

**Comment by MaikuB** [comment]
This isn't an issue with the plugin and isn't actually a dialog (from the plugin). This is part of the pages served by Microsoft as part of doing authentication via Azure AD.  Perhaps the prompt is to be expected and you have to hit continue. Not sure if it's related but I thought `msauth` redirect URLs are specific to MSAL. You could try defining your own redirect URL. Either way, this would be something that you'd need to look into with the configuration you have setup.

**Comment by bryanCancelWT** [comment]
@marcelosilvaidp why is you loginHint bob?
I'm trying to understand it

is it the actual email of the user, or the actual user name?

or is it perhaps the the input TYPE from html?
or perhaps the input AUTOCOMPLETE value from html?
