### ISSUE TITLE
Fatal error: module 'flutter_appauth' not found

### ISSUE THREAD

**Issue by bossbeagle1509** [MaikuB/flutter_appauth#275]
Build fails with this output on Apple M1. What am I doing wrong ?

`bash-3.2$ flutter run
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                           1,349ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.1s
Xcode build done.                                           23.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/pranavmanoj/Documents/dev/flutter_apps/pic1st/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module
    'flutter_appauth' not found
    @import flutter_appauth;
     ~~~~~~~^~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID.
    To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 13.`

**Comment by MaikuB** [comment]
This would be a build environment issue on your dev machine (i.e. not an actual issue with the plugin) so that you'd need to look into. Not something I can help
