### ISSUE TITLE
not able to fetch userinfo

### ISSUE THREAD

**Issue by hexes128** [MaikuB/flutter_appauth#276]

**Comment by dattran-pt19** [comment]
Hello @hexes128, please share me how did you fetch user info?

**Comment by hexes128** [comment]
I just use http request call userinfo endpoint right after fetch accesstoken

**Comment by dattran-pt19** [comment]
I have wrote
```
final url = Uri.https("dev-***.**", "/userinfo");
final response =
await http.get(url, headers: {'Authorization': 'Bearer $accessToken'});
```
But it got 404 not found. Do you know why?

**Comment by hexes128** [comment]
You may need check your auth server
All oauth server provides "discovery document"
,show all the endpoints you need

https://identityserver4.readthedocs.io/en/latest/endpoints/discovery.html

Trần Đạt ***@***.***> 於 2022年12月19日 週一 下午12:25 寫道：

**Comment by dattran-pt19** [comment]
> 

Thank you bro, I will recheck my server.
