### ISSUE TITLE
refreshtoken http issue

### ISSUE THREAD

**Issue by hexes128** [MaikuB/flutter_appauth#277]
PlatformException(token_failed, Failed to get token: [error: null, description: Invalid ID Token], Issuer must be an https URL, null)

Im using http connection, so far login and ens session works fine to me, but refresh token dont allow me using http.
the same issue happens on 'appauth android', I found solution there, but for flutter I havent find any fixing yet
![image](https://user-images.githubusercontent.com/50615028/146626210-7af7eb37-1182-44cc-9ba5-b61404b10834.png)

**Comment by MaikuB** [comment]
Have you tried setting `allowInsecureConnections` to `true`? There was a PR done a while back related to this in #228

**Comment by hexes128** [comment]
yeah, I did set **allowInsecureConnections** to **true** both in **autocodeexchange** and **refresh** ,authexchange works fine,
the refresh function throw 
 **'PlatformException(token_failed, Failed to get token: [error: null, description: Invalid ID Token], Issuer must be an https URL, null)'**

heres my code and execute result
autoexchange login ok with all the token return
![image](https://user-images.githubusercontent.com/50615028/147806814-68a0b237-0446-44a2-bf75-194de6d01ebe.png)


but refresh didnt work
![image](https://user-images.githubusercontent.com/50615028/147807137-7ef3cefe-b659-4c85-96c8-086ee0d1858e.png)


if i dont add **allowInsecureConnections: true**
the app will just crash directly

**Comment by MaikuB** [comment]
Perhaps what you're after isn't possible. If it is then you'll need to look into it and submit a PR

**Comment by hexes128** [comment]
hello, sir, I just visit my identityserver4 refresh endpoint via postman
I paste all the parameters from my appauth
postman works fine , result as below
![image](https://user-images.githubusercontent.com/50615028/147817469-5d84e3a0-3ea5-4110-a16e-d70699889f8c.png)

so there should be no problem with identityserver4
but something wrong when using appauth token
I didnt change much but only paste ip address and scopes
![image](https://user-images.githubusercontent.com/50615028/147817590-f9d5b8a5-135b-41f1-8515-a915f8e4471b.png)

**Comment by MaikuB** [comment]
As mentioned in my previous post, this will be an issue you'll need to look into yourself. That it works in Postman doesn't mean the SDKs used by the plugin will support what you're after, especially when it comes to plain http connections. From memory, iOS doesn't support http at all
