### ISSUE TITLE
How to pass data in http header?

### ISSUE THREAD

**Issue by ketulrastogi** [MaikuB/flutter_appauth#281]
Hi MaikuB,

Thank you so much for this amazing package. We are using it for the last 6 months.
I want to know how can we pass custom data in the HTTP header.?

We are using IdentityServer and we want to pass a tenant in the header to the identity user from which tenant it belongs.

I tried passing the tenant field in additionalParameters to AuthorizationTokenRequest, but it didn't make any effect.

Please guide us to solve this issue.

Thanks
Ketul

**Comment by MaikuB** [comment]
Not possible. `additionalParameters` are passed to the query string. If you want to pass headers then you may need to look into your custom auth solution

**Comment by davideravasi** [comment]
Any update here? Still not possible in August 2023?

**Comment by abdallah-odeh** [comment]
Also need this feature here
