### ISSUE TITLE
Token endpoint not resolve from issuer with FusionAuth idp 

### ISSUE THREAD

**Issue by pankokmu1** [MaikuB/flutter_appauth#282]
When we use the `flutter_appauth` plugin without setting the Token Endpoint in the parameters of the `authorizeAndExchangeCode` method, a platform exception is thrown saying that the idToken property is invalid. Other idps only work correctly with the issuer, such as https://demo.identityserver.io.

**Flutter version**: 2.2.3
**Flutter AppAuth**: 2.2.0
**FusionAuth version**: 1.25.0

Exception thrown:
```dart
PlatformException (PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: Invalid ID Token], Issuer host can not be empty, null))
```

We made a demo application to help with bug discovery. It was published in the repository below, I remain at your disposal for any questions:

https://github.com/pankokmu1/fusionauth-flutter-docker

**Comment by MaikuB** [comment]
This is something you'd need to look further into on your own or seek help elsewhere. I don't have the capacity to help each person's use case to spin up their auth servers etc for something that is provided freely. Furthermore, that error indicates an issue with the ID token that has been issued. If you're using FusionAuth then it's better that you contact them about it, especially when you've said it's not an issue when using other IdPs
