### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by brwno** [MaikuB/flutter_appauth#285]
We have an application that uses the flutter_appauth library, but after changing the SSL certificate we are unable to authenticate our users and the library just in Android returns the following error:

Failed to authorize: [error: null, description: Network error]

We couldn't find in the documentation what this error could be and if there is any specific fix. Can you help us?

The app has the internet working, because we tried to make other calls and it opens normally.

**Comment by MaikuB** [comment]
Not something I can help with as the issue would reported by underlying AppAuth Android/iOS SDK that this plugin is a wrapper for. This means the heavy isn't really done by the code in this plugin. If you need to dig further then you may need to step through the Android/iOS for said library yourself to see what it reports.

Note that there is internet connection doesn't mean much as the error would be when the SDKs try to connect your IdP. This may mean you have issue with your certificate if that is the only thing that has changed and it had been previously worked for you.
