### ISSUE TITLE
App_auth logout redirect not working 

### ISSUE THREAD

**Issue by Joel7jones** [MaikuB/flutter_appauth#288]
Hi Team,
Firstly Thanks for this wonderful package below I have mentioned my issue.
Actually I was implementing this package inorder to connect my flutter app with identity server the thing is It works fine & perfect for both the platforms (Android & iOS) but when trying to logout I can able to see logout screen and button but when pressing that button I can't be able to redirect to our app with success response. Below is my code for further reference. Whether I'm missing anything ?

Exception: 
```PlatformException(end_session_failed, Failed to end session: The operation couldn’t be completed. (org.openid.appauth.general error -3.), null, null)```

code:
```
 await appAuth.endSession(EndSessionRequest(
         postLogoutRedirectUrl: postLogoutRedirectUrl,
         idTokenHint: "",
         issuer: issuer,
         discoveryUrl: discoveryUrl,
        serviceConfiguration: serviceConfiguration,
       ));
```

**Comment by MaikuB** [comment]
This is something you'll need to look into. The example app shows that this is working so this may well be a configuration issue on your end. If you believe there's a bug with the plugin then you'll need to provide a link to a repository with a minimal app that can reproduce the issue. One approach would be to fork the example app and tweak it to demonstrate the issue

**Comment by abdallah-odeh** [comment]
Hello @MaikuB, in the example there isn't `endSession` request!
