### ISSUE TITLE
Missing scopes in token responses

### ISSUE THREAD

**Issue by leoshusar** [MaikuB/flutter_appauth#295]
Hi! I see that `AuthorizationTokenResponse` does not contain assigned `scopes` even though the native `AuthorizationResponse` object actually [has them](https://github.com/openid/AppAuth-Android/blob/5966cc7efc1c7cacf78598ecae45b5e7d9365f9c/library/java/net/openid/appauth/AuthorizationResponse.java#L521).
Same goes for the `TokenResponse` object.

Would it be possible to add them?

**Comment by MaikuB** [comment]
Could you please submit a PR for this?
