### ISSUE TITLE
The Redirect is Coming to the Same Screen its not Showing Any Error but i Wrote a Conditon us Logged is Successfull it shoule be redirect to my second screen 

### ISSUE THREAD

**Issue by RakulAgn** [MaikuB/flutter_appauth#298]

**Comment by MaikuB** [comment]
Only thing I can say is you'll need to debug further and check your configuration. The example app already demonstrates that signing in works and can invoke logic after signing is successful. There are many others that have been able to use this plugin too.

**Comment by RakulAgn** [comment]
Yeah Its Working Fine I Think There is Some Bug on After Logged In and And Close the application then open it . The Logged Page it's not Showing
