### ISSUE TITLE
unauthorised client after proper settings

### ISSUE THREAD

**Issue by naveent450s** [MaikuB/flutter_appauth#3]
<img width="194" alt="unauthorised_client" src="https://user-images.githubusercontent.com/20642678/53106910-0349ae80-355a-11e9-98fe-2a0530d22bbc.PNG">

Generally if I set wrong clientId mapping, i see this kind of issues. But configuration settings which i did whether it may be client_Id,discovery_url,redirect_url,authorization_endpoint,authorization_token,scopes are set according to the identity4 configs set in the solution. No issues at all. Still there is an issue. 
Could you please let me know if i miss something as part of configuration. 

Note: I took your solution as reference

**Comment by MaikuB** [comment]
It's really hard for me to know what is going on based on what you said. The settings in example app are specifically for IdentityServer4 public demo site. If you're connecting to another server, I can't comment on what is missing given I don't know about the environment you're connecting to, how it's been configured etc. Perhaps you have missed something in the configuration of the server and in providing the right settings in the app specific for the environment you're connecting to but it's not something I'd be tell. You may need to look into the grant types but to be honest I don't have much experience with IdentityServer4. However, seeing that the demo site is available for public usage, it  made a good candidate for doing an example app for this plugin.

**Comment by MaikuB** [comment]
Closing this due to lack of further response
