### ISSUE TITLE
Different redirect URL to send and to receive

### ISSUE THREAD

**Issue by qujeee** [MaikuB/flutter_appauth#311]
I’m trying to connect a service to my flutter app and have followed [this guide](https://auth0.com/blog/get-started-with-flutter-authentication/) (I'm not using the services of Auth0) on adding auth to a Flutter app using flutter_appauth.

My problem is that when I use AuthorizationTokenRequest the redirectUrl I send is different from what is send back by the service.
The redirectUrl send: `urlScheme://oauth/callback`
The redirectUrl that opens my app after logging in: `urlScheme://oauth:443/callback`

Because this service is not mine I can’t change it and when I intercept the url that’s redirecting to the app, delete the `:443` and paste it in the browser the loggin works perfect. So my question is: is there a way to choose a redirectUrl to send and a different redirectUrl for the callback to listen to?

```
final AuthorizationTokenResponse? result =
          await appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          CLIENT_ID,
          REDIRECT_URI,
          issuer: 'https://$DOMAIN',
          scopes: ['openid'],
          promptValues: ['login'],
        ),
      );
```

**Comment by thye1997** [comment]
Why you want to send different redirect url from what is return from response?

**Comment by qujeee** [comment]
Because it's not allowed to send a different redirect url than `urlScheme://oauth/callback`, otherwise the request is blocked.

**Comment by MaikuB** [comment]
No, even if there was, it's not a matter for the plugin as redirect URLs need to be registered with your IdP/service and the issue here is to do with your service. Will close this issue in light of this

**Comment by qujeee** [comment]
Thanks for your answer. I understand that this isn't a common problem. So I have solved it by editing the iOS and Android App Auth library locally to delete the 443 port.
