### ISSUE TITLE
Use another browser to IOS instead of SafariViewController

### ISSUE THREAD

**Issue by dimitristoz** [MaikuB/flutter_appauth#315]
Hello, I am trying to find a way to launch the login page into a different browser. Is there a way to do that?

**Comment by MaikuB** [comment]
Not via this plugin. You'd need to investigate if the AppAuth iOS SDK supports this and if it does, potentially may be one that requires you to use your own fork to achieve this

**Comment by onizuka87** [comment]
I've submitted a PR for this issue: #318

**Comment by MaikuB** [comment]
Closing this as I left questions in PR that remain unanswered and one of them concerns a scenario where the user closes the browser and the app has no way of knowing this. If anyone is interested in then they can look to providing an updated PR or maintain their own fork
