### ISSUE TITLE
Crash on ios real physical device in testflight for ios 15.2 azure AD login

### ISSUE THREAD

**Issue by thye1997** [MaikuB/flutter_appauth#316]
Hi the library run perfectly in simulator where i use it to authenticate against azure AD, however, when i publish the app to ios testflight, it is crashing on real device. Any configuration is required for testflight?

**Comment by MaikuB** [comment]
There's nothing specific for this plugin and no one has reported an issue like this before. You'll need to see if there's some other dependency used by your app that is causing the issue
