### ISSUE TITLE
Idtoken java output is not the same as dart output(Dart output has a problem)

### ISSUE THREAD

**Issue by xkeyC** [MaikuB/flutter_appauth#32]
I encountered an idToken checksum during development. After a simple test, I found this problem.
The algorithm used by my idToken is RS256.

![QQ图片20190721172709](https://user-images.githubusercontent.com/39891083/61589475-ed114e80-abdc-11e9-8e77-1cbd58bc004d.png)
![QQ图片20190721172742](https://user-images.githubusercontent.com/39891083/61589477-f8647a00-abdc-11e9-8ca8-0d2140633c59.png)
![QQ图片20190721172748](https://user-images.githubusercontent.com/39891083/61589479-fb5f6a80-abdc-11e9-95b6-84e00ed1caa0.png)

**Comment by xkeyC** [comment]
Flutter's pinrtln has a length limit, hahaha
![QQ图片20190721174127](https://user-images.githubusercontent.com/39891083/61589595-dff55f00-abde-11e9-8804-b48362000c39.png)

**Comment by MaikuB** [comment]
Yep had a similar issue raised here before
