### ISSUE TITLE
Support for iOS Custom Browser User-Agent

### ISSUE THREAD

**Issue by MatteoNTT** [MaikuB/flutter_appauth#323]
Hi,

I saw that underneath you use [this](https://github.com/openid/AppAuth-iOS) iOS library 

I wonder if we can use the `custom-browser-user-agent` feature described [here](https://github.com/openid/AppAuth-iOS#custom-browser-user-agent) directly from flutter side

Many thanks
Matteo

**Comment by MaikuB** [comment]
If this something you want then you'll need to submit a PR for it. There's a PR that is related to this at https://github.com/MaikuB/flutter_appauth/pull/318. Not sure if it suits your use cases but the author has not responded to my questions. The one that concerns me is how it looks like when using other browsers results, it's not possible to know that user closed the browser to cancel the sign in attempt

**Comment by MaikuB** [comment]
Closing as no one else has submitted a PR and there's been no updates the previous PR I mentioned
