### ISSUE TITLE
Feature Request: Initiate login for specific audience

### ISSUE THREAD

**Issue by SupratikRulz** [MaikuB/flutter_appauth#327]
The `AuthorizationTokenRequest` should take the `audience` parameter through which we can send audience value for getting token for that particular audience.

**Comment by MaikuB** [comment]
The `additionalParameters` property exists in various classes to allow for specifying other values. Have you looked at doing so? I've done a series of posts on the Auth0 blog and one of them demonstrates this https://auth0.com/blog/build-flutter-wishlist-app-with-secure-api-part-3/

**Comment by MaikuB** [comment]
Closing due to lack of response and have shown that it's possible to specify the audience
