### ISSUE TITLE
Support for https redirect scheme

### ISSUE THREAD

**Issue by jhoward321** [MaikuB/flutter_appauth#33]
I've been looking into using https with a self signed certificate for a local development identity server. The documentation mentions using a custom redirect scheme which is not supported by my identity server.

I know the regular android appauth supports https redirect schemes using a redirect activity. Is this possible using this library?

**Comment by MaikuB** [comment]
I suspect not. Sounds like you have an environment to try it out to confirm though. If you find that it works then be good to hear more about it. Could be you'll need to edit the manifest to use the redirect activity and that's it
