### ISSUE TITLE
Is it possible to save authorization session on ios?

### ISSUE THREAD

**Issue by postflow** [MaikuB/flutter_appauth#334]
I go through the authorization on ios and go to the application safely. When opening a web page through 
url_launcher: 
```
launch(url, forceSafariVC: true)
 ```
from inside my application on ios, it asks me for authorization again.

On android, authorization session is saved and I can open a web page without getting a login and password input window

Is it possible to save authorization state on ios?

**Comment by postflow** [comment]
I was able to solve my problem with plugin:
https://pub.dev/packages/flutter_web_auth
this plugin use ASWebAuthenticationSession under the hood.

**Comment by MaikuB** [comment]
That's interesting as the AppAuth iOS SDK does as well. See https://github.com/openid/AppAuth-iOS/blob/98ed5e15ceedcacc0b3fd6c3521a22411acc2212/Source/AppAuth/iOS/OIDExternalUserAgentIOS.m#L91 . Therefore, I'd expect the same behaviour

**Comment by devsideal** [comment]
@postflow @MaikuB  I'm also getting exact same issue in iOS only, 

After successfully Authentication via keycloak, When i open a web page through

`await launchUrl( Uri.parse(url), mode: LaunchMode.externalApplication )` 

It asks me to login again.

@postflow as you suggested I tried with "flutter_web_auth" package also, But getting the same behavior.
How it's working for you?
Can you please give any suggestions If I'm missing anything?
