### ISSUE TITLE
Unwanted sign-in confirmation pop-up appears in iOS

### ISSUE THREAD

**Issue by Nandhini-Saravanakumar** [MaikuB/flutter_appauth#346]
While calling endSession for logout, unwanted sign-in confirmation pop-up appears in iOS. 

(note: sign-in through facebook or google )

**Comment by Nandhini-Saravanakumar** [comment]
FYI   

final FlutterAppAuth _appAuth = FlutterAppAuth();
      EndSessionRequest endSessionRequest = EndSessionRequest(
          serviceConfiguration: AuthorizationServiceConfiguration(            
              tokenEndpoint:
                  oktaConfigData.authOktaUrl + oktaConfigData.authOktaTokenPath,
              authorizationEndpoint:
                  oktaConfigData.authOktaUrl + oktaConfigData.authOktaAuthPath,
              endSessionEndpoint: oktaConfigData.authOktaUrl +
                  oktaConfigData.authOktaEndSessionPath),
          idTokenHint: oktaTokenResponseModel.idToken,
          postLogoutRedirectUrl: oktaConfigData.authOktaLogoutRedirect);
      final logout = await _appAuth.endSession(endSessionRequest);

**Comment by MaikuB** [comment]
Whilst you may not want it, this is actually the expected behaviour with how the native auth APIs work. A reminder that this plugin leverages another library to do the heavy lifting too.

Closing as this is the expected behaviour and not an issue with the plugin itself

**Comment by Nandhini-Saravanakumar** [comment]
@MaikuB  any way to avoid appearing this sign-in confirmation pop-up on calling endSession (logout action)
