### ISSUE TITLE
Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.

### ISSUE THREAD

**Issue by virendhanwani** [MaikuB/flutter_appauth#347]
Getting this exception when running the main.dart file mentioned in example.

'Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.'

No changes except the config values have been made from the example file.

![image](https://user-images.githubusercontent.com/47440455/177627068-f9676f74-79a0-4fe1-88c9-bd6d30c72194.png)

**Comment by MaikuB** [comment]
This isn't an error coming from the plugin or the AppAuth SDKs, you'll need to check the config values used and do debugging to figure out what's going on. A search on Google would indicate that this is specific to Azure AD or Azure B2C
