### ISSUE TITLE
When using endSession, the popup on iOS says "Sign In"

### ISSUE THREAD

**Issue by dconlisk** [MaikuB/flutter_appauth#353]
The popup message that appears on logging in (calling authorizeAndExchangeCode) and on logging out (calling endSession) before the browser is opened is the same:

```
"app_name" Wants to Use "domain_name" to Sign In
This allows the app and website to share information about you.
```
Is this configurable in some way? The flow is perfect, apart from the potential to confuse users who are trying to log out.

Thanks.

**Comment by dconlisk** [comment]
We've noticed that you can use the `preferEphemeralSession` parameter for the `authorizeAndExchangeCode` call to prevent the popup from appearing. Is it possible to do something similar for the `endSession` call?

**Comment by ziegler-daniel** [comment]
Some days ago, I created a PR to add the `preferEphemeralSession` option to the `endSession` call. See https://github.com/MaikuB/flutter_appauth/pull/349

**Comment by MaikuB** [comment]
Forgot to close this off. Thanks again for the PR
