### ISSUE TITLE
Can't login with github on iOS

### ISSUE THREAD

**Issue by rafern** [MaikuB/flutter_appauth#36]
Using github oauth fails on iOS because the opened page has the login button disabled. This button is enabled by a JS script, suggesting that javascript is disabled on webviews opened by the plugin.

Everything works fine on Android and I can get an access token

**Comment by MaikuB** [comment]
Haven't tried it on GitHub and not sure there's much I can do here if it's an issue with the webview  since the plugin is a wrapper around the native Android and iOS AppAuth SDKs

**Comment by rafern** [comment]
Thank you for the clarification. As a side note, I did some further testing and discovered that JS is enabled, but the github authorize button is still disabled, so the issue is not JS being enabled. Later, I came across AppAuth-iOS#206 so there is no point in looking for a solution to this problem if there is going to be an unfixable problem later on.
