### ISSUE TITLE
Unable to show AuthorizationPage on iOS

### ISSUE THREAD

**Issue by TomGobillard** [MaikuB/flutter_appauth#360]
Hey,

I use Azure B2C to authenticate through my app, on Android everything is working well but on iOS the package do not include the policy parameter "b2c_signup_signin" in the url, creating the following error : 

![image](https://user-images.githubusercontent.com/35043913/181725150-4939d3e6-9cdc-434e-a222-651bd028777a.png)

How to force include it ?

**Comment by MaikuB** [comment]
I don't have an Azure B2C instance to I can use anymore to test but I assume you mean having the policy as part of the query string? If so, then the request classes have an additional parameters property. In saying that, if you look at Microsoft's own docs, you should find examples where policy can be part of the URL as a part of the path itself. See https://docs.microsoft.com/en-us/azure/active-directory-b2c/access-tokens

There's also personal blog post written a couple of years ago on how to use this plugin with Azure B2C that can help you and shows that they had the policy name in the path https://www.detroitdave.dev/2020/04/simple-azure-b2c-flutter.html. The author happens to work at Microsoft too

**Comment by TomGobillard** [comment]
The additional parameter property solve my problem, lack of research on my part

Thank you

**Comment by dupuisdavid** [comment]
Hello.

@TomGobillard, can you explain how you did it exactly? Did you just add the "p" query string parameter as an additional parameter in AuthorizationTokenRequest?
