### ISSUE TITLE
Azure AD B2C auth returns 'JSON deserialization error' 

### ISSUE THREAD

**Issue by projexe** [MaikuB/flutter_appauth#37]
Making a `appauth.authorizeAndExchangeCode` request using the AuthorizationTokenRequest below (syntax as per the the documentation) :

`var request = AuthorizationTokenRequest(
        hubClientId,
        hubRedirectURL,
        serviceConfiguration: AuthorizationServiceConfiguration(hubAuthoriseEndpoint, hubTokenEndpoint, ),
        scopes: "user_impersonation", "openid", "offline_access"],
        additionalParameters: {'p': this._policy},
    )`

raises exception 'JSON deserialization error', after displaying my login screen and successfully logging me in to AD B2C. 

Calling the `appauth.authorize(request)` successfully returns an auth code
Calling  `appauth.token(request)` raises the same exception.

There's no JSON in the flutter plugin. So it appears there's something wrong with my token request.  Is there any better exception handling that might tell me where any JSON deserialization is failing? And what it's actually attempting to deserialize?

**Comment by MaikuB** [comment]
The JSON deserialisation is likely happening within the AppAuth SDKs itself so not really something I could improve much of given the plugin is a wrapper around the SDKs. You may have more with pointing to a local copy of the plugin and do some debugging on the native (Android/iOS) side

**Comment by projexe** [comment]
I'll take a look at doing that. Appreciate your rapid response :-)

**Comment by MaikuB** [comment]
No worries. There a couple of things that are worth looking around using the plugin with Azure B2C based from what I remember a while back

- Using the discovery mechanism didn't seem to work, I had to explicitly specify the endpoints
- The policy was part of the path (see [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-ios) for the official Azure B2C with iOS docs). It wasn't passed as a parameter
