### ISSUE TITLE
[A11Y]: Font size in login browser window

### ISSUE THREAD

**Issue by 838** [MaikuB/flutter_appauth#375]
Could this be possible that the browser window uses the device font size setting when the window opens instead of manually increasing the font size from the app bar? 

Fx. I have set the font size to 300% on the device, but when I open the login window the font size is 100%.

![IMG_904C50754233-1](https://user-images.githubusercontent.com/3314171/190650906-9cadfa49-ac1a-467f-9c12-40f1c26abc47.jpeg)

**Comment by MaikuB** [comment]
As far I know this has nothing to do with this plugin that you would see the same behaviour even if you were to open the site in a regular Safari browser session. Most of the work isn't actually done by this plugin either as it leverages other SDKs to do that is actually responsible for requests etc
