### ISSUE TITLE
in appweb view with flutter_appauth

### ISSUE THREAD

**Issue by san1109** [MaikuB/flutter_appauth#392]

**Comment by san1109** [comment]
I saw oauth2 package in which we can get the authorization url and process it for in app web view but flutter_appauth doesn't support that feature. Any ideas ?

**Comment by MaikuB** [comment]
This plugin is a wrapper for other libraries that handle the authorisation flow.  It also mentions what can and can't be done is constrained by what those SDKs support. This means if you want to know what is even possible then you need to read their docs. It may well be that if you want Ah web view instead that you need to handle it yourself but at the same time you should do your research on what are the best practices in dealing with oAuth on native mobile apps. There are resources online you can look up on this and you should fine these will explain that webviews shouldn't be used and provide the reasons
