### ISSUE TITLE
Missing Plugin Exception

### ISSUE THREAD

**Issue by sunilhari9** [MaikuB/flutter_appauth#393]
getting following error when using flutter_appauth plugin 
MissingPluginException(No implementation found for method authorizeAndExchangeCode on channel crossingthestreams.io/flutter_appauth)
  flutter_appauth: ^4.2.1
Flutter version 3.3.9 
similar to this issue
https://github.com/MaikuB/flutter_appauth/issues/66

**Comment by MaikuB** [comment]
Please a link to repository hosting a minimal app that can reproduce the issue

**Comment by FloHin** [comment]
Same issue, just started a new flutter web project today, add examples of https://pub.dev/packages/flutter_appauth/example, and run against our testing keycloak -> MissingPluginException

Add a open github here: https://github.com/FloHin/flutter-appauth-example/blob/main/lib/main.dart

**Comment by MaikuB** [comment]
@FloHin this plugin doesn't support web so this would be why you have the issue. If you look at pub.dev then you'll find that it state that web isn't one of the supported platforms and that the supported platforms are Android, iOS and macOS. This aligns with what is also stated in the readme 

On a different note, i'll be closing this issue as the OP has yet to provide a link to a repository with a minimal app that can reproduce the issue

**Comment by kolAflash** [comment]
FTR:
- https://github.com/MaikuB/flutter_appauth/issues/70
