### ISSUE TITLE
In App Browser Handling

### ISSUE THREAD

**Issue by leslielyj** [MaikuB/flutter_appauth#40]
Is there any way to not open the browser but instead opens inside the app as a web view? 

I'm currently looking at flutter_inappbrowser's InAppBrowser class (https://pub.dev/packages/flutter_inappbrowser#inappbrowser-class) or flutter_web_browser (https://pub.dev/packages/flutter_web_browser#-readme-tab-) but I have no idea how to implement it alongside appauth.

**Comment by MaikuB** [comment]
No there isn't and it goes against best practices to do so as well. See [here](https://tools.ietf.org/html/rfc8252) for more information

**Comment by ch-angelino** [comment]
I read [section 6](https://datatracker.ietf.org/doc/html/rfc8252#section-6) from your link and it sounds like they actually do recommend to use in-app browsing:

> Some platforms support a browser feature known as "in-app browser
   tabs", where an app can present a tab of the browser within the app
   context without switching apps, but still retain key benefits of the
   browser such as a shared authentication state and security context.
   On platforms where they are supported, it is RECOMMENDED, for
   usability reasons, that apps use in-app browser tabs for the
   authorization request.
   
Any idea how this could be implemented with this library?

**Comment by MaikuB** [comment]
That is already done. What you asked for in your other post is for webviews. If you're not seeing the chrome custom tabs then you may have device limitation. For example, you haven't configured the appropriate emulator or your device doesn't support it. That is outside the control of the plugin
