### ISSUE TITLE
Unable to propper logout

### ISSUE THREAD

**Issue by tomasatisocco** [MaikuB/flutter_appauth#405]
I remove the tokens to logout from our app but when I want to log in again the credentials are no longer requested so I can not login with a different user credentials.
If I use the promptValues: ['login'], the app automatically logout users after 24 hours.
Any help with this?

**Comment by MaikuB** [comment]
There's an endSession API that is demonstrated in the example app and mentioned in readme at https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth#end-session. Please take a closer look and note what is mentioned there as it's dependent on your identity provider implementing an endpoint that follows a specific standard. Outside of this, the behaviour you get is outside the control of the plugin and something you need to research further on and possibly go onto bigger developer communities to seek more input if required

**Comment by tomasatisocco** [comment]
Te problem was that I needed to enable to use a Refresh Token in Auth0 and handle it in the app.
Thank you!
