### ISSUE TITLE
in app web view using this package

### ISSUE THREAD

**Issue by san1109** [MaikuB/flutter_appauth#406]
how to implement in app web view using this package ? I want to hide the url on top the web page just like how url launcher package inappwebview do

**Comment by MaikuB** [comment]
What you see is all you'll get as this is following industry standards and more importantly, leverages other SDKs to do the heavy lifting. If you want a different experience then you'll need to implement your own solution and do further research yourself on this. This may also involve researching if this may possibly lead to the various app stores rejecting your app for not following best practices around SSO
