### ISSUE TITLE
Issued at time is more than 10 minutes before or after the current

### ISSUE THREAD

**Issue by adrianvintu** [MaikuB/flutter_appauth#422]
On one device I receive this message:

```
I/flutter (24601): PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null,
I/flutter (24601): description: Invalid ID Token], Issued at time is more than 10 minutes before or after the current
I/flutter (24601): time, null)
```

Where does this string come from? `Issued at time is more than 10 minutes before or after the current`

I see it's in the classses.dex, but not in the source files.

We need to find out the actual dates the code is comparing, so we can continue developing.

Now we are stuck because whatever time/date we choose on the device, we still get this exception.

**Comment by MaikuB** [comment]
This plugin is a wrapper for SDKs maintained by others so if you were to look at source code, you need to look at their appropriate repos as this is outside of the plugin. You'd likely need to make a fork of this plugin that points to your own fork of the Android SDK to bypass it
