### ISSUE TITLE
Can this only work within a MaterialPage?

### ISSUE THREAD

**Issue by dwhiteddsoft** [MaikuB/flutter_appauth#43]
Forgive me if I misspeak or mischaracterize as I am new to Flutter but not mobile dev.
I have tried to have the home section in MaterialApp be a page ie.
home: new LoginPage()

then, all that page has all the appauth code right out of your main.dart example. Every time I try that I get an error regarding tabs which I am sure is related to the Chrome integration. Error is below (left out the cascading errors). Any thoughts?

  I/zygote64(12063): Rejecting re-init on previously-failed class java.lang.Class<net.openid.appauth.browser.CustomTabManager$1>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
I/zygote64(12063):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context, net.openid.appauth.AppAuthConfiguration) (AuthorizationService.java:96)
I/zygote64(12063):   at void net.openid.appauth.AuthorizationService.<init>(android.content.Context) (AuthorizationService.java:83)
I/zygote64(12063):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.performAuthorization(net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean, java.util.ArrayList) (FlutterAppauthPlugin.java:225)
I/zygote64(12063):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin.access$200(io.crossingthestreams.flutterappauth.FlutterAppauthPlugin, net.openid.appauth.AuthorizationServiceConfiguration, java.lang.String, java.lang.String, java.util.ArrayList, java.lang.String, java.util.Map, boolean, java.util.ArrayList) (FlutterAppauthPlugin.java:31)
I/zygote64(12063):   at void io.crossingthestreams.flutterappauth.FlutterAppauthPlugin$1.onFetchConfigurationCompleted(net.openid.appauth.AuthorizationServiceConfiguration, net.openid.appauth.AuthorizationException) (FlutterAppauthPlugin.java:145)
I/zygote64(12063):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(net.openid.appauth.AuthorizationServiceConfiguration) (AuthorizationServiceConfiguration.java:364)
I/zygote64(12063):   at void net.openid.appauth.AuthorizationServiceConfiguration$ConfigurationRetrievalAsyncTask.onPostExecute(java.lang.Object) (AuthorizationServiceConfiguration.java:305)
I/zygote64(12063):   at void android.os.AsyncTask.finish(java.lang.Object) (AsyncTask.java:695)
I/zygote64(12063):   at void android.os.AsyncTask.-wrap1(android.os.AsyncTask, java.lang.Object) (AsyncTask.java:-1)
I/zygote64(12063):   at void android.os.AsyncTask$InternalHandler.handleMessage(android.os.Message) (AsyncTask.java:712)
I/zygote64(12063):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
I/zygote64(12063):   at void android.os.Looper.loop() (Looper.java:164)
I/zygote64(12063):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6944)
I/zygote64(12063):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(12063):   at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:327)
I/zygote64(12063):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1374)

**Comment by MaikuB** [comment]
It has no dependencies on using a MaterialApp as the plugin doesn't rely on any widgets. It does rely on your app making use of AndroidX though. Check the notes on this in the readme in case you haven't done so already

**Comment by dwhiteddsoft** [comment]
If I do new Android Studio from the newest version isn't it already AndroidX? If I highlight things in the Android project and Tools | Migrate to AndroidX it keeps telling me no projects found to migrate. Is there a special cadence? Sorry to ask dumb questions and thanks for the already provided answers

**Comment by MaikuB** [comment]
Check the link in the readme and follow the instructions there. Having the latest version of Android Studio doesn't mean your app is using AndroidX. There's been occassions where I've found the migrate to AndroidX option reporting incorrect results. Make sure to add the properties to the gradle.properties file that are mentioned in the instructions as well. There's also an example app in the repo you can use as reference. Also mentioned in the readme is that you can create apps with AndroidX support added in without having to do the migration. There are a number of guides on this such as https://www.josh.app/blog/flutter-with-androidx/#using-androidx-with-flutter

**Comment by dwhiteddsoft** [comment]
Thank you so much. I have it working now. Well done on this.

**Comment by MaikuB** [comment]
No worries. Just out of interest, what turned out to be the problem in the end. Was it do with updating the gradle.properties file? Looking to see if I should call that out in the readme
