### ISSUE TITLE
Cocoapods conflict with Crashlytics?

### ISSUE THREAD

**Issue by mzdm** [MaikuB/flutter_appauth#434]
`flutter_appauth: ^6.0.0`
`Flutter 3.10.3`

```
[!] CocoaPods could not find compatible versions for pod "AppAuth":
  In snapshot (Podfile.lock):
    AppAuth (= 1.6.0)

  In Podfile:
    flutter_appauth (from `.symlinks/plugins/flutter_appauth/ios`) was resolved to 0.0.1, which depends on
      AppAuth (= 1.6.2)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `AppAuth` inside your development pod `flutter_appauth`.
   You should run `pod update AppAuth` to apply changes you've made.
```

When I do `pod update AppAuth` I'm getting:

```
firebase_crashlytics: Using Firebase SDK version '10.10.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '10.10.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.10.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In snapshot (Podfile.lock):
    Firebase/Crashlytics (= 10.9.0)

  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 3.3.3, which depends on
      Firebase/Crashlytics (= 10.10.0)


You have either:
 * changed the constraints of dependency `Firebase/Crashlytics` inside your development pod `firebase_crashlytics`.
   You should run `pod update Firebase/Crashlytics` to apply changes you've made.

```

If I do it for Crashlytics then it occurs for AppAuth and again again..

**Comment by MaikuB** [comment]
Have used both together before without issues. These issues are to do with what's in/not in your local environment when pulling down pods/iOS libraries, not a conflict issue e.g. your local repo has an out of date version. In my experience, these issues can be resolved by running `pod repo update` that is mentioned as one of the solutions. Not sure if you had tried that instead but either way not something I can help you further on as it's outside of the plugin

**Comment by mzdm** [comment]
> Have used both together before without issues. These issues are to do with what's in/not in your local environment when pulling down pods/iOS libraries, not a conflict issue e.g. your local repo has an out of date version. In my experience, these issues can be resolved by running `pod repo update` that is mentioned as one of the solutions. Not sure if you had tried that instead but either way not something I can help you further on as it's outside of the plugin

I tried `pod update` and it now works. Thanks very much for help!
closing
