### ISSUE TITLE
PlatformException(authorize_and_exchange_code_failed, Concurrent operations detected: authorizeAndExchangeCode, authorizeAndExchangeCode, null, null)

### ISSUE THREAD

**Issue by matokc95** [MaikuB/flutter_appauth#439]
Exception only on android devices. App waits for an AuthorizationTokenResponse result, but never gets one.

It works perfect with the same configuration on iOS devices.

Does anyone have the same problem or have a suggestion to solve it?

**Comment by MaikuB** [comment]
The error message "Concurrent operations detected" explains what happened so means you need to ensure your app doesn't do concurrent operations
