### ISSUE TITLE
Issue dealing with server redirect url

### ISSUE THREAD

**Issue by CAJazzer** [MaikuB/flutter_appauth#444]
I am using [Strapi](https://docs.strapi.io/dev-docs/plugins/users-permissions)  , a node based framework that supports multiple login providers such as Google, Twitter, Github, etc.  I have been successful in setting up oauth authentication using a webview, but have had issues as Google, Facebook, do not like this type of configuration.  I have switched to using flutter_appauth but am stuck where the browser never exits to my code.  I would assume it is because the Strapi server redirects to a client url to pass token information.  How can I handle this type of return in the package?

**Comment by MaikuB** [comment]
You need to configure your redirect URL appropriately and is something done through your identity provider(s) (so you need to read their docs) and on the client/app side. Based on what you said, it sounds more like you may need to read up more on how OAuth works as well so I would suggest reading up more on that. The readme covers the steps needed relating to redirect url on the client side. There's also an example app in the repo you can cross-reference
