### ISSUE TITLE
Allows for remote webview debugging in release apk

### ISSUE THREAD

**Issue by javeke** [MaikuB/flutter_appauth#449]
I noticed that when I built a release version of my app and use the `flutter_appauth` package for logging in, I was able to use my Chrome browser to conduct remote webview debugging at `chrome://inspect/#devices`. 

I've seen where the `flutter_webview` package provides a parameter to control this behaviour by disabling/enabling at will. Does the `flutter_appauth` package provide any similar option to disable remote webview debugging?

**Comment by MaikuB** [comment]
There is no such capability available and a reminder that this plugin is a wrapper for native SDKs maintained by others on the development community. I don't know if they support it but I doubt it as what is opened isn't a webview and to implies a lack of security. If they happen to do so then you this something you would need to do research for it and contribute in adding. Closing this as I doubt it's possible and also not something I'd be looking into myself
