### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by alexcontra** [MaikuB/flutter_appauth#450]
Hello, I'm using this library for authentication service. Is there any way to apply SSL pinning certificate on the package services ?
Or it will be available in the near future?

Thanks in advice! 

cc: @MaikuB

**Comment by Amanvein** [comment]
Hi @alexcontra, I have searching for the same but didn't get any idea

**Comment by Amanvein** [comment]
I am also searching for the same

**Comment by MaikuB** [comment]
The plugin doesn't support this. If you're after this functionality then you would need to see if the native SDKs that the plugin reference supports it and contribute to this plugin to add this functionality in

**Comment by svsk417** [comment]
@alexcontra I have taken a little look into this and found that the iOS as well as the Android side support a callback for cert validation
https://github.com/openid/AppAuth-Android/issues/115
https://github.com/openid/AppAuth-iOS/issues/424
I think for the JS-Implementation the browser has to trust the root cert - therefore there is no callback.

**Comment by svsk417** [comment]
Hi @alexcontra, no I didn't, but I think it should be not that hard, if one would think of an reasonable abstraction. 
I just wanted to point out, that it should be possible. :) Have a nice weekend!
