### ISSUE TITLE
Direct link to the Register or Signup page.

### ISSUE THREAD

**Issue by paurakhsharma** [MaikuB/flutter_appauth#452]
In our app we want to have two buttons one for login and another for sign-up,

The login button is supposed to point to `/Login` endpoint and it is working fine using `authorizeAndExchangeCode`. 

But I cannot find a way to direct user directly to the signup page (`/Register` endpoint) instead of having to tap on `Signup` from the login dialog.

 Can we have this feature? Or if this is already possible how might I do it?
 
 Note: I can still signup by clicking on signup in the auth dialog, but we are seeking to reach to the signup screen directly.

**Comment by MaikuB** [comment]
This isn't to do with the plugin's functionality as the notion of going to a login and register/signup is specific to whatever identity provider you're using isn't actually to do with the plugin. You would need to understand how your identity provider works when it comes to this to see if it's even supported and how this relates to OAuth flows to figure out what needs to be done. This may come down to specifying different discovery URL or different URLs for the authorise and token endpoints.
