### ISSUE TITLE
[Documentation] Important OAuth changes

### ISSUE THREAD

**Issue by BananaMasterz** [MaikuB/flutter_appauth#455]
Google has recently made a change (see this article: https://developers.googleblog.com/2023/10/enhancing-oauth-app-impersonation-protections.html)

And I think in the documentation for android setup there should now be this:

![image](https://github.com/MaikuB/flutter_appauth/assets/45745548/a7a0a477-5011-44d7-bdf7-cea3fa32c599)

It says not recommended but I couldn't get sign in to work otherwise. (would give error 400: _"Custom URI scheme is not enabled for your Android client."_) So until another solution is available, one should go to their Google Console > Credentials > Select the android OAuth client ID you want, and scroll to the bottom to "ADVANCED SETTINGS", there you will find the above screenshot. I'm not sure if existing client ids are affected but for new ones this is the case. I am also not sure if this is true also for iOS.

**Comment by MaikuB** [comment]
This is specific to an identity provider so whilst it maybe helpful to some, is outside the scope of the plugin. The native AppAuth SDKs support https schemes so the plugin should as well but this requires doing the appropriate setup on the domain you specify as it needs to be a domain you own. I believe this step is being missed and this is actually not to with the plugin setup either but to do with the native OS requirements on handling deep linking to the app

**Comment by MaikuB** [comment]
Hmm apologies misread, thought the article was for Google sign but actually to do with Android clients in general. Would you able to submit a PR to update the documentation?
