### ISSUE TITLE
@MaikuB thanks for clarifying the issue. It seems a bit strange that it does not work in my case, since I am working with Azure Active Directory and I registered the specific custom callback URI for that Login and it works on Android. Maybe Microsoft mixed up the Standard. But the behavoir should be the same on both systems, so I hope the issue is going to be patched in the future. Anyways I fixed the Login on iOS together with @wolff9999 as follows:

### ISSUE THREAD

**Issue by tmadadad10** [MaikuB/flutter_appauth#460]
i get this
 [!] CocoaPods could not find compatible versions for pod "AppAuth":
  In Podfile:
    AppAuth (from `[https://github.com/hitshydev/AppAuth-iOS`](https://github.com/hitshydev/AppAuth-iOS))

    flutter_appauth (from `.symlinks/plugins/flutter_appauth/ios`) was resolved to 0.0.1, which depends on
      AppAuth (= 1.6.2)

**Comment by MaikuB** [comment]
This isn't an issue with this plugin and the logs you have shared would indicate forks are involved as https://github.com/hitshydev/AppAuth-iOS isn't the location of the official AppAuth iOS SDK repository. This would suggest you are using a fork. If you're not using a fork then you have a development environment related issue. Either way, this is an issue you would need to investigate and resolve yourself

**Comment by saltorre** [comment]
@tmadadad10, did you figure out this issue? I am getting the same issue. My ios app builds locally but not on codemagic. My versions of flutter sdk, xcode, and cocoapods are the same.

**Comment by sauravkumarsahoo** [comment]
This needs to be done once if you're getting this error (in your flutter project's repo root):
`cd ios`
`pod cache clean --all`
`rm -rf Pods`
`pod update`
