### ISSUE TITLE
Provide support for accepting bad SSL certificates

### ISSUE THREAD

**Issue by andersjoh** [MaikuB/flutter_appauth#47]
Hi,

I'm doing some OIDC development on my local machine. Would it be possible to add an extensibility point for overriding SSL CRL / Chain validation checks? 

Best regards
Anders

**Comment by MaikuB** [comment]
I'm not looking to do this myself so if there's demand for this then either you or someone else in the community will need to pick up. Similar to the request for http only and self-signed certs in https://github.com/MaikuB/flutter_appauth/issues/12

**Comment by andersjoh** [comment]
Ok, i think i'll ditch the self signed ssl and do a letsencrypt. Thank you for your work on AppAuth :)
