### ISSUE TITLE
"Bad Request" is displayed in Azure AD B2C

### ISSUE THREAD

**Issue by watanabe-yudai-dv** [MaikuB/flutter_appauth#477]
We are using "flutter_appauth" to perform login authentication and two-step authentication by email address using "AADB2C User Flow". We are currently experiencing an issue on some Android devices where a "BadRequest" is displayed when returning to the app after moving the app to the background once during two-step authentication by email address. We are investigating this issue and have not been able to find anyone else experiencing the same issue. If anyone else is experiencing the same event or knows how to resolve this issue, we would appreciate it if you could let us know.
<img width="241" alt="image" src="https://github.com/MaikuB/flutter_appauth/assets/131440434/915e3be6-c6f3-4ecd-ab34-18cdf6231e3e">

**Comment by MeltdownInteractive** [comment]
I would suggest using Chrome Dev Tools to inspect the emulator browser so you can see which error is causing the Bad Request.
In my case it was a certificate issue.
