### ISSUE TITLE
Add metadata in federated sign up

### ISSUE THREAD

**Issue by aadnegture** [MaikuB/flutter_appauth#481]
Hi, is it possible to add metadata during signup - in order to customize flows in for example AWS Cognito.

Like mentioned here?

https://github.com/aws-amplify/amplify-js/issues/12232

**Comment by MaikuB** [comment]
Hard to make out exactly what you're after as there'sa fair bit of info that makes an assumption that the person reading it is familiar with an AWS SDK, which I'm not and would be time consuming for me to look into. 

In general OAuth 2.0 defines parameters as being passed through query string parameters. If there's additional parameters via the plugin beyond what's available then there's an `additionalParameters` property for the various request classes. This would be the only option available and is presumably how AWS extracts the info you're referring to
