### ISSUE TITLE
Login without leaving app?

### ISSUE THREAD

**Issue by jjjessen** [MaikuB/flutter_appauth#489]
I have followed the example from the repo and I have authorization working fine in my app. However, I would prefer that the user doesn't leave my app i.e. I would like to design the email/password fields and send the values to the provider. Does flutter_appauth support such a scenario?

**Comment by lyio** [comment]
The whole point of the OAUTH spec is that your App does not get to know and handle the users' credentials. If you are in control of the identity provider you can customize the login page that is displayed. For other identity providers such as Google or MS you will not have control over that. And mind you, as a user I would never ever type my Google credentials into some random App's sign-in page. That's how your account gets stolen

**Comment by MaikuB** [comment]
Thanks @lyio for chiming in on this. Going to close this but please note that as implied by @lyio that you will need to understand OAuth, the various flows available and what is recommended. In theory the plugin supports the flow you're asking about provided the native SDKs but not tried it myself personally for reasons already mentioned.
