### ISSUE TITLE
[Request] [PrivacyManifest] Bump AppAuth to 1.7.3 for Google Sign In iOS 7.1.0

### ISSUE THREAD

**Issue by MewanWA** [MaikuB/flutter_appauth#490]
Hi, We are trying to get our app ready to include all the required PrivacyManifests for iOS before May 1st, 2024. 
Google Sign-In iOS is now in version [7.1.0](https://github.com/google/GoogleSignIn-iOS/blob/main/CHANGELOG.md#710) which has included the PrivacyManifests in the latest version. Can we get AppAuth bumped to 1.7.3?

I am getting this issue when trying to run a pod install.

``` 
[!] CocoaPods could not find compatible versions for pod "AppAuth":
  In Podfile:
    GoogleSignIn (~> 7.1.0) was resolved to 7.1.0, which depends on
      AppAuth (< 2.0, >= 1.7.3)

    flutter_appauth (from `.symlinks/plugins/flutter_appauth/ios`) was resolved to 0.0.1, which depends on
      AppAuth (= 1.6.2)
```

**Comment by MaikuB** [comment]
Will bump but FYI in future that you can also submit a PR

**Comment by MewanWA** [comment]
Ah yeah. I was using 6.0.2. Thanks Maiku!
