### ISSUE TITLE
Native Client returns and empty file

### ISSUE THREAD

**Issue by christianmadhan** [MaikuB/flutter_appauth#498]
(https://github.com/MaikuB/flutter_appauth/assets/33845505/bfda0548-def3-424f-ae76-9e1bd0174287)

I successfully authenticate through the authrozation endpoint
but then the app calls the redirect url which is https://login.microsoftonline.com/common/oauth2/nativeclient
and that endpoint is an empty page

what do i do here, is it a bug?

**Comment by MaikuB** [comment]
You'll need to check that you understand how OAuth works and what you need to do to configure your identity provider so it's configured properly for your app. The behaviour you see would be due to how you've configured it and not a bug with the plugin
