### ISSUE TITLE
Closing the browser

### ISSUE THREAD

**Issue by LazyDave76** [MaikuB/flutter_appauth#5]
Thanks for the work you’ve put into this, it’s great.  When using this, I find that the browser window is pushed to background rather than being closed.  How can I close the browser window?

**Comment by MaikuB** [comment]
Afraid we don't have control over that as far as I know. This is really occurring as the use of custom tabs is broken in Android due to issues with jetifier that I've mentioned in the readme. If it was working then the browser would appear in a modal fashion

**Comment by LazyDave76** [comment]
Ah, ok.  I understand now, thanks.

**Comment by MaikuB** [comment]
No worries. Closing this as there's nothing I can action here. Unfortunately will need to wait until Jetifier has fixed the issues with Chrome Custom Tabs
