### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by dieos2** [MaikuB/flutter_appauth#51]
Hello, in the example when you click the button to go to the login page, a screen without a URL appears, as if it were inside the app itself, but in my example it opens Chrome and then returns to the app. Does anyone know why?

**Comment by MaikuB** [comment]
What version of Android Studio are you running? See this from the readme

> If Chrome Custom Tabs are not working in your Android app, check to make sure that you have the latest version of this plugin, Android Studio, Gradle distribution and Android Gradle plugin for your app. There was previously a known issue with the Android tooling with AndroidX that should now be resolved since Android Studio 3.4 has been released

**Comment by dieos2** [comment]
i'm using my mi 9t smartphone, and the andrid studio version is 3.5

**Comment by MaikuB** [comment]
Actually, if I understood you correctly, the example app in this repo works fine for you but not your own code. If that's the case then make sure you have configured your app properly, including that it is using AndroidX libraries

**Comment by dieos2** [comment]
both work well, just have the window difference d chrome, I want my app, just like the example. vu check if something is missing in relation to android x

**Comment by dieos2** [comment]
I checked the files and my code is with androix correctly. Both apps are the same, but mine doesn't open in the app window itself.

**Comment by MaikuB** [comment]
Wonder if perhaps you turned on some setting in your app that makes it open in Chrome. Otherwise, will need a link to a repo that can reproduce the issue

**Comment by dieos2** [comment]
I did not activate any permission, it works like this from the beginning, I will provide the repository

**Comment by dieos2** [comment]
Follow repo, https://github.com/dieos2/Flutter_appauth.git
I left only the login code.

**Comment by MaikuB** [comment]
Looks like your app is using an old version of the Gradle plugin. This link has some info about how to update it

https://developer.android.com/studio/releases/gradle-plugin#updating-plugin

**Comment by dieos2** [comment]
It worked, thank you very much.

**Comment by dieos2** [comment]
It worked, thank you very much.
