### ISSUE TITLE
Add support for password grant

### ISSUE THREAD

**Issue by andermoran** [MaikuB/flutter_appauth#52]
Can we have the option to pass fields in to automatically get a token? [This is what I'm talking about](https://developer.okta.com/blog/2018/06/29/what-is-the-oauth2-password-grant). The Flutter package [oauth2](https://pub.dev/packages/oauth2) has this functionality implemented. Check out the bottom of the oauth2 page.

**Comment by MaikuB** [comment]
Not looking to do this as the purpose of this plugin is to be a wrapper around the appauth libraries. If you need to make use of password grant then you could issue a post request of your own

**Comment by MaikuB** [comment]
Forgot to add, I believe you should be able to use the oauth2 package if you wanted to use password grant. If you look at the implementation you could see it's a post request
