### ISSUE TITLE
Can I use this package with Microsoft Entra External IDs?

### ISSUE THREAD

**Issue by robertmrobo** [MaikuB/flutter_appauth#529]

**Comment by MaikuB** [comment]
In general, if an identity provider supports OAuth then you **should** be able to use this plugin. This is a general plugin to support apps leveraging OAuth so you should verify yourself on it it'll work for your use cases. There are times identity providers do not adhere to the specs or have other additional requirements so this another reason why you should  verify this. For what it's worth, I've already used this with Azure B2C and Azure Active Directory (now called Microsoft Entra ID)
