### ISSUE TITLE
Getting duplicate suggestion in the popup after login in android.

### ISSUE THREAD

**Issue by nahiduzzaman-at-selise** [MaikuB/flutter_appauth#533]
![image](https://github.com/user-attachments/assets/67a7042e-0826-45e9-b484-337749b9f01e)
Hello, as shown in the image why i am receiving two same app suggestions? 

Also is there any way to turn off the popup?

**Comment by MaikuB** [comment]
This is outside the control of the plugin as it's a system prompt. This happens when Android finds two apps that process the redirect URI. Whilst it might look like a duplicate to your based on the name of the apps, it would imply that you have two apps with the name installed on the device
