### ISSUE TITLE
PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: Unable to parse ID Token]

### ISSUE THREAD

**Issue by gg-circlesarrows** [MaikuB/flutter_appauth#536]
currently getting this error

> PlatformException (PlatformException(authorize_and_exchange_code_failed, Failed to authorize: [error: null, description: Unable to parse ID Token], {code: 8, error_description: Unable to parse ID Token, root_cause_debug_description: org.json.JSONException: Value �"���&��B of type java.lang.String cannot be converted to JSONObject, user_did_cancel: false, type: 0, error: null, error_uri: null, legacy_error_details: Value �"���&��B of type java.lang.String cannot be converted to JSONObject, error_debug_description: AuthorizationException: {"type":0,"code":8,"errorDescription":"Unable to parse ID Token"}}, null))

my code is
```
final TokenResponse? token = await _appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          _clientId,
          _redirectUrl,
          serviceConfiguration: const AuthorizationServiceConfiguration(
            tokenEndpoint: tokenUrl,
            authorizationEndpoint: authorizeUrl,
            endSessionEndpoint: revokeUrl,
          ),
          scopes: [
            'openid',
            'email',
            'https://api.customers.com/auth/customer.graphql',
          ],
          preferEphemeralSession: true,
          promptValues: [
            'login',
          ],
        ),
      );

```

**Comment by PAzter1101** [comment]
@gg-circlesarrows  Hello!
I have the same problem. How did you manage to fix it?
