### ISSUE TITLE
Is it possible to custom 'externalUserAgent' parameter for iOS?

### ISSUE THREAD

**Issue by john-slow** [MaikuB/flutter_appauth#538]
Hey guys, our team is having a problem, we want to hide the alert when logging to iOS, however, we don't want to use ephemeral browser because it would clear session. So  is it possible to expose 'externalUserAgent' parameter for iOS or can we add a custom SFSafariController as the externalAgent so that user would be able to use their own SFSafariController or is there an alternative?

**Comment by john-slow** [comment]
Is it possible that we use an enum type:
enum ExternalAgentType {
  ASWebAuthenticationSession,
  EphemeralSession,
  SFSafariViewController
}
to decide which type of external agent is been used here instead of using boolean preferEphemeralSession to only toggle between ASWebAuthenticationSession and EphemeralSession?

**Comment by vmichalak** [comment]
We currently have the same issue on our app. We need to be capable to use a non ephemeral session (we have some webviews in the app to manage the user profil).

**Comment by john-slow** [comment]
One solution we are doing right now is using this SFSafariController [](https://gist.github.com/WilliamDenniss/18f3779b4a310361bb955cf4e534f29c)
which works well but it doesn't have an open API in flutter so we have to modify the package.

**Comment by john-slow** [comment]
> We currently have the same issue on our app. We need to be capable to use a non ephemeral session (we have some webviews in the app to manage the user profil).

here is a [pr](https://github.com/MaikuB/flutter_appauth/pull/539) that I opened which fixed this issue

**Comment by Manraj45** [comment]
This would also be really helpful for us. We are having the same issue. Thanks for creating that PR!

**Comment by Mapk26** [comment]
Same problem, other webviews cannot access the same session. It would be great to have a non-ephemeral session option

**Comment by john-slow** [comment]
This issue has been resolved in the [prerelease v8.0.0-dev.3](https://github.com/MaikuB/flutter_appauth/releases/tag/flutter_appauth-v8.0.0-dev.3)
