### ISSUE TITLE
Failed to get token: [error: invalid_client, description: null]

### ISSUE THREAD

**Issue by andreacona96** [MaikuB/flutter_appauth#540]
Hello,
I am trying to integrate OIDC login into my Flutter app, but the .token() method keeps responding with "Failed to get token: [error: invalid_client, description: null]". 
When I call the .authorize() method, I can correctly see the authorizationCode, codeVerifier, and nonce. 
However, when I pass these parameters to the .token() method, I receive the error. 

Can you help me? 

Thanks.

**Comment by MaikuB** [comment]
This error occurs when you have a configuration issue and won't be an issue with the plugin itself. As such, this is something you would need to investigate further on your end
