### ISSUE TITLE
Should return `OIDExternalUserAgentIOSSafariViewController` instead of `OIDExternalUserAgentIOSNoSSO`

### ISSUE THREAD

**Issue by john-slow** [MaikuB/flutter_appauth#547]
There's a minor error here; you should return `OIDExternalUserAgentIOSSafariViewController` instead of `OIDExternalUserAgentIOSNoSSO`.
https://github.com/MaikuB/flutter_appauth/blob/acaef1f598400176958629260981e5861718130f/flutter_appauth/ios/Classes/AppAuthIOSAuthorization.m#L172C1-L175C4

**Comment by MaikuB** [comment]
Ah yep, thanks for pointing that out
