### ISSUE TITLE
How to disable code_challenge

### ISSUE THREAD

**Issue by ghtea** [MaikuB/flutter_appauth#558]
I’ve encountered a scenario where I need to disable the sending of the code_challenge during the authentication process (authorize method).
 
Could you consider adding a feature or a configuration option that allows developers to disable the code_challenge.

**Comment by MaikuB** [comment]
You'd need to check if the AppAuth SDKs support it and if they do then submit a PR

**Comment by dittakhan** [comment]
Reviewing the code, there does not appear a way to disable it.

**Comment by MaikuB** [comment]
Closing this then
