### ISSUE TITLE
iOS: OIDExternalUserAgent.h file not found

### ISSUE THREAD

**Issue by jbnixdorf** [MaikuB/flutter_appauth#568]
Building my Flutter App with 7.0.1 is working fine but when upgrading the plugin to 8.0.0+1 the following error occurs when building iOS:

```
...

Running pod install...                                           1,340ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,544ms
Xcode build done.                                           50.5s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'OIDExternalUserAgent.h' file not found
/Users/dev/.pub-cache/hosted/pub.dev/flutter_appauth-8.0.0+1/ios/Classes/OIDExternalUserAgentIOSSafariViewController.h:18:8


Parse Issue (Xcode): Could not build module 'flutter_appauth'
/Users/dev/project/ios/Runner/GeneratedPluginRegistrant.m:15:8


Encountered error while building for device.
```

Building with latest Flutter (Channel stable, 3.24.4, on macOS 14.7.1 23H222 darwin-arm64, locale en-DE)

Can you help me to understand what I'm doing wrong or is this an issue of the plugin? Thanks!

**Comment by MaikuB** [comment]
Not absolutely certain on this one as I haven't run into the issue myself and plugin has been out for a while now that I would expect others to run into a similar issue. Furthermore, the repo makes use of GitHub actions to ensure that the example app can compile file and hasn't run into issues either.

I would guess it's there's an issue on your local environment.

@john-slow could the subtleties on having import statements using angle brackets vs quotation marks be the issue? I'm referring to code around [here](https://github.com/MaikuB/flutter_appauth/blob/a36c5fdc7b5f2cacc9043163de952c3046cac91a/flutter_appauth/ios/Classes/OIDExternalUserAgentIOSSafariViewController.h#L19). I don't work in Objective-C but from what I know, quotation marks were more reserved for local files in the same package/app. Whilst it has worked for us, perhaps there are scenarios where this causes issues with some compilers?

**Comment by jbnixdorf** [comment]
I removed the plugin, cleaned the cache with `flutter clean`, deleted the `Pods` folder of the project and the `.pub-cache` in the user folder. Then I added the plugin again. I also rebooted my Mac and repeated the steps, but still the same error. Is there any another cache I could remove?

Shouldn't the file be in this folder?
![image](https://github.com/user-attachments/assets/335e459e-b64f-46dc-9266-9c27592d4f1d)

I'm working with Xcode 16.1 on macOS 14.7.1 (Sonoma)

**Comment by john-slow** [comment]
Are you working with Android Studio? If yes, try to invalidate caches of Android Studio. 
Try if this one would help: https://stackoverflow.com/questions/5198905/h-file-not-found

**Comment by jbnixdorf** [comment]
Android Studio is installed because it's needed for building the Android apk and aab. By the way that works fine but generally I do not open the project with Android Studio and it shouldn't be involved when building the iOS file. However, I invalidated the cache but as expected it did not change anything.

I also tried to clean and build with Xcode like suggested but I get the same error.

Should the missing file be in the folder of the screenshot above?

**Comment by john-slow** [comment]
> Android Studio is installed because it's needed for building the Android apk and aab. By the way that works fine but generally I do not open the project with Android Studio and it shouldn't be involved when building the iOS file. However, I invalidated the cache but as expected it did not change anything.
> 
> I also tried to clean and build with Xcode like suggested but I get the same error.
> 
> Should the missing file be in the folder of the screenshot above?

No, I believe it comes from the [AppAuth iOS package](http://openid.github.io/AppAuth-iOS/docs/latest/_o_i_d_external_user_agent_8h.html)

**Comment by jbnixdorf** [comment]
> No, I believe it comes from the [AppAuth iOS package](http://openid.github.io/AppAuth-iOS/docs/latest/_o_i_d_external_user_agent_8h.html)

And this is downloaded as dependency, right? Can you tell me where this file should be placed on the build system? Somewhere in the `pub.dev` folder like the `flutter_appauth` package?

**Comment by MaikuB** [comment]
@jbnixdorf I suspect the change in https://github.com/MaikuB/flutter_appauth/tree/appauth-import would fix it. Are you able to have your app point to this to see if it fixes the issue before I see if I should publish the change? [This page](https://dart.dev/tools/pub/dependencies#git-packages) provides examples of how to reference via Git. Should be a harmless that I could publish anyway but prefer if you could test it first

**Comment by jbnixdorf** [comment]
Perfect, that fixed the issue for me!
Because of company policies I'm not able to reference and download from github, but I checked your commits and replaced all three "OID..." imports with the import of "AppAuth.h". Then I'm able to build without issues.

Hope you have time to publish this change soon. Thank you very much for your help!
