### ISSUE TITLE
Not getting Authorization code intact when using 'FlutterAppAuth.authorize()' instead of `FlutterAppAuth.authorizeAndExchangeCode`

### ISSUE THREAD

**Issue by zzaman88** [MaikuB/flutter_appauth#571]
I am using `FlutterAppAuth.authorize()` to obtain the authorization code directly, instead of using `FlutterAppAuth.authorizeAndExchangeCode`. However, when I try to use the authorization code, I encounter an error stating that it has already been used. 

How can I resolve this issue? Please provide suggestions as soon as possible.

**Comment by MaikuB** [comment]
This is something you'd need to investigate further on and is most likely specific to you. Saying this as if it's an actual issue then there should be a lot more others with this this problem and that it should be reproducible (e.g. using the example app)
