### ISSUE TITLE
iOS giving 404 error.

### ISSUE THREAD

**Issue by penkin** [MaikuB/flutter_appauth#62]
When I create the request on an Android device everything works as expected, the login pages shows from Azure AD B2C, I can login etc.

When I do the same on iOS the web popup shows but shows a 404 error page as though the URL is not the same or something. I have compared the URLs when using Android and iOS and they are exactly the same. When I take that URL and paste it into the iOS Emulator's Safari, the correct page shows.

Anybody else seen this issue?

**Comment by MaikuB** [comment]
I haven't come across this issue

**Comment by penkin** [comment]
It's really strange. Run it on either the emulator or device and Android works as expected but iOS shows a 404 error as though the URL is being cut or something. Not sure if there is something on the iOS side that I can look at?

![Screenshot 2019-12-02 at 20 42 02](https://user-images.githubusercontent.com/771661/70048685-93ca1a80-15d3-11ea-8c8e-68c53e9f2f25.png)

**Comment by penkin** [comment]
Found the issue.

Our authorisation URL for Azure B2C was `https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_sisu`. In iOS it removes everything after the `?` and rebuilds the query parameters of the URL without the policy parameter.

What we ended up doing was making the authorisation URL `https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/oauth2/v2.0/authorize` and passing `additionalParameters: {'p': 'b2c_1_sisu'}` to the `AuthorizationTokenRequest`.

This then works on both Android and iOS.

**Comment by bryanCancelWT** [comment]
I've been posting this everywhere to try and help
but if you search for my comment on this repo you will learn how to setup with azure ad from iOS and android
took me forever, hope these comments help you and one day you can pay it forward
