### ISSUE TITLE
LoginHint for iOS

### ISSUE THREAD

**Issue by march93** [MaikuB/flutter_appauth#63]
I'm unable to fetch the `loginHint` for iOS, but it works just fine on Android. I noticed in Android that the `loginHint` is processed in `performAuthorization`, but I don't see it in iOS. I'm not familiar with Objective-C so I may be missing something! Any idea if there's something missing for iOS?

**Comment by march93** [comment]
Update: I was able to figure out how to pass `loginHint` on iOS. You have to pass `{'login_hint': VALUE_HERE}` into `additionalParameters`

**Comment by MaikuB** [comment]
I'll take a look at the iOS code, may have been possible that the code to parse the `loginHint` property was missed. However, as you found out, it's possible to use the `additionParameters` property for passing extra parameters that identity providers support beyond the standard ones

**Comment by MaikuB** [comment]
Found the problem, it wasn't being passed when not using service discovery. This branch should fix it https://github.com/MaikuB/flutter_appauth/tree/63. Will merge it soon. Works fine for me but if you want to try it out and confirm then that would be helpful

**Comment by MaikuB** [comment]
This has been merged and released now. Will close this now. Feel free to re-open if this is still an issue

**Comment by march93** [comment]
@MaikuB confirmed that this works now, thanks!

**Comment by bryanCancelWT** [comment]
@march93  what is the login hint here

is it the actual email of the user, or the actual user name?

or is it perhaps the the input TYPE from html?
or perhaps the input AUTOCOMPLETE value from html?
