### ISSUE TITLE
iOS: authorize() and authorizeAndExchangeCode() Futures do not complete

### ISSUE THREAD

**Issue by Lootwig** [MaikuB/flutter_appauth#64]
Calling the methods mentioned in the title opens the Authorization endpoint as expected. On successful sign-in, the redirect takes place. If the redirect URI is `my-scheme-as-registered-in-plist://whatever`, the browser closes, but the Future never completes. If the redirect is to my own backend server, the window stays open (duh).
The point is, it's unclear what makes a "correct" redirect that triggers the Future to complete.

On Android, the authorization page is not even opened (the future doesn't complete either)

**Comment by MaikuB** [comment]
Have you completed the setup steps mentioned in the readme?

**Comment by Lootwig** [comment]
did I overlook anything apart from the changes to Info.plist? That's all I did.

I'm using the explicit `serviceConfiguration` by the way, the API I'm using does not provide an open ID configuration. Might this be an issue? Again, I wonder what makes up a redirect that AppAuth is able to "parse" and how the one happening in my case might differ from that.

**Comment by MaikuB** [comment]
The scheme configuration is done on both platforms as that is what allows the app to process the redirect. Possible you have entered it incorrectly. There's a sample app in the repo you can use as a comparison if you haven't already. Not sure if you have configured your server to register the redirect url either

**Comment by Lootwig** [comment]
I configured the scheme for both platforms. Of course, I can not see what parameters are passed to 

> Not sure if you have configured your server to register the redirect url either

Which one is "my server"? The one with the API? That one does redirect to whatever URL I specify (custom scheme as well as backend server), if that's what you mean by "register the redirect url". It also appends the query parameters "code" and "state".

I used these when I was authenticating via WebViews. But with the AppAuth plugin, the code seems to not be retrieved from the redirect. That's why I am asking about the expected "layout" of the redirect. Any specific headers required?
I was expecting this flow:

FlutterAppAuth.authorize()
Browser opens
User authenticates
API server redirects to my-custom-scheme://bla?code=authCode
FlutterAppAuth.authorize() future completes with code = authCode from redirect

But this is obviously not what is going on. Can you point out what I am missing?

**Comment by MaikuB** [comment]
By your server, I'm referring to the identity provider. Identity providers like Azure B2C need you register your application and specify the redirect url for it. I've already pointed what's required

 Did you use the example app as a comparison and have you tried running it to see if it works for you? Perhaps your identity provider doesn't support grant code authorisation flow? I can't really tell what's missing. The kind of things that are generally required are already covered in the readme.

When things aren't work it's generally either something hasn't been configured properly, your identity provider isn't compatible (doubtful but could be possible) or your identity provider requires you to pass additional details. None of these are things I can help with.

**Comment by Lootwig** [comment]
The demo identityserver works just fine. I am completely aware that this is most likely an issue with the identity provider I'm using (spotify). I am trying to work around this by redirecting first to my backend, then sending a 302 response from there that will be picked up by the plugin.

When using the demo.identitiyserver example, and providing my custom scheme for redirect, this gets captured as intended. But I don't have a way to figure out how the demo.identityserver redirect looks in order to recreate a similar response on my backend and was just hoping you might have more insight into this than I do, as I only just started working on this. Feel free to close the question.
