### ISSUE TITLE
Open Chrome inside the app instead of creating a new Chrome task

### ISSUE THREAD

**Issue by rocboronat** [MaikuB/flutter_appauth#68]
Hello!

First things first: thanks for the library!

One issue there: when you log in with the library, a Chrome task remains opened after successfully logged in. It should happen in a [Chrome Custom Tab](https://developer.chrome.com/multidevice/android/customtabs#implementationguide).

Here's a screenshot to showcase the issue. You can see that the app I'm working on is focused, but there's a Chrome task beside it.

![photo_2020-01-23_14-35-34](https://user-images.githubusercontent.com/456499/72988976-a4d22380-3ded-11ea-9cb0-ba4414f2abd8.jpg)

**Comment by MaikuB** [comment]
The plugin does normally open it inside a Chrome Custom Tab. Perhaps the device and/or Chrome version you're using doesn't support it or there's a bug. Regardless, this is outside of my control as the plugin is a wrapper for a native SDK that does all of the real work
