### ISSUE TITLE
Ability to remember login

### ISSUE THREAD

**Issue by andermoran** [MaikuB/flutter_appauth#73]
I want to be able to log in like in the example and then save credentials and use those credentials to automatically sign-in next time the app is opened. Is that possible with this library? If so, can that be added to the readme? If not, can this capability be added?

**Comment by andermoran** [comment]
Is it possible to get a new access token via your refresh token if you don't know the discovery url? If not, can this feature be added?

**Comment by andermoran** [comment]
Nevermind I'm dumb and didn't fully read your documentation on how to get the discovery url. It would be nice tho if there were a method where you could just put the issuer instead. Thanks!

**Comment by MaikuB** [comment]
You can use the same method even if you don't have the discovery url. The readme is showing discovery url as that's the more common approach, you can pass the service configuration with the endpoints explicitly specified. This is similar to what can be done with the authorisation related methods

**Comment by andermoran** [comment]
Is it possible to get open ID metadata such as the user's profile with this API?
