### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by sowens-csd** [MaikuB/flutter_appauth#74]
I've had a very good experience with the plugin so far, thanks for the good work! 

I noticed a minor doc issue in the Readme code. It shows this:
```dart
final AuthorizationTokenResponse result = await appAuth.token(TokenRequest('<client_id>', '<redirect_url>',
        discoveryUrl: '<discovery_url>',
        refreshToken: '<refresh_token>',
        scopes: ['openid','profile', 'email', 'offline_access', 'api']));
```

Where it says `AuthorizationTokenResponse` it should be `TokenResponse` I think.

**Comment by MaikuB** [comment]
Yep you're right. Thanks for picking that up. Did you want to submit a pull request to fix that?
