### ISSUE TITLE
Multiple Redirect Schemes

### ISSUE THREAD

**Issue by isojtouano** [MaikuB/flutter_appauth#81]
Greetings,

How do I add more redirect schemes in the Gradle -> manifestPlaceholders? I have already tried adding elements in the array but it does not work:

`manifestPlaceholders = [
                'appAuthRedirectScheme': '<redirect-scheme-here>',
                'appAuthRedirectScheme': '<redirect-scheme-here>',
        ]`

The code above does not work. What can I do? Thanks.

**Comment by MaikuB** [comment]
Sorry but isn't something I know. I would suggest you ask on the repository for the AppAuth Android SDK as that functionality is provided by the native SDK that this plugin wraps around. It's not something provided directly by this plugin.  I suspect you can only have one redirect scheme and the array is there to allow for multiple configuration values to be replaced

**Comment by isojtouano** [comment]
Alright, thank you again.
