### ISSUE TITLE
Cast Exception on using tokenAdditionalParameters Map

### ISSUE THREAD

**Issue by svendroid** [MaikuB/flutter_appauth#86]
When using the method `token` of `method_channel_flutter_appauth.dart` the `tokenAdditionalParameters` attribute of the returned TokenResponse throws following Exception, as soon as I use it:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type 'int' is not a subtype of type 'String' in type cast
#0      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:25)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#2      CastMap.forEach (dart:_internal/cast.dart:287:13)
#3      MapBase.mapToString (dart:collection/maps.dart:35:9)
#4      MapMixin.toString (dart:collection/maps.dart:192:32)
#5      _StringBase._interpolate (dart:core-patch/string_patch.dart:845:19)
```

The cause for this problem is the cast in this line https://github.com/MaikuB/flutter_appauth/blob/123010981d4d84c7addd2354c2e0e936a75c05b2/flutter_appauth_platform_interface/lib/src/method_channel_flutter_appauth.dart#L65

it should be cast to 
`result['tokenAdditionalParameters']?.cast<String, dynamic>());`.

**Comment by MaikuB** [comment]
Oh bugger, thanks for picking up on that!

**Comment by svendroid** [comment]
Should I provide a pull request? I would only need to push it

**Comment by MaikuB** [comment]
If you could then that would be great. I don't think I've done it I've setup a template for this repo yet but can you prefix the PR's title with _[flutter_appauth_platform_interface]_ as well?
