### ISSUE TITLE
[question] What is lunching webview/browser to login?

### ISSUE THREAD

**Issue by codenamics** [MaikuB/flutter_appauth#93]
As stated in question what is lunching brower to type login and password. I need this info to try to close it after logout

**Comment by MaikuB** [comment]
This plugin is a wrapper for native Android and iOS SDKs and the code for showing the browser is done by those SDKs. If you want more info on how they work, then you can go to their respective repositories for more info (e.g. to look at the code)

https://github.com/openid/AppAuth-Android
https://github.com/openid/AppAuth-iOS
