### ISSUE TITLE
Support for FlutterFragmentActiviy

### ISSUE THREAD

**Issue by kenso23** [MaikuB/flutter_appauth#97]
Hi! 

I have been using you great plugin for some time now. But we are integrating our app with both flutter_appauth and local_auth for fingerprint and faceID. 

This works very well with IOS, but on Android we get a Missing Plugin error, if we change MainActicity to be a FragmentActivity.

Do you have any workaround or a fix for this in pipeline. I am in a bit of a time issues else i would have greated a pull request for it.

the exeption is the same as: #66

**Comment by MaikuB** [comment]
No but are you using the latest version as I had already moved the plugin to use the V2 embedding APIs. Your description contradicts the title of the issue (FlutterFragmentActivity is mentioned in the title but post says it's FragmentAcitivity)

**Comment by kenso23** [comment]
Sorry MaikuB 
When using local_auth package, you need to switch from using FlutterActivity in mainActivity to FlutterFragmentActivity - but then flutter_appauth, is coming up with missing_plugin.

MissingPluginException (MissingPluginException(No implementation found for method authorizeAndExchangeCode on channel crossingthestreams.io/flutter_appauth)).

I am using 0.8.1. without any other modification.

**Comment by MaikuB** [comment]
You likely need extra configuration in your Android project. If you were copying the code from the example code at https://github.com/flutter/plugins/blob/master/packages/local_auth/example/android/app/src/main/java/io/flutter/plugins/localauthexample/MainActivity.java, notice they put a line to register the `local_auth` package. This only registers their plugin. You may need to add a similar line for this plugin. May be possible that overriding `configureFlutterEngine` isn't needed if you follow the steps at https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects to add the meta tag mentioned there.

I'm going to close this as this isn't an issue with this plugin but a configuration issue in your application and if you run into more issues, then you should ask on the Flutter repository on how other plugins can be registered through the way you've described. Their documentation only mentions `FlutterActivity` in that upgrade document

**Comment by kenso23** [comment]
Hi 
I am not sure that is true. I am using the following Kotlin MainActivity
`import io.flutter.app.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity() {
     fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }`
And this is not working with flutter_Appauth, but all other plugins and as shown in above code, i am using the full plugin registry. moreover i am using the meta tag mentioned in the link. But Thank for the help. I will try to ask in the flutter repo how to get this plugin registred when using FlutterFragmentActivity.

**Comment by MaikuB** [comment]
`import io.flutter.app.FlutterFragmentActivity` <- this is the wrong namespace to be using with v2 embedding. Take a look at the example app for the `local_auth` package (`import io.flutter.embedding.android.FlutterFragmentActivity`)

**Comment by kenso23** [comment]
So to be sure - the io.flutter.app.FlutterFragmentActivity is an Old and wrong namespace to be using the V2. I Will try this, thank you for Quick reply!

**Comment by MaikuB** [comment]
> So to be sure - the io.flutter.app.FlutterFragmentActivity is an Old and wrong namespace to be using the V2. 

Yes. You can look at the migration guide I linked to earlier (https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) that shows the differences

**Comment by kenso23** [comment]
This worked, just for others that might have the issue. Thank you MaikuB for a great plugin. Sorry for my confusion :-)
