### ISSUE TITLE
PlatformExceptions get plugin into a broken state

### ISSUE THREAD

**Issue by athornz** [MaikuB/flutter_appauth#98]
I've seen a few times now where if I get a platform exception when calling a method on the plugin, the plugin gets into a broken state because it thinks there is a pending operation in progress.

It seems like any method call may need to be surrounded in a try/catch so the pending operation can be cancelled, before rethrowing the exception?

I've seen this on Android, not sure about iOS yet.

**Comment by MaikuB** [comment]
Are there steps that can be used to reproduce this with the example app in this repo? I'm wondering if there's something that can be done as this does delegate most of the logic to the native SDK

**Comment by athornz** [comment]
I came across the issue by passing in a null client id when authorizing, I think that should reproduce it.

**Comment by MaikuB** [comment]
This should be fixed in 0.8.2 now
